### ISSUE TITLE
browserslist error(module not found) when run next build 

### ISSUE THREAD

**Issue by ale-grosselle** [vercel/next.js#33325]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.0.9-canary.0
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

12.0.7 does't have this bug, Only 12.0.8 (and canary)

Running "next build" command I received this error:

```
> Build error occurred
Error: Cannot find module 'browserslist-config-company'
    at Function.webpackEmptyContext [as resolve] 
```

The package is properly installed:
![Schermata 2022-01-14 alle 23 37 09](https://user-images.githubusercontent.com/6173088/149594266-8e5ab3ad-cfd7-4bbf-9f79-f01b640e1bfa.png)

The package.json browserlist:

```
"browserslist": [
    "extends browserslist-config-company"
  ],
```

Definition of _browserslist-config-company/index.js_

`module.exports = ['cover 90% in IT', 'last 2 years', 'not dead', 'not IE 11'];`

Including browserlist rules from an external file ("_extends browserslist-config-company_"), probably is the root cause of the problem. Hard coding the rules:

```
"browserslist": [
    "cover 90% in IT", "last 2 years", "not dead", "not IE 11"
  ],
```
all works as expected 

### Expected Behavior

Including browserlist rules from an external package, it won't break the build.

### To Reproduce

Simply, try to define in your package.json the browserslist attribute, including rules from an external package

**Comment by balazsorban44** [comment]
Hi, I could not reproduce this. Could you create a minimal reproduction?

**Comment by ale-grosselle** [comment]
Hello @balazsorban44,
1. download this repo: https://github.com/ale-grosselle/next-browserconfifg
2. run `next build`

I will get this error:
<img width="1368" alt="Schermata 2022-01-15 alle 16 56 01" src="https://user-images.githubusercontent.com/6173088/149628469-0e2b5115-51ea-4f71-8b5a-67304401f5bb.png">

**Comment by DennisNeuendorfJimdo** [comment]
It seems this regression happened between 12.0.7 and 12.0.8. We have two Nextjs-projects with working a browserlists-extends on 12.0.7 like:
```
extends @myscope/browserslist-config-foo
```

Both break when upgrading to 12.0.8.

with errors  like :
```
error - ./node_modules/next/dist/client/dev/amp-dev.js
Error: Cannot find module '@myscope/browserslist-config-foo'
    at Array.reduce (<anonymous>)
```

**Comment by DennisNeuendorfJimdo** [comment]
The reproduction-repo form @ale-grosselle  shows the error (when you delete the package-lock.json). Pinning nextjs to 12.0.7. fixes the problem.

**Comment by topaxi** [comment]
Running into the same issue, also a scoped browserslist config, any workarounds besides downgrading?

**Comment by DennisNeuendorfJimdo** [comment]
The bug seems to be introduced in this [commit](https://github.com/vercel/next.js/commit/3667eba38559e5ccb810bade4779cda3649f1413#diff-35e60cb9cfc6f14c2998799e7e5a28e5adfd6ededc273851531da3a1e506b0d4) by switching to a precompiled version of browserslist. 

I replaced the compiled import `require("next/dist/compiled/browserslist")`  to the former `require("browserslist")` which solved the issue.

**Comment by topaxi** [comment]
Very nice, thanks for the quick fix 🎉 🙇

**Comment by DennisNeuendorfJimdo** [comment]
Awesome! Thanks for the fast work!
