### PR TITLE
Fix build stalling with styled-jsx plugins

### LINKED ISSUE #12727: Can't build app with 9.4.0 when using custom babel config
# Bug report

## Describe the bug

Since v9.3.7-canary.17 I can't build my app. It builds forever. When I remove the custom `.babelrc` it works fine again.

```js
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-sass", "styled-jsx-plugin-postcss"]
        }
      }
    ]
  ],
  "plugins": [
    ["macros"],
    [
      "module-resolver",
      {
        "root": ["./"],
        "alias": {
          "~": "./"
        }
      }
    ],
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragmaFrag": "React.Fragment"
      }
    ]
  ]
}
```

### LINKED ISSUE #12740: Custom .babelrc config does not work on 9.4.0
# Bug report
When using custom configs in `next.config.js` and a custom `.babelrc` file, the custom babel config is not applied.

## Describe the bug

I have custom configs in `next.config.js` and am using a custom `.babelrc` and this [plugin](https://github.com/josephluck/next-plugin-custom-babel-config) to load it. On next@9.3.6, this worked perfectly fine for me. However, when I upgraded to version 9.4.0, it stopped working.

I made some structural changes to my app and realized that I could just use the built-in custom `.babelrc` approach as outlined in the docs [here](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config). However, when I used this method on version 9.3.6, it no longer applies my custom babel config. It also does not work on version 9.4.0.

All I do is add some plugins in the `.babelrc`.

When I run the development server, I see the following in my terminal. It states that a custom `.babelrc` is being used; however, it states it after the app begins compiling.

Screen Shot 2020-05-11 at 11 54 54 AM

When I add this line to `next.config.js`, it works again.
```
defaultLoaders.babel.options.configFile = path.resolve(__dirname, '.babelrc');
```

## To Reproduce

1. Create a next app with `next.config.js` and `.babelrc` at root
2. Add a plugin like `@babel/plugin-transform-flow-strip-types` to `.babelrc` and add a file with flow types
2. Run the app in dev mode
3. See that the custom `.babelrc` is not applied (i.e. flowtypes are not stripped, resulting a compilation error)

## Expected behavior

Custom `.babelrc` should be applied and, in the above example, flowtypes should be stripped and the app should compile successfully.

## System information

- OS: macOS
- Version of Next.js: 9.4.0
- Version of Node.js: 12.16.1

### LINKED ISSUE #12803: Project not compiling after upgrading to 9.4
# Bug report

## Describe the bug

When I run `npm run dev` it does compile first, but then when I try to reach the page it shows `compiling...` on the console but never compiles.
This did happen after upgrading to 9.4 (from 9.3.6 with which everything worked fine).

## To Reproduce

1) Clone this repo: https://github.com/beneccli/nextjs-9.4-styled-jsx-compiling-issue
2) Install and start dev
3) Try to reach http://localhost:3000

## Expected behavior

The page should load properly and give some love by saying "Hello World!".

## Screenshots

Capture d’écran 2020-05-12 à 21 14 40

## System information

- OS: macOS
- Browser: Safari
- Version of Next.js: 9.4
- Version of Node.js: v12.13.0

## Additional context

While simplifying it I realized it was happening while using `<style jsx>...</style>`.
When `<style jsx>...</style>` is removed from `page/index.js` it works just fine.
On the terminal we see that it starts loading `styled-jsx-plugin-postcss` but seems to never get past that.

As a reminder, it did work with 9.3.6. This issue appeared after upgrading to 9.4. Therefore I am not sure who is responsible here but logically I send an issue on nextjs.

### PR DESCRIPTION
**Pull request by ijjk**
This reverts to `@babel/core@7.7.7` since it appears there is an incompatibility/bug introduced in `7.8.0` which causes `styled-jsx` plugins to stall. This also adds a regression test to ensure upgrading in the feature does not cause this to break.

x-ref: https://github.com/zeit/next.js/pull/11840

closes: https://github.com/zeit/next.js/issues/12803
closes: https://github.com/zeit/next.js/issues/12740
closes: https://github.com/zeit/next.js/issues/12727
 
<details>
<summary>Related profiling information from where the app is stalling on upgraded `@babel/core` versions</summary>

babel-core v7 8 0-stalling

</details>

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Looks alright, we’d want to re-upgrade though

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| buildDuration | 11.6s | 10.9s | -644ms |
| nodeModulesSize | 58.4 MB | 58.3 MB | -43.6 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.942 | 1.886 | -0.06 |
| / avg req/sec | 1287.57 | 1325.67 | ⚠️ +38.1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.265 | 1.229 | -0.04 |
| /error-in-render avg req/sec | 1976.47 | 2033.62 | ⚠️ +57.15 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.68 kB | 6.68 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e49d.js gzip | 10.4 kB | 10.4 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.28 kB | 3.28 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.26 kB | 8.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.38 kB | 5.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| index.html gzip | 928 B | 928 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.6s | -1ms |
| nodeModulesSize | 58.4 MB | 58.3 MB | -43.6 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.68 kB | 6.68 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e49d.js gzip | 10.4 kB | 10.4 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.28 kB | 3.28 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.26 kB | 8.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.38 kB | 5.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _error.js | 850 kB | 850 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 851 kB | 851 kB | ✓ |
| link.js | 888 kB | 888 kB | ✓ |
| routerDirect.js | 880 kB | 880 kB | ✓ |
| withRouter.js | 880 kB | 880 kB | ✓ |
| Overall change | 4.36 MB | 4.36 MB | ✓ |

</details>

</details>

**Review by Timer — APPROVED** [review]
LGTM if tests pass.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.6s | -11ms |
| nodeModulesSize | 58.4 MB | 58.3 MB | -45.2 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.167 | 2.241 | ⚠️ +0.07 |
| / avg req/sec | 1153.59 | 1115.37 | -38.22 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.422 | 1.477 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1758.61 | 1692.08 | -66.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.68 kB | 6.68 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e49d.js gzip | 10.4 kB | 10.4 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.28 kB | 3.28 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.26 kB | 8.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.38 kB | 5.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| index.html gzip | 928 B | 928 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.1s | ⚠️ +1ms |
| nodeModulesSize | 58.4 MB | 58.3 MB | -45.2 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.68 kB | 6.68 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e49d.js gzip | 10.4 kB | 10.4 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.28 kB | 3.28 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.26 kB | 8.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.38 kB | 5.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/plugins-stalling | Change |
| - | - | - | - |
| _error.js | 850 kB | 850 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 851 kB | 851 kB | ✓ |
| link.js | 888 kB | 888 kB | ✓ |
| routerDirect.js | 880 kB | 880 kB | ✓ |
| withRouter.js | 880 kB | 880 kB | ✓ |
| Overall change | 4.36 MB | 4.36 MB | ✓ |

</details>

</details>

**Comment by StarpTech** [comment]
Thanks for taking it into account.
