### ISSUE TITLE
Cannot build using TypeScript 4.8.2

### ISSUE THREAD

**Issue by nbouvrette** [vercel/next.js#40108]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 14.18.3
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.6
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

When upgrading to TypeScript 4.8.2 (from 4.7.4), I can no longer build my application that requires Next.js as a dependency:

```console
> next-multilingual@1.4.2 build
> rm -Rf ./lib && tsc

node_modules/next/dist/client/with-router.d.ts:8:121 - error TS2344: Type 'C' does not satisfy the constraint 'BaseContext'.

8 export default function withRouter<P extends WithRouterProps, C = NextPageContext>(ComposedComponent: NextComponentType<C, any, P>): 
React.ComponentType<ExcludeRouterProps<P>>;
                                                                                                                          ~

  node_modules/next/dist/client/with-router.d.ts:8:63
    8 export default function withRouter<P extends WithRouterProps, C = NextPageContext>(ComposedComponent: NextComponentType<C, any, P>): React.ComponentType<ExcludeRouterProps<P>>;
                                                                    ~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends BaseContext` constraint.


Found 1 error in node_modules/next/dist/client/with-router.d.ts:8
```

### Expected Behavior

The application should just build, as it is using TypeScript 4.7.4

### Link to reproduction

https://github.com/Avansai/next-multilingual

### To Reproduce

1) Clone `https://github.com/Avansai/next-multilingual`
2) run `npm run build` -> it works!
3) Upgrade TypeScript to 4.8.2
4) run `npm run build` -> it fails

**Comment by huozhi** [comment]
We upgraded the typings support for typescript 4.8.2 in the latest canary 12.2.6-canary.7 (publishing), can you try it later once it's on the npm?

**Comment by nbouvrette** [comment]
Sure, I only had access to `12.2.6-canary.6`

**Comment by SukkaW** [comment]
@nbouvrette `12.2.6-canary.7` has already been released and includes @huozhi's fix https://github.com/vercel/next.js/pull/39979.

**Comment by huozhi** [comment]
Verified the reproduction works with typescript 4.8.2 and `next@12.2.6-canary.7`

**Comment by nbouvrette** [comment]
Sorry, I just had a chance to check and I confirm that this is also working on `next@12.2.6-canary.9` - thanks

**Comment by huozhi** [comment]
Glad it works! Thanks for reporting
