### ISSUE TITLE
Failed to load external module styled-components after updating to version 16.1.0

### ISSUE THREAD

**Issue by Aluisio** [vercel/next.js#87686]
### Link to the code that reproduces this issue

https://github.com/Aluisio/test-styled-components

### To Reproduce

1. Build in the local development environment
2. Send the .next folder to the server
2. npm run start

Error: Failed to load external module styled-components-bd377d8093d58039: Error: Cannot find module 'styled-components-bd377d8093d58039'
Require stack:
- /home/ubuntu/front-end/.next/server/chunks/ssr/[root-of-the-server]__33cb3701._.js
- /home/ubuntu/front-end/.next/server/chunks/ssr/[turbopack]_runtime.js
- /home/ubuntu/front-end/.next/server/pages/_document.js
- /home/ubuntu/front-end/node_modules/next/dist/server/require.js
- /home/ubuntu/front-end/node_modules/next/dist/server/load-components.js
- /home/ubuntu/front-end/node_modules/next/dist/build/utils.js
- /home/ubuntu/front-end/node_modules/next/dist/build/swc/options.js
- /home/ubuntu/front-end/node_modules/next/dist/build/swc/index.js
- /home/ubuntu/front-end/node_modules/next/dist/build/next-config-ts/transpile-config.js
- /home/ubuntu/front-end/node_modules/next/dist/server/config.js
- /home/ubuntu/front-end/node_modules/next/dist/cli/next-test.js
- /home/ubuntu/front-end/node_modules/next/dist/bin/next
    at Context.externalRequire [as x] (.next/server/chunks/ssr/[turbopack]_runtime.js:535:15)
    at module evaluation (.next/server/chunks/ssr/[root-of-the-server]__33cb3701._.js:2:13032)
    at instantiateModule (.next/server/chunks/ssr/[turbopack]_runtime.js:740:9)
    at getOrInstantiateModuleFromParent (.next/server/chunks/ssr/[turbopack]_runtime.js:763:12)
    at Context.esmImport [as i] (.next/server/chunks/ssr/[turbopack]_runtime.js:228:20)
    at module evaluation (.next/server/chunks/ssr/[root-of-the-server]__1c13cba3._.js:7:2777)
    at instantiateModule (.next/server/chunks/ssr/[turbopack]_runtime.js:740:9)
    at instantiateRuntimeModule (.next/server/chunks/ssr/[turbopack]_runtime.js:768:12)
    at getOrInstantiateRuntimeModule (.next/server/chunks/ssr/[turbopack]_runtime.js:781:12)
    at Object.m (.next/server/chunks/ssr/[turbopack]_runtime.js:790:18)

When running the command `npm run dev`, another error is shown:
Error [TurbopackInternalError]: failed to create symlink to ../../../node_modules/styled-components

In my case, I can't run `npm run build` on the server, so I send the `.next` folder separately.
Up to version 16.0.10 this worked normally.

### Current vs. Expected behavior

In version 16.0.10 it works normally, but in version 16.1.0 or 16.1.1 (the latest version at the time of test) the error is appearing.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #17-Ubuntu SMP Mon Sep  2 13:48:07 UTC 2024
  Available memory (MB): 958
  Available CPU cores: 1
Binaries:
  Node: 24.11.1
  npm: 11.6.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 16.1.1
  eslint-config-next: N/A
  react: 19.2.3
  react-dom: 19.2.3
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next start (local)

### Additional context

After updating from version 16.0.10 (turbopack) to 16.1.0 or 16.1.1, after the build and start commands, when accessing the website the following error occurs: Error: Failed to load external module styled-components-bd377d8093d58039: Error: Cannot find module 'styled-components-bd377d8093d58039'.

This problem started in version 16.1.0.
My environment is Ubuntu on an AWS EC2 server, Turbopack, and PM2
Turbopack version: `d1bd5b58`

**Comment by icyJoseph** [comment]
What specs are there when you build this locally? If I understand correctly, you build locally and upload to the target server right?

**Comment by Aluisio** [comment]
Exactly. I compile locally and push to the .next folder on the server.

The build is created on a Mac Mini M2 with 8GB of RAM and macOS Tahoe 26.2.

`npx next info` return:
```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.2.0: Tue Nov 18 21:09:34 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T8112
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 24.11.1
  npm: 11.6.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 16.1.1 // Latest available version is detected (16.1.1).
  eslint-config-next: N/A
  react: 19.2.3
  react-dom: 19.2.3
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

The server details are in the "Provide environment information" section.

I've been doing this since Next.js 12 and it always worked perfectly, and only now after updating to version 16.1.0 has it stopped working.

**Comment by icyJoseph** [comment]
I am almost certain the issue has to be: https://nextjs.org/blog/next-16-1#improved-handling-of-serverexternalpackages - but I cannot prove it, just yet. It is also a bit dangerous to test canaries in this kind of setup, since there are some with known CVEs. 

We can try to at least narrow it down to Turbopack. Does it all work if you build and copy with Webpack?

**Comment by Aluisio** [comment]
I run the command `next build --webpack`, re-uploaded the .next folder, and it worked.
So the problem really is with Turbopack.

**Comment by icyJoseph** [comment]
Yes, it has to be that improve handling of server external packages, it is somehow making the build dependent on your system, or something else I am not fully grasping.

**Comment by Aluisio** [comment]
I discovered that if you build using TurboPack and, in addition to uploading the .next folder, also upload the node_modules folder, it works. However, in a normal environment, uploading the node_modules folder doesn't make sense.

**Comment by icyJoseph** [comment]
Right, I guess that's because styled-components is not being bundled - aka, kept as an external server package. Is this issue present in the submitted repo too? or only in your prod repository? Feels like this shouldn't happen if styled-components is in your package.json, but hard to tell for me, it is a strange issue.

**Comment by Aluisio** [comment]
The error also occurs in the repository I submitted. I created a sample repository because I can't make the production repository available.

**Comment by icyJoseph** [comment]
Right, I think we'll need to wait for a Turbopack maintainer here. How are you starting the server and all then? Does it help to just reinstall the modules on the EC2? Or I guess you do that.

**Comment by Aluisio** [comment]
Sorry, I didn't understand your question.

**Comment by sokra** [comment]
> I am almost certain the issue has to be: https://nextjs.org/blog/next-16-1#improved-handling-of-serverexternalpackages

You are right.

The build output contains symlinks now.

Did you try running the app locally? Our first guess would be that there is something wrong with the way the .next folder is copied over. Do you copy the symlinks too?

In the .next folder there should be a symlink at `.next/node_modules/styled-components-bd377d8093d58039` that links to the package. Check if that exists and it correctly pointing to the styled-conponents package in node_modules

**Comment by Aluisio** [comment]
The problem is really in the way the .next folder is copied to the server.

I always used the Cyberduck application to upload the .next folder, and after copying it again, I checked and the symbolic links were indeed not copied correctly. They were in the .next folder on the server, but not as symbolic links.

After that, I did a new test by compressing the .next folder with the command `tar --exclude='.DS_Store' --no-xattrs -czf build-next.tar.gz .next` and uploaded it again using Cyberduck, and on the server I decompressed it with the command `tar -xzf build-next.tar.gz`, and the symbolic links were maintained and the project started working again.

Now the test I mentioned where uploading the node_modules folder worked makes sense, because in that case, since the node_modules folder is very large, I had compressed the .next and node_modules folders and uploaded them to the server.
So it's actually not related to the node_modules folder, but rather because I had compressed the folders.

**Comment by arolariu** [comment]
I'm running into the same thing but my context is slightly different.

After switching to next@16.1, my multi-stage docker container builds or CI builds where I leverage any form of artifact caching, compression, or bundling techniques stop working - the next server always fails with some random package error like so:

>  Error: An error occurred while loading instrumentation hook: Failed to load external module @opentelemetry/semantic-conventions-cc6bc780becf1cf3: Error: Cannot find module '@opentelemetry/semantic-conventions-cc6bc780becf1cf3'

Or...

> Error: An error occurred while loading instrumentation hook: Failed to load external module require-in-the-middle-2ca7b9c2766f317e: Error: Cannot find module 'require-in-the-middle-2ca7b9c2766f317e'
Require stack:

See the following file system structure for a built multi-stage Docker container:

<img width="981" height="831" alt="Image" src="https://github.com/user-attachments/assets/bfc5453c-9c6b-4bd3-8622-4eebe5688d9f" />

The symlink links for the `@azure` or `@opentelemetry` packages are incorrect.
They point to paths that are not present / available in the docker container context.

For reference, I'm running multi-stage docker container building with pretty normal practices:
Stage A) - install npm packages
Stage B) copy npm packages from Stage A) and run `next build` (or equivalent)
Stage C) copy .next folder from Stage B) and run `next start` (or equivalent)

---

If I fallback to single stage, classic dockerfile - this works.
Same for CI - if I now stop any type of optimization for the node_modules between pipeline runs and revert to **always** installing the packages and having one step for install+build+run, it works...

---


If I fallback to next@16.0 and proceed with the multi-stage docker container build, we observe a difference in the final container file system structure:

<img width="573" height="1072" alt="Image" src="https://github.com/user-attachments/assets/d4275d59-6aab-4ed7-ac2d-47420d13e2b0" />


CC: @sokra, @icyJoseph.

---


Edit 1 -- after playing around, looks like I got the OTel and Azure Identity packages working again with:

> transpilePackages: ["import-in-the-middle", "require-in-the-middle"]

<img width="835" height="268" alt="Image" src="https://github.com/user-attachments/assets/b03638bc-1965-4830-90f1-8127a57875db" />

But it's very hard to understand why this works... I'd like some help or explanation...

Here's how the docker container file system structure looks now, after the `transpilePackages` field set:

<img width="676" height="710" alt="Image" src="https://github.com/user-attachments/assets/5ae41e7d-89d1-40db-8171-c03cec71bad2" />

**Comment by taletski** [comment]
@arolariu, using `transpilePackages: ["import-in-the-middle", "require-in-the-middle"]` makes Turbopack bundle these libraries into `.next` instead of symlinking them. By default, they aren’t bundled since v16.1 (see [`serverExternalPackages` list](https://nextjs.org/docs/app/api-reference/config/next-config-js/serverExternalPackages)).

As far as I get it, since 16.1 external packages are not bundled along with their downstream deps (your first screenshot). When you select to transpile and thus bundle `require-in-the-middle` you also cause all downstream dependencies, like `@opentelemetry/instrumentation` and then `@opentelemetry/*` and then `@azure/*` to be bundled too (your third screenshot). Bundling avoids broken symlinks for all of them, that's how your workaround works. 

I'd check in your multi-stage Docker container why missing package(s) are not in the symlinked dirs. My bet is that you are copying cached `node_modules` in the `{whatever}/app/node_modules` dir while symlinks expect them in `{whatever}/node_modules`. I guess prettier symlink still works because you might have another `{whatever}/node_modules/prettier` as you might run install on the top level and `prettier` is required by the top level `package.json`. Would need more info to confirm though.

**Comment by iffa** [comment]
Seeing this error as well, using just a simple multi-stage Docker build setup. I added import-in-the-middle and require-in-the-middle but am seeing similar errors for other packages as well. Am I expected to just keep adding packages to the list in hopes of the issue getting fixed? We're using Pages router (App router only for a sitemap / robots)

**Comment by taletski** [comment]
@iffa you could try to transpile [all default external packages](https://github.com/vercel/next.js/blob/54c1075027a549638be3ef53a06018975db3291c/packages/next/src/lib/server-external-packages.jsonc#L1). I'd *only* try that to debug.

The real fix is understanding why `node_modules` symlinks are broken in your multi-stage build. Some of your deps are no longer bundled but resolved via symlinks at runtime, so any mismatch in how deps are installed between build and
runtime stages will surface now.

Please check that packages symlinked from `.next/node_modules` are installed in the same path in both stages.

**Comment by arolariu** [comment]
@taletski, some people are running a monorepository style codebase where you have multiple node projects, besides the nextjs one.

In my multi stage docker container build (see here: [Dockerfile](https://github.com/arolariu/arolariu.ro/blob/main/sites/arolariu.ro/Dockerfile)) I'm doing the npm run install stage, then the npm run build stage and then the last stage just copies the .next folder and runs npm run start... that should work out of the box when you have opentelemetry or azure or X packages installed - you as a developer shouldn't now worry about "glue code" to make the nextjs framework work with X packages.... at least that's my assumption...

I don't know about prettier package tbh, I find that weird too, prettier is not declared as a dependency or dev dependency in the nextjs package.json (see here: [package.json](https://github.com/arolariu/arolariu.ro/blob/main/sites/arolariu.ro/package.json)) manifest... 😳

**Comment by taletski** [comment]
@arolariu I am not sure how it is related to a monorepo setup. 

I agree that the default `serverExternalPackages` list moves Next away from its original “frontend-first, everything bundled” convention and is a breaking change. With the Turbopack improvements in 16.1, this shift has just become more visible.

At the same time, Next has been leaning backend-first with the App Router and Server Components.
My observation is that with Next 16+, the mental model feels closer to Node.js development (CJS, `require()`, runtime dependencies) than to a frontend-first setup where everything is bundled.

In that context, adapting CI pipelines on your end makes sense: copying `node_modules` across multi-stage Docker builds is a fairly standard Node.js practice, and not really about glue code.

**Comment by mischnic** [comment]
> 1. Build in the local development environment
> 2. Send the .next folder to the server
> 3. npm run start

> I discovered that if you build using TurboPack and, in addition to uploading the .next folder, also upload the node_modules folder, it works. However, in a normal environment, uploading the node_modules folder doesn't make sense.


You all should be using `output: "standalone"`: https://nextjs.org/docs/pages/api-reference/config/next-config-js/output

Without that, just copying the `.next` folder (and having no `node_modules` at runtimes) by itself was never supported (and I'm surprised that it worked at all for you).

If you use `output: "standalone"`, then Next.js figures out which parts of `node_modules` are actually needed at runtime and will only copy those to `.next/standalone`.

----

@taletski

> As far as I get it, since 16.1 external packages are not bundled along with their downstream deps (your first screenshot).

That part hasn't changed with 16.0 (or 16.1). Before 16.1, Turbopack wrote `require("styled-components")` into `.next/server/chunks/...` and expected that it would be available at runtime in the server. Or, if it's not resolvable by itself (because it's a transitive dependency, it woudl straight up ignore `serverExternalPackages`, but most of these dependencies really need to stay unbundled, because their code is too dynamic to be handled by a bundler).

Now, it generates these symlinks which solves a bunch of problems, see https://github.com/vercel/next.js/pull/86375 for more details.

> I agree that the default serverExternalPackages list moves Next away from its original “frontend-first, everything bundled” convention and is a breaking change. With the Turbopack improvements in 16.1, this shift has just become more visible.

I think that for almost all users (also when using `output: standalone`), this 16.1 has actually made it less visible. Previously, there would be obscure build time warnings about some transitive dependency not being resolvable. In a monorepo, this becomes even hard to workaround (manually adding transitive dependencies to package.json) or straight up impossible (having to specify the same dependency in two versions).

**Comment by bertrand-riviere** [comment]
Hello,

I think the fact Turbopack uses symlinks for serverExternalPackages for standalone output since v16.1.x should be considered as a breaking change.
I mean, for many usecases, build on CI => copy to server, multi-stage Docker builds, etc… users expect to be able to use basic file copy which does not preserve symlinks.

The workaround I have found is to **zip** the output folder before copy using the **-y** flag (**which preserve symlinks**).
Considering the number of issues that are related to this change, I do not seem to be the only one that have been confused:
-	https://github.com/vercel/next.js/issues/88844
-	https://github.com/vercel/next.js/issues/89851
-	https://github.com/vercel/next.js/issues/88885
-	…

I think the following docs should be updated to mention this change and suggest ways to workaround it for common scenario:
-	https://nextjs.org/docs/app/api-reference/config/next-config-js/serverExternalPackages 
-	https://nextjs.org/docs/app/api-reference/config/next-config-js/output (at least this is where I have started to try to find answers after my app stopped working).

Maybe the v16.1.0 release note should also be updated to mention this “breaking change”.

Hopefully this would avoid other users to waste time trying to understand why their deployment worklow no longer works after upgrading.

**Comment by marcoshernanz** [comment]
Thanks for the report. I confirmed this is the same Turbopack hashed external-module alias issue tracked in #87737. The build records an alias tied to one `node_modules` layout, then the runtime artifact cannot resolve it in another layout. Closing as a duplicate so the deployment investigation stays consolidated.
