### ISSUE TITLE
Turbopack standalone build in 16.1.x omits serverExternalPackages from .next/standalone/node_modules

### ISSUE THREAD

**Issue by MTroian94** [vercel/next.js#88844]
### Link to the code that reproduces this issue

https://github.com/MTroian94/next-16.1.4

### To Reproduce

1. Create a new Next.js app using Next.js 16.1.x with Turbopack enabled.
2. Install a dependency that will be externalized, for example: `pnpm add ts-deepmerge`
3. Configure `next.config.ts` with `output: "standalone"` and `serverExternalPackages`:
```ts
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "standalone",
  serverExternalPackages: ["ts-deepmerge"],
};

export default nextConfig;
```
4. Import and use ts-deepmerge in any server-side file (e.g. `page.tsx`)
5. Run the build using Turobopack
```bash
next build
```
6. Inspect the generated standalone output:
```bash
ls .next/standalone/node_modules
```
**Observed result**
- `ts-deepmerge` is not present in `.next/standalone/node_modules`.

### Current vs. Expected behavior

**Current behavior (Next.js 16.1.x + Turbopack)**
When building a project with:
- output: "standalone"
- serverExternalPackages configured
- default Turbopack build (next build)

dependencies listed in `serverExternalPackages` (e.g. `ts-deepmerge`) are not included in `.next/standalone/node_modules`. 
As a consequence:
- the standalone output is incomplete
- runtime execution fails with a missing module error, for example:
```
Error: Cannot find module 'ts-deepmerge'
```
- Docker images that rely exclusively on `.next/standalone` (e.g. distroless images without `node_modules` installation) cannot start.

**Expected behavior**
Dependencies specified in `serverExternalPackages` should be:
- resolved at runtime via `.next/standalone/node_modules`
- included in the standalone output, as they were in Next.js ≤ 16.0.x
- consistently included regardless of whether the build uses Webpack or Turbopack
This is the current behavior when running:
```bash
next build --webpack
```
which produces a correct standalone output including `ts-deepmerge`.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.2.0: Tue Nov 18 21:09:34 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T8112
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 22.22.0
  npm: 10.9.4
  Yarn: 1.22.22
  pnpm: 10.28.0
Relevant Packages:
  next: 16.1.4 // Latest available version is detected (16.1.4).
  eslint-config-next: N/A
  react: 19.2.3
  react-dom: 19.2.3
  typescript: 5.9.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Runtime, Turbopack

### Which stage(s) are affected? (Select all that apply)

next start (local), Other (Deployed)

### Additional context

**Behavior up to Next.js 16.0.x**
Up to `Next.js 16.0.x`, after running next build, the generated `.next/standalone `folder had the following structure:
```
.next/
└─ standalone/
   ├─ .next
   ├─ server.js
   ├─ package.json
   ├─ node_modules/
   │  └─.pnpm
   │  └─next
   │  └─react
   │  └─react-dom
   │  └─ts-deepmerge
   │  └─typescript
```
As expected, `ts-deepmerge` was correctly included in `.next/standalone/node_modules`.

**Behavior up to Next.js 16.0.x**
After upgrading to **Next.js 16.1.x**, `ts-deepmerge` is no longer present in .`next/standalone/node_modules` when building with **Turbopack**.

**Workaround**
If I run the build using Webpack instead:
```
next build --webpack
```
The generated .next folder has ts-deepmerge inside `.next/standalone/node_modules` folder. 

**Impact on Docker standalone builds**
This behavior causes a concrete issue when using a Docker setup based on `output: "standalone"`. 
My Dockerfile follows the recommended multi-stage approach, where the runtime image only copies the contents of .next/standalone and .next/static, without installing node_modules again:

```dockerfile
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
```
With **Next.js 16.1.x + Turbopack**, since `ts-deepmerge` is no longer included in .`next/standalone/node_modules`, the runtime container fails at startup with a missing dependency error.

Because the final image is based on a **distroless Node.js** image and does not run `pnpm install` (by design), there is no way for the missing dependency to be resolved at runtime.

Using `next build --webpack` restores the previous behavior and produces a correct standalone output, which suggests a regression or behavior change specific to Turbopack in 16.1.x.

I have found a similar issue about this https://github.com/vercel/next.js/issues/87686

**Comment by Luk-z** [comment]
@icyJoseph some news? we wanna release next16 in our production app but we are blocked by this issue. Thanks

**Comment by codeagencybe** [comment]
any update on this? We are also blocked by this problem

_Edit by maintainer bot: Comment was **automatically** minimized because it was considered unhelpful. (If you think this was by mistake, let us know). Please only comment if it adds context to the issue. If you want to express that you have the same problem, use the upvote 👍 on the issue description or subscribe to the issue for updates. Thanks!_

**Comment by jonas-is-coding** [comment]
`serverExternalPackages` with `output: "standalone"` should produce a runnable standalone artifact. If Turbopack omits those packages from `.next/standalone/node_modules`, that is a regression relative to expected standalone behavior. For production, the safest path is `next build --webpack` until Turbopack standalone packaging reaches parity, and CI should validate boot from only `.next/standalone` plus static assets.

**Comment by jketcham** [comment]
Just ran into this while trying to setup Next 16.1 with Sentry.

**Comment by Luk-z** [comment]
We solve using `node-linker=hoisted` (pnpm) when building standalone in docker.
In local development we still use the default `node-linker` (isolated).
Anyway I also think it is a regression but it seems that is's not relevant for next.js team.

**Comment by mischnic** [comment]
> Observed result
> ts-deepmerge is not present in .next/standalone/node_modules.

This in itself is not a problem:
```
.next/standalone/.next/node_modules/ts-deepmerge-1926c4f5c6929741
```
is a symlink which points to
```
.next/standalone/node_modules/.pnpm/ts-deepmerge@7.0.3/node_modules/ts-deepmerge
```



----


Your reproduction https://github.com/MTroian94/next-16.1.4
works fine with this Dockerfile (from https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile)
```Dockerfile
FROM node:24.13.0-slim AS builder

WORKDIR /app
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN --mount=type=cache,target=/root/.local/share/pnpm/store corepack enable pnpm && pnpm install --frozen-lockfile

# Copy application source code
COPY . .
ENV NODE_ENV=production
RUN pnpm build

# ============================================

FROM node:24.13.0-slim AS runner

# Set working directory
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY --from=builder --chown=node:node /app/public ./public

COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static

USER node
EXPOSE 3000
CMD ["node", "server.js"]
```

Can you share how you reproduce that `Cannot find module 'ts-deepmerge'` error?

**Comment by Luk-z** [comment]
@mischnic as written in the first message the bug is that running `next build` server External Packages are not present in `.next/standalone/node_modules`. This is a problem and a regression because with 16.0.x this don't happens.

Do you agree? Or maybe is this an expected behavior (breaking change) ?

Please don't hack with a custom Dockerfile. As i written in the previous message there are some trick to make this work. But this is not the purpose of this issue. Keep the focus on `next build` please.

**Comment by AndrewBoklashko** [comment]
Would like to share my experience on a similar Turbopack build problem.

In my application the problem was because Turbopack outputs `node_modules` into `.next/standalone/.next/node_modules`:

<img width="1384" height="519" alt="Image" src="https://github.com/user-attachments/assets/6fff3ac6-586b-4ba7-b442-81e2e3ebbaca" />

While if I build with `--webpack` flag, it outputs `node_modules` into `.next/standalone/node_modules`:

<img width="1336" height="501" alt="Image" src="https://github.com/user-attachments/assets/5c281bd5-4525-4403-89a9-1d67f9c63585" />

Docker image(runner stage):
```
...

FROM node AS runner

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/apps/my-next-app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/my-next-app/.next/static ./apps/my-next-app/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/my-next-app/public ./apps/my-next-app/public

WORKDIR /app/apps/my-next-app

USER nextjs

ENV NODE_OPTIONS="--max-old-space-size=4096 --require dd-trace/init"
ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "server.js"]
```

As you can see, I am using `--require dd-trace/init` early import which expectedly is not resolvable if `dd-trace` is located in `.next/standalone/.next/node_modules` since it gets imported outside of Next server context.

My workaround is to use pnpm `publicHoistPattern` to get `dd-trace` into root `node_modules` folder:
```
// pnpm-workspace.yaml
...
publicHoistPattern:
  - '*dd-trace*'
...
```
Which results in the following Turbopack build output:

<img width="1383" height="447" alt="Image" src="https://github.com/user-attachments/assets/055f25b9-e740-4393-9d57-1fd6e3ac1dd3" />

With this output, `dd-trace` is correctly resolvable at runtime.

Kind of unexpected Turbopack breaking change but at least there is a workaround.

---
NodeJS: 22
pnpm: 10.23
NextJS: 16.2.1

**Comment by GeorgeIpsum** [comment]
> Would like to share my experience on a similar Turbopack build problem.
> 
> In my application the problem was because Turbopack outputs `node_modules` into `.next/standalone/.next/node_modules`:
> 
> <img alt="Image" width="1384" height="519" src="https://private-user-images.githubusercontent.com/15115317/573900998-6fff3ac6-586b-4ba7-b442-81e2e3ebbaca.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY5MDgwNzAsIm5iZiI6MTc3NjkwNzc3MCwicGF0aCI6Ii8xNTExNTMxNy81NzM5MDA5OTgtNmZmZjNhYzYtNTg2Yi00YmE3LWI0NDItODFlMmUzZWJiYWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDIzVDAxMjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYTc0ODZkOWExNjc3Y2UzYmQ3NDY1NDMzYThkYTU4Nzc4YTYxNjdmMjRlNjIxMGQyM2Y4NzYwMmI2OGViZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.3jRMfxBSHna57OCFzgQg69yjuPICH3mCMYmlkUjrpTw">
> While if I build with `--webpack` flag, it outputs `node_modules` into `.next/standalone/node_modules`:
> 
> <img alt="Image" width="1336" height="501" src="https://private-user-images.githubusercontent.com/15115317/573901105-5c281bd5-4525-4403-89a9-1d67f9c63585.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY5MDgwNzAsIm5iZiI6MTc3NjkwNzc3MCwicGF0aCI6Ii8xNTExNTMxNy81NzM5MDExMDUtNWMyODFiZDUtNDUyNS00NDAzLTg5YTktMWQ2N2Y5YzYzNTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDIzVDAxMjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OTRkNjk0OWU1ODBlYmQ2ZWUyN2UwOWNiNTg4NWYxMGU4NDliNTFlYmY4ODNiODA0NDRiMDcyMzU3NjlhMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.SiK0cHAgvW7jUvmy_ZdBppYSNTb2gNQAYkXfVxez7BU">
> Docker image(runner stage):
> 
> ```
> ...
> 
> FROM node AS runner
> 
> RUN addgroup --system --gid 1001 nodejs && \
>     adduser --system --uid 1001 nextjs
> 
> COPY --from=builder --chown=nextjs:nodejs /app/apps/my-next-app/.next/standalone ./
> COPY --from=builder --chown=nextjs:nodejs /app/apps/my-next-app/.next/static ./apps/my-next-app/.next/static
> COPY --from=builder --chown=nextjs:nodejs /app/apps/my-next-app/public ./apps/my-next-app/public
> 
> WORKDIR /app/apps/my-next-app
> 
> USER nextjs
> 
> ENV NODE_OPTIONS="--max-old-space-size=4096 --require dd-trace/init"
> ENV NODE_ENV=production
> 
> EXPOSE 3000
> 
> CMD ["node", "server.js"]
> ```
> 
> As you can see, I am using `--require dd-trace/init` early import which expectedly is not resolvable if `dd-trace` is located in `.next/standalone/.next/node_modules` since it gets imported outside of Next server context.
> 
> My workaround is to use pnpm `publicHoistPattern` to get `dd-trace` into root `node_modules` folder:
> 
> ```
> // pnpm-workspace.yaml
> ...
> publicHoistPattern:
>   - '*dd-trace*'
> ...
> ```
> 
> Which results in the following Turbopack build output:
> 
> <img alt="Image" width="1383" height="447" src="https://private-user-images.githubusercontent.com/15115317/573901506-055f25b9-e740-4393-9d57-1fd6e3ac1dd3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY5MDgwNzAsIm5iZiI6MTc3NjkwNzc3MCwicGF0aCI6Ii8xNTExNTMxNy81NzM5MDE1MDYtMDU1ZjI1YjktZTc0MC00MzkzLTlkNTctMWZkNmUzYWMxZGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDIzVDAxMjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YzYyMDZhYTE3YTZkMzYxNmI4Y2U5NDhlZjU3OTc4YjJmZGQyY2M5MmU0MDc3Y2ZhODQ5ZjM3YzgwOTI2MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.FNkJZdEMKvPjdOKej8LhmzIRrpvyPK3JbPQBkv23504">
> With this output, `dd-trace` is correctly resolvable at runtime.
> 
> Kind of unexpected Turbopack breaking change but at least there is a workaround.
> 
> NodeJS: 22 pnpm: 10.23 NextJS: 16.2.1

This really saved me, thank you so much. One note to add here: I also had to do an actual import of `dd-trace/init` somewhere in my code otherwise the turbopack build wouldn't actually place the `init.js` in `node_modules/dd-trace`:

```ts
// instrumentation.dd-trace.ts which I import for node env in `instrumentation.ts`
// without this nft will NOT also include `dd-trace/init.js` in outputs
import "dd-trace/init";
import ddTrace from "dd-trace";

ddTrace.use("http", {
  server: { blocklist: ["/api/health"] },
});
```

**Comment by 6TELOIV** [comment]
I can confirm that `next build --webpack` works as a workaround for me.

Looking into the error and the output, (one of) my problem packages is `pino`. With turbopack, I get the error `Error: Cannot find module 'pino-dc25f7231e266390'`. Looking at the output, pino ***is in fact*** inside `.next/standalone/.next/node_modules/pino`. However, the module with the hash added is only persent in `.next/node_modules/pino-dc25f7231e266390` as a symbolic link pointing to the project's `node_modules` install location.

This, of course, is not copied to the container, and so at runtime it tries to resolve `pino-dc25f7231e266390` and crashes.

**Comment by timothyclin** [comment]
I ran into the same issue and found "next build --webpack" is a workaround as well.

**Comment by armandabric** [comment]
I got the same issue while migrating to turbopack. 

I build a script that fix the generated symlinks: https://gist.github.com/armandabric/85f7d0cd2f9370adc6222da43951fa47

**Comment by marcoshernanz** [comment]
Thanks for the report. I confirmed this is the same Next.js 16.1 Turbopack standalone external package failure tracked in #87686. Both cases generate a hashed external alias without copying the required package into the standalone artifact. Closing as a duplicate so the deployment investigation stays consolidated.
