### ISSUE TITLE
Cannot find babel-react-compiler when using Bun

### ISSUE THREAD

**Issue by Jayllyz** [vercel/next.js#85234]
### Link to the code that reproduces this issue

https://github.com/Jayllyz/next-bun-react-compiler

Resolved in Bun 1.3.2 : https://github.com/oven-sh/bun/releases/tag/bun-v1.3.2

### To Reproduce

It fails with Turbopack :
```sh
git clone https://github.com/Jayllyz/next-bun-react-compiler
bun install
bun run build

$ next build
   ▲ Next.js 16.0.1 (Turbopack)
   - Experiments (use with caution):
     · serverActions
     ✓ turbopackFileSystemCacheForDev

   Creating an optimized production build ...

> Build error occurred
Error: Turbopack build failed with 1 errors:
./src/app/page.tsx
Error evaluating Node.js code
ResolveMessage: Cannot find module './node_modules/.bun/babel-plugin-react-compiler@1.0.0/node_modules/babel-plugin-react-compiler' from '/Users/jayllyz/code/my-app/node_modules/.bun/next@16.0.0+f98dd74b6b4c2783/node_modules/next/dist/compiled/babel/bundle.js'

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.


Import traces:
  Client Component Browser:
    ./src/app/page.tsx [Client Component Browser]
    ./src/app/page.tsx [Server Component]

  Client Component SSR:
    ./src/app/page.tsx [Client Component SSR]
    ./src/app/page.tsx [Server Component]


    at <unknown> (file. It's possible that the missing plugin is loaded by a preset)
    at processTicksAndRejections (null)
error: script "build" exited with code 1
```

It works with Webpack :
```
bun run build:webpack
$ next build --webpack
   ▲ Next.js 16.0.1 (webpack)

   Creating an optimized production build ...
 ✓ Compiled successfully in 3.6s
 ✓ Finished TypeScript in 984.7ms
 ✓ Collecting page data in 227.0ms
 ✓ Generating static pages (4/4) in 15.8s
 ✓ Collecting build traces in 5.7s
 ✓ Finalizing page optimization in 5.9s

Route (app)
┌ ○ /
└ ○ /_not-found


○  (Static)  prerendered as static content
```

### Current vs. Expected behavior

Should use react compiler correctly.

### Provide environment information

```bash
perating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.0.0: Wed Sep 17 21:41:50 PDT 2025; root:xnu-12377.1.9~141/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
Binaries:
  Node: 24.10.0
  npm: 11.6.2
  Yarn: 1.22.21
  pnpm: 10.19.0
  bun: 1.3.1
Relevant Packages:
  next: 16.0.1 // Latest available version is detected (16.0.1).
  eslint-config-next: N/A
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by yusing** [comment]
Same here, next 16 + react 19.2, `turbopackFileSystemCacheForDev` enabled

**Comment by darphiz** [comment]
same issue


_Edit by maintainer bot: Comment was **automatically** minimized because it was considered unhelpful. (If you think this was by mistake, let us know). Please only comment if it adds context to the issue. If you want to express that you have the same problem, use the upvote 👍 on the issue description or subscribe to the issue for updates. Thanks!_

**Comment by icyJoseph** [comment]
Is this a bun issue though? https://github.com/oven-sh/bun/issues/23554 is there some incompatibility with bun runtime?

**Comment by undead-reaper** [comment]
You can use `bun run dev` without the --bun flag as a workaround till this is fixed

**Comment by amirqasemi74** [comment]
I have the same issue when building nextjs 16 with bun in docker file
```

FROM oven/bun:1.3 AS builder

WORKDIR /website

COPY package.json bun.lock ./

RUN bun install

COPY . .

RUN bun run build

```

output:
```
#11 8.586 Error evaluating Node.js code
#11 8.586 ResolveMessage: Cannot find module './node_modules/babel-plugin-react-compiler' from '/website/node_modules/next/dist/compiled/babel/bundle.js'
#11 8.586 
#11 8.586 Make sure that all the Babel plugins and presets you are using
#11 8.586 are defined as dependencies or devDependencies in your package.json
#11 8.586 file. It's possible that the missing plugin is loaded by a preset
#11 8.586 you are using that forgot to add the plugin to its dependencies: you
#11 8.586 can workaround this problem by explicitly adding the missing package
#11 8.586 to your top-level package.json.
```

**Comment by shadow173** [comment]
I hit this same issue building with Docker + Bun. Switching to npm in the Dockerfile fixed it.

**Comment by cunc** [comment]
> Is this a bun issue though? [oven-sh/bun#23554](https://github.com/oven-sh/bun/issues/23554) is there some incompatibility with bun runtime?

Using bun 1.3.1 and next 15.5.6 with `experimental: { reactCompiler: true }` works fine, hope this will help

**Comment by M4h45amu7x** [comment]
same

_Edit by maintainer bot: Comment was **automatically** minimized because it was considered unhelpful. (If you think this was by mistake, let us know). Please only comment if it adds context to the issue. If you want to express that you have the same problem, use the upvote 👍 on the issue description or subscribe to the issue for updates. Thanks!_

**Comment by FarKiD** [comment]
I had the same error, it was fixed after I installed Node.js, turns out I was only relying on Bun and never installed Node.js, and Next.js seems to be relying on it internally.

**Comment by thealbertyang** [comment]
I ran into this exact issue using Bun 1.3.1, Next.js 16.0.1, with `reactCompiler: true` in my `next.config.ts`. 

> Error evaluating Node.js code
ResolveMessage: Cannot find module '../../node_modules/.bun/babel-plugin-react-compiler@1.0.0/node_modules/babel-plugin-react-compiler' from 
'./node_modules/.bun/next@16.0.1+1f27bae1e6a4cc9d/node_modules/next/dist/compiled/babel/bundle.js' 
Did you mean "@babel/../../node_modules/.bun/babel-plugin-react-compiler@1.0.0/node_modules/babel-plugin-react-compiler"?

I used [publicHoistPattern](https://bun.com/blog/bun-v1.3.1#publichoistpattern-and-hoistpattern) to fix it. 

Add this to your `bunfig.toml` at the project root:

```
[install]
linker = "isolated"
publicHoistPattern = ["babel-plugin-react-compiler"]
```

Then just run `bun install` and `bun --bun run next dev` and your Next.js app should now start without errors:

```
// next.config.ts
const nextConfig = {
  reactCompiler: true, // ✅ Works now!
}
```

The issue is that Bun's isolated mode puts packages in a .bun directory that Next.js Turbopack can't find. `publicHoistPattern` tells Bun to hoist just the React Compiler plugin to the regular node_modules where Next.js expects it. 

Hope this helps!

**Comment by dmythro** [comment]
I'm having the same error both within monorepo and a separate Next 16 app repos when try to check React Compiler: `Cannot find module './node_modules/babel-plugin-react-compiler'` even though it was installed in dev dependencies.

As I've read in the thread (@cunc, not sure why his comment was downvoted if true), it was working with Next 15.5.6 with `experimental: { reactCompiler: true }`, so it is kinda Next 16 regression then or what?

Would really appreciate some input on this as primarily have Bun projects now.

**Comment by RiskyMH** [comment]
This issue should be fixed now in Bun from https://github.com/oven-sh/bun/pull/24325! Please upgrade to bun canary in ~30mins and let me know if its all good now!
```zig
$ bun upgrade --canary
```

For context the issue is only from using turbopack build which nextjs v16 enabled by default.

**Comment by Jayllyz** [comment]
Thanks a lot, I can confirm that its working now.
```
next-bun-react-compiler on  main via 🥟 v1.3.2 on ☁️   took 25s
❯ bun upgrade --canary
[2.28s] Upgraded.

Welcome to Bun's latest canary build!

Report any bugs:

    https://github.com/oven-sh/bun/issues

Changelog:

    https://github.com/oven-sh/bun/compare/797847639...528620e9a


next-bun-react-compiler on  main via 🥟 v1.3.2 on ☁️   took 2s
❯ bun --bun run build
$ next build
 ⚠ Warning: Next.js inferred your workspace root, but it may not be correct.
 We detected multiple lockfiles and selected the directory of /Users/jayllyz/package-lock.json as the root directory.
 To silence this warning, set `turbopack.root` in your Next.js config, or consider removing one of the lockfiles if it's not needed.
   See https://nextjs.org/docs/app/api-reference/config/next-config-js/turbopack#root-directory for more information.
 Detected additional lockfiles:
   * /Users/jayllyz/code/next-bun-react-compiler/bun.lock

   ▲ Next.js 16.0.1 (Turbopack)
   - Experiments (use with caution):
     ✓ turbopackFileSystemCacheForDev

   Creating an optimized production build ...
 ✓ Compiled successfully in 2.7s
 ✓ Finished TypeScript in 1040.2ms
 ✓ Collecting page data in 188.7ms
 ✓ Generating static pages (4/4) in 256.6ms
 ✓ Finalizing page optimization in 184.7ms

Route (app)
┌ ○ /
└ ○ /_not-found


○  (Static)  prerendered as static content
```

**Comment by ziyak97** [comment]
Maybe slightly unrelated, but any idea when we can run this on Vercel? 

https://vercel.com/docs/functions/runtimes/bun

The doc mentions 

{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "bunVersion": "1.x"
}

i assume we cannot set this - "1.x" and are reliant on what is allowed by Vercel?

**Comment by followbl** [comment]
@ziyak97 went through this with support yesterday, you have to set the install script in the root of your app with that vercel.json and manually install the proper bun version...

```json
{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "bunVersion": "1.3.1",
  "buildCommand": "env CI=true npx bun@1.3.1 run --bun next build",
  "installCommand": "npx bun@1.3.1 install"
}
```

obviously make sure you put in your proper bun version

also, if you set this in your vercel settings with a custom install command, it won't work, fyi

**Comment by RiskyMH** [comment]
Vercel manages the minor and patch version. Only valid option is `1.x`

**Comment by izakfilmalter** [comment]
Setting my `vercel.json` to the following get the build working:
```json
{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "bunVersion": "1.3.2",
  "buildCommand": "env CI=true npx bun@canary run --bun next build",
  "installCommand": "npx bun@canary install"
}
```
I'm now running into the following:
```sh
Collecting page data  .Error: Failed to load chunk server/chunks/ssr/_e361dbd6._.js from runtime for chunk server/app/(auth)/sign-out/page.js
    at loadRuntimeChunkPath (.next/server/chunks/ssr/[turbopack]_runtime.js:636:19)
    at loadRuntimeChunk (.next/server/chunks/ssr/[turbopack]_runtime.js:605:9)
    at c (.next/server/chunks/ssr/[turbopack]_runtime.js:766:25)
    at <anonymous> (.next/server/app/(auth)/sign-out/page.js:25:3)
    at anonymous (null)
    at processTicksAndRejections (null)
    at processTicksAndRejections (null) {
  [cause]: ResolveMessage {}
}
```

**Comment by followbl** [comment]
@izakfilmalter this I believe is a `cacheComponents` issue - I have not got it down to a pared down reproducible case, but I'm 99% sure that's the issue

**Comment by xmlking** [comment]
I can overcome this issue by setting `reactCompiler: false`

**Comment by RiskyMH** [comment]
@xmlking can you try canary bun as i should have fixed this issue! Bun 1.3.2 will release pretty soon though.

```zig
bun upgrade --canary
```

Edit: its released now

**Comment by ziyak97** [comment]
While I’ll wait for Bun to resolve all issues before migrating, I think Vercel should also provide more visibility into which versions they support and which are set as default. For example, my app will break on anything below 1.3.2 (which isn’t even out yet). Shouldn’t there be a page on Vercel that shows this information so we know when it’s safe to make the switch?

@rauchg

**Comment by iagomls** [comment]
Bun `v1.3.2` got released, so no `--canary` flag is required anymore.

**Comment by xmlking** [comment]
Works with bun v1.3.2

**Comment by ziyak97** [comment]
Sadly this does not work for me

I have

cacheComponents: true

When i remove -> cacheComponents: true

It works. 

Failing during build, dev works fine @RiskyMH is this a known issue that is already open, or should I open one?

**Comment by RiskyMH** [comment]
That is a seperate issue - does it work in node though as if so we (bun) need to fix

**Comment by ziyak97** [comment]
@RiskyMH yes it works on node. If this is not open yet i can do so on Bun and try to create a codebase to reproduce this if that helps. Currently on the latest canary of bun -> v1.3.3
