### ISSUE TITLE
Error Prerendering Not-Found page

### ISSUE THREAD

**Issue by Kamasah-Dickson** [vercel/next.js#60296]
### Link to the code that reproduces this issue

https://crispy-space-engine-947xg5j9pwwh995w.github.dev/

### To Reproduce

npm run build

### Current vs. Expected behavior

the error is about pre-rendring of the not-found page. the not-found page is at app/not-found but I dont know why am getting the errors

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro   
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

### Additional context

running build in my ide on version 13.5.6 caught the error, I updated to next 14.0.4 and not errors were caught while building but when I pushed to Vercel,  compilation failed due to pre-rendering of the not-found page.

![image](https://github.com/vercel/next.js/assets/86136379/eef2f6eb-9ca3-4d7b-b066-a2a9bf1cf692)
