### ISSUE TITLE
next/dynamic causing Runtime Exception for Suspense boundary starting with 13.0.7

### ISSUE THREAD

**Issue by idmedia-kaiser** [vercel/next.js#45488]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.1.7-canary.1
      eslint-config-next: 13.1.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/wonderful-haze-bo0ujx

### To Reproduce

Open index page in the codesandbox and reload the page
![image](https://user-images.githubusercontent.com/5065920/216105675-3cb98941-586f-4cfc-918c-d4d213906e69.png)

This is a simplification of the bug we are facing if we update to latest version
Basically when a state update happens and the useSelector updates a component with a dynamic component inside, it throws an unexpected runtime error

### Describe the Bug

After updating to 13.0.7-canary.3 or above an unhandled React runtime error is thrown in develop mode

`Unhandled Runtime Error
Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.`

After some digging I guess its related to this PR
[Implement loadable with lazy and suspense for next dynamic](https://github.com/vercel/next.js/pull/42589)  https://github.com/vercel/next.js/pull/42589

### Expected Behavior

There should be no runtime error

### Which browser are you using? (if relevant)

Chome 109.0.5414.120

**Comment by idmedia-kaiser** [comment]
@huozhi Guess this is related to https://github.com/vercel/next.js/pull/42589

**Comment by SukkaW** [comment]
IMHo this is a duplicate of https://github.com/vercel/next.js/issues/44083

Try upgrading to React 18.3.0 (`npm i react@next react-dom@next`) and then the issue should be gone.

If you encounter the `wakeable.then is not a function` error after upgrading to React 18.3.0, please refer to https://github.com/facebook/react/issues/25994 and apply a workaround I created here: https://github.com/facebook/react/issues/25994#issuecomment-1402287594

**Comment by huozhi** [comment]
Close as duplicated, will track it in #44083
