### ISSUE TITLE
Next js 13.5.4 - npm run build throw "TypeError: en.hasOwnProperty is not a function" for all my pages

### ISSUE THREAD

**Issue by Nico924** [vercel/next.js#56367]
### To Reproduce

"npm run build" with 13.5.4 will yield "TypeError: en.hasOwnProperty" for all my pages.
the same code works fine in 13.4.12.
Following the stacktrace, the error is located : in /.next/server/chunks/3930.js:1:77335

"npm run dev" is working perfectly however.

### Current vs. Expected behavior

Should be the same as in 13.4.12

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 8.8.0
Relevant Packages:
  next: 13.5.4-canary.11
  eslint-config-next: 13.4.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.0.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router
