### ISSUE TITLE
Heroicons  package stopped working in tests

### ISSUE THREAD

**Issue by weyert** [vercel/next.js#54038]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.16
      eslint-config-next: 13.4.16
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Jest (next/jest)

### Link to the code that reproduces this issue or a replay of the bug

n/a

### To Reproduce

```
import * as React from 'react'
import { XMarkIcon } from '@heroicons/react/20/solid'

export function CloseButton({
  onClick,
}: {
  onClick?: (event: React.SyntheticEvent<HTMLButtonElement, MouseEvent>) => void
}) {
  return (
    <button
      onClick={onClick}
      type="button"
      className="inline-flex items-center p-2 text-white border border-transparent rounded-full shadow-sm bg-primary-normal hover:bg-primary-selected focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-normal"
      data-testid="modal-close-button"
      title="Close"
    >
      <XMarkIcon className="w-5 h-5" aria-hidden="true" />
    </button>
  )
}

export function WrapperLayout() => {
  return (<CloseButton />)
}

```

```
const nextJest = require('next/jest')

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
})

const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/setupTests.tsx'],
  moduleDirectories: ['node_modules', '<rootDir>/'],
  testEnvironment: 'jest-environment-jsdom',
  testMatch: ['**/__tests__/**/*.(test|spec).(js|jsx|ts|tsx)'].filter(Boolean),
  moduleNameMapper: {
    '^@/layouts/(.*)$': '<rootDir>/src/layouts/$1',
  },
}

// Based on the comment: https://github.com/remarkjs/react-markdown/issues/635#issuecomment-1368289666
async function jestConfig() {
  const nextJestConfig = await createJestConfig(customJestConfig)()
  // nextJestConfig.transformIgnorePatterns[0] = `/node_modules/(?!${esModules}).+.(js|jsx|mjs|cjs|ts|tsx)$`
  return nextJestConfig
}

module.exports = jestConfig
```

```typescript
  test('renders component', async () => {
    render(< WrapperLayout />)
  })
```

### Describe the Bug

After upgrading to 13.4.16 from 13.4.13  my unit tests stopped working for any test cases that test components that use the `@heroicons/react`-package with the error:

app:test:     Cannot find module '@heroicons/react/20/solid/esm/Squares2X2Icon' from 'src/layouts/WrapperLayout.tsx'

### Expected Behavior

I would expect that the unit tests to pass

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

Other platform

<sub>[NEXT-1517](https://linear.app/vercel/issue/NEXT-1517/heroicons-package-stopped-working-in-tests)</sub>

**Comment by weyert** [comment]
I think it's related to this PR: https://github.com/vercel/next.js/pull/53902/files

**Comment by shuding** [comment]
Very strange as this works in a regular Next.js application, so probably `next/jest` related.

**Comment by weyert** [comment]
Maybe it’s because it points to the esm version?

**Comment by weyert** [comment]
Experiencing a similar issue now with `@headlessui/react`-package and created a repro for it here:
https://github.com/vercel/next.js/issues/54286#issuecomment-1685124105

**Comment by Eliepse** [comment]
Glad to see that I'm not the only one, I lost several hours trying to solve this bug but couldn't find a solution.
I'm using _pnpm_ and have the exact same problem.

**Comment by edenstrom** [comment]
Same issue in this closed issue: https://github.com/vercel/next.js/issues/53668
