### ISSUE TITLE
[Turbopack Nextjs 16]: Pino - Cannot find module './transport-stream'

### ISSUE THREAD

**Issue by CHC383** [vercel/next.js#87342]
This is the same issue as #86099. The original issue deviated to `Turbopack + non-Vercel deployment` and closed after that case was fixed. However, the `Turbopack + Vercel deployment (AWS Lambda)` scenario still has the errors below, tested with `v16.1.0`.

Thanks @lukesandberg for the workaround https://github.com/CHC383/nextjs-turbopack-pino-reproduction/pull/1

---

### Link to the code that reproduces this issue

https://github.com/CHC383/nextjs-turbopack-pino-reproduction

### To Reproduce

1. Deploy the code to Vercel
2. Visit <url>/api/log
3. Check the log of the Vercel deployment

## Current behavior

With Turbopack in NextJs v16, Pino worker thread throws the following error:

```
Uncaught Exception: Error: Cannot find module './transport-stream'
Require stack:
- /var/task/node_modules/.pnpm/pino@10.1.0/node_modules/pino/lib/worker.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Module._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Module.require (node:internal/modules/cjs/loader:1463:12)
    at require (node:internal/modules/helpers:147:16)
    at Object.<anonymous> (/var/task/node_modules/.pnpm/pino@10.1.0/node_modules/pino/lib/worker.js:7:36)
    at Module._compile (node:internal/modules/cjs/loader:1706:14)
```

## Expected behavior

Pino worker thread works without any exception, which is the behavior of using WebPack.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #89-Ubuntu SMP PREEMPT_DYNAMIC Sat Oct 11 01:02:46 UTC 2025
  Available memory (MB): 15839
  Available CPU cores: 20
Binaries:
  Node: 24.12.0
  npm: 11.6.2
  Yarn: N/A
  pnpm: 10.26.0
Relevant Packages:
  next: 16.1.0 // Latest available version is detected (16.1.0).
  eslint-config-next: N/A
  react: 19.2.3
  react-dom: 19.2.3
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by arolariu** [comment]
I'm also having the same problem after the recent update to 16.1, but for OpenTelemetry packages....

> 2025-12-19T12:08:53.6150727Z Error: An error occurred while loading instrumentation hook: Failed to load external module @opentelemetry/api-6ec0324a2d0bd38c: Error: Cannot find module '@opentelemetry/api-6ec0324a2d0bd38c'
2025-12-19T12:08:53.6151079Z Require stack:
2025-12-19T12:08:53.6151150Z - /app/.next/server/chunks/[root-of-the-server]__47410f50._.js
2025-12-19T12:08:53.6151175Z - /app/.next/server/chunks/[turbopack]_runtime.js
2025-12-19T12:08:53.6151192Z - /app/.next/server/instrumentation.js
2025-12-19T12:08:53.6151212Z - /app/node_modules/next/dist/server/lib/router-utils/instrumentation-globals.external.js
2025-12-19T12:08:53.6151229Z - /app/node_modules/next/dist/server/next-server.js
2025-12-19T12:08:53.6151246Z - /app/node_modules/next/dist/server/next.js
2025-12-19T12:08:53.6151262Z - /app/server.js
2025-12-19T12:08:53.6151280Z at Context.externalRequire [as x] (.next/server/chunks/[turbopack]_runtime.js:535:15)
2025-12-19T12:08:53.6151299Z at module evaluation (.next/server/chunks/[root-of-the-server]__47410f50._.js:1:46)
2025-12-19T12:08:53.6151318Z at instantiateModule (.next/server/chunks/[turbopack]_runtime.js:740:9)
2025-12-19T12:08:53.6151338Z at getOrInstantiateModuleFromParent (.next/server/chunks/[turbopack]_runtime.js:763:12)
2025-12-19T12:08:53.6151373Z at Context.esmImport [as i] (.next/server/chunks/[turbopack]_runtime.js:228:20)
2025-12-19T12:08:53.6151391Z at <unknown> (.next/server/chunks/[root-of-the-server]__47410f50._.js:1:1407)
2025-12-19T12:08:53.6151409Z at Context.asyncModule [as a] (.next/server/chunks/[turbopack]_runtime.js:455:5)
2025-12-19T12:08:53.6151427Z at module evaluation (.next/server/chunks/[root-of-the-server]__47410f50._.js:1:1334)
2025-12-19T12:08:53.6151445Z at instantiateModule (.next/server/chunks/[turbopack]_runtime.js:740:9)
2025-12-19T12:08:53.6151463Z at getOrInstantiateModuleFromParent (.next/server/chunks/[turbopack]_runtime.js:763:12)


---

I've added them to the `serverExternalPackages` as such:

```ts
  serverExternalPackages: [
    "@azure/identity",
    "@azure/monitor-opentelemetry-exporter",
    "@opentelemetry/api",
    "@opentelemetry/auto-instrumentations-node",
    "@opentelemetry/exporter-logs-otlp-http",
    "@opentelemetry/exporter-metrics-otlp-http",
    "@opentelemetry/exporter-trace-otlp-http",
    "@opentelemetry/instrumentation",
    "@opentelemetry/resources",
    "@opentelemetry/sdk-metrics",
    "@opentelemetry/sdk-node",
    "@opentelemetry/sdk-trace-node",
    "@opentelemetry/semantic-conventions",
  ],
```

But it still complains with the above error.

**Comment by tkmcmaster** [comment]
Similar issues:
```
⨯ Error: Failed to load external module styled-components-bd377d8093d58039: SyntaxError: Unexpected token '.'
    at Context.externalRequire [as x] (dist/server/chunks/ssr/[turbopack]_runtime.js:535:15)
    at module evaluation (dist/server/chunks/ssr/[root-of-the-server]__ba9569cc._.js:6:2743)
    at instantiateModule (dist/server/chunks/ssr/[turbopack]_runtime.js:740:9)
    at getOrInstantiateModuleFromParent (dist/server/chunks/ssr/[turbopack]_runtime.js:763:12)
    at Context.esmImport [as i] (dist/server/chunks/ssr/[turbopack]_runtime.js:228:20)
    at module evaluation (dist/server/chunks/ssr/[root-of-the-server]__ba9569cc._.js:6:2890)
    at instantiateModule (dist/server/chunks/ssr/[turbopack]_runtime.js:740:9)
    at instantiateRuntimeModule (dist/server/chunks/ssr/[turbopack]_runtime.js:768:12)
    at getOrInstantiateRuntimeModule (dist/server/chunks/ssr/[turbopack]_runtime.js:781:12)
    at Object.m (dist/server/chunks/ssr/[turbopack]_runtime.js:790:18)
```

```Javascript
  serverExternalPackages: [
    "@aws-sdk/client-s3",
    "@aws-sdk/s3-request-presigner",
    "@aws-sdk/client-sqs",
    "@aws-sdk/credential-providers",
    "@aws-sdk/ec2-metadata-service",
    "@aws-sdk/lib-storage",
    "styled-components",
    "aws-crt",
    "sharp"
  ],
```
and `serverExternalPackages` did not solve the issue. We went from Next 16.0.10 to 16.1.0. Testing rolling back to see if it solves the issue.

Edit: Downgrading to Next 16.0.10 works.

**Comment by arolariu** [comment]
This seems like a pretty serious issue that was not documented thoroughly.

@icyJoseph - can we get an official acknowledgment from nextjs team about this issue, or an explanation on what we are doing wrong? 

In the release blog post there's no mention of this side effect.

**Comment by amolagre** [comment]
I am having similar issue with `"next-auth": "5.0.0-beta.29"` after upgrading to `v16.1.0`
```
Error: Failed to load external module next-auth-5ef33c431079c29a:
  Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.\node_modules\.pnpm\next-auth@5.0.0-beta.29_nex_6e95a68da9e729511a9047940c90021d\node_modules\next\server'
  imported from .\node_modules\.pnpm\next-auth@5.0.0-beta.29_nex_6e95a68da9e729511a9047940c90021d\node_modules\next-auth\lib\env.js
Did you mean to import "next/server.js"?
  at ignore-listed frames
```

Downgrading back to `16.0.10` resolved issue.

**Comment by lukesandberg** [comment]
A workaround for transport-stream is to use an explicit include

https://github.com/CHC383/nextjs-turbopack-pino-reproduction/pull/1

The issue is that the patterns in pinojs are too complex tor turbopack to trace.  This is reported upstream here: https://github.com/pinojs/thread-stream/issues/184

**Comment by Netail** [comment]
> A workaround for transport-stream is to use an explicit include
> 
> https://github.com/CHC383/nextjs-turbopack-pino-reproduction/pull/1
> 
> The issue is that the patterns in pinojs are too complex tor turbopack to trace.  This is reported upstream here: https://github.com/pinojs/thread-stream/issues/184
> 

Is this something Turbopack will tackle in the future? Would be annoying if Turbopack wouldn't be able to handle these cases, while it should be a webpack replacement.

**Comment by CHC383** [comment]
> A workaround for transport-stream is to use an explicit include
> 
> [CHC383/nextjs-turbopack-pino-reproduction#1](https://github.com/CHC383/nextjs-turbopack-pino-reproduction/pull/1)
> 
> The issue is that the patterns in pinojs are too complex tor turbopack to trace. This is reported upstream here: [pinojs/thread-stream#184](https://github.com/pinojs/thread-stream/issues/184)

Thanks, I confirmed that the workaround resolved the issue.



> I am having similar issue with `"next-auth": "5.0.0-beta.29"` after upgrading to `v16.1.0`
> 
> ```
> Error: Failed to load external module next-auth-5ef33c431079c29a:
>   Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.\node_modules\.pnpm\next-auth@5.0.0-beta.29_nex_6e95a68da9e729511a9047940c90021d\node_modules\next\server'
>   imported from .\node_modules\.pnpm\next-auth@5.0.0-beta.29_nex_6e95a68da9e729511a9047940c90021d\node_modules\next-auth\lib\env.js
> Did you mean to import "next/server.js"?
>   at ignore-listed frames
> ```
> 
> Downgrading back to `16.0.10` resolved issue.

I ran into a similar error with Vitest (Vite) previously while using `next-auth` (have switched to `better-auth`), and the workaround was https://github.com/vitest-dev/vitest/issues/4554#issuecomment-1827824912. Just a pointer but not sure about the proper fix.

**Comment by Aluisio** [comment]
I have a similar problem with styled components.
`Error: Failed to load external module styled-components-bd377d8093d58039: Error: Cannot find module 'styled-components-bd377d8093d58039'`

**Comment by amolagre** [comment]
Thanks @CHC383 ,

> I ran into a similar error with Vitest (Vite) previously while using next-auth (have switched to better-auth), and the workaround was https://github.com/vitest-dev/vitest/issues/4554#issuecomment-1827824912. Just a pointer but not sure about the proper fix.

I’ll take a look into it. What’s bothering me is that this was working up to Next.js `v16.0.10` and stopped working in `v16.1.0`.
I’m also aware that `next-auth` isn’t actively maintained at the moment. I already had a migration to `better-auth` planned, but it looks like I’ll need to prioritize it now.

**Comment by markedwards** [comment]
We are also hitting an issue with a self-hosted standalone build of Next 16.1.4, when trying to use `@serdnam/pino-cloudwatch-transport`.  Including it in `serverExternalPackages` used to work with webpack, but with Turbopack it breaks.
