### ISSUE TITLE
Vercel's injected build adapter (next >=16.2) mis-packages basePath apps' .well-known route functions — works on 16.1.7 / legacy builder

### ISSUE THREAD

**Issue by leonardosaullo** [vercel/next.js#96512]
### Corrected analysis (supersedes the original report — the version bisect below was refined by elimination testing; apologies for the churn)

**Trigger: the combination of (a) a `basePath` in next.config, (b) app-router routes under `.well-known/` (Workflow DevKit's `/.well-known/workflow/v1/{flow,step}`), and (c) a REMOTE Vercel build on next >= 16.2** — where Vercel injects the new build adapter (`Applying modifyConfig from Vercel` / `Running onBuildComplete from Vercel` in build logs). Local `vercel build` (which does not run the adapter) packages the same source correctly on every version we tested.

**Failure modes observed (same app, basePath `/ingestion`):**
- **Bun runtime** (`bunVersion: 1.x`): the functions ship without the Turbopack external-alias content (`.next/node_modules/mongodb-<hash>` symlinks dropped) — build green, runtime dies pre-boot on `Cannot find package 'mongodb-<hash>'`. Force-including the symlinks flips it to a hard error: *"invalid deployment package … files in symlinked directories"*.
- **Node runtime**: the launcher fails with `Cannot find module './.next/server/pages/ingestion/.well-known/workflow/v1/flow.js'` — pages-router path with the **basePath baked into the page identity** (the route is an app-router route; basePath should never appear in the page name).

**Eliminated variables** (each tested with a production deploy + an actual workflow execution): next 16.2.9 vs 16.2.11 (both broken remotely), bun vs node runtime (both broken, different symptom), `VERCEL_CLI_VERSION` 57 vs 58 (both broken — the adapter injection is version-of-next-gated, not CLI-gated), build cache on/off.

**Control case:** a sibling app with an IDENTICAL stack (next 16.2.9, Turbopack, bun package manager, Bun runtime, WDK, same Vercel team/fleet) but **no basePath** deploys and runs workflows correctly via remote builds — verified live.

**Working configurations:**
1. **next 16.1.7** — remote build falls back to the legacy builder (`Traced Next.js server files…`), functions package correctly, workflows verified end-to-end. This is our current pin.
2. Local `vercel build` + `vercel deploy --prebuilt` on ANY version — after replacing the alias symlinks with real directories and expanding directory-valued `filePathMap` entries per-file (the prebuilt path otherwise rejects the symlinks with the same *invalid deployment package* error).

Environment: Next 16.1.7 (pinned; broken on 16.2.9/16.2.10/16.2.11), Turbopack, `basePath: '/ingestion'`, workflow (WDK) 4.4.0, bun package manager, deployed to Vercel (team fleet CLI 58.1.0). Deployment IDs for every combination above available on request.
