### ISSUE TITLE
Cannot find module '@next/third-parties/google' when trying to import GoogleTagManager

### ISSUE THREAD

**Issue by renanleonel** [vercel/next.js#58697]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/musing-solomon-f4tnqz?file=%2Fapp%2Flayout.tsx%3A8%2C11

### To Reproduce

1. Start application with next dev
2. Check layout.tsx
3. import error `Cannot find module '@next/third-parties/google' or its corresponding type declarations.typescript(2307)`

### Current vs. Expected behavior

Expected: import work as intended in documentation https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#google-tag-manager

Current: import not working
![image](https://github.com/vercel/next.js/assets/62075475/6baaf911-5196-4cdd-984c-62c86c306c31)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Node: v20.9.0
Next: 14.0.3,
React: 8.2.0
react-dom: 18.2.0,
npm: 10.1.0

Windows 11
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Tested using next/canary, next v14 and nextv13, all with same problems.

after changing the import to  `import { GoogleTagManager } from '@next/third-parties/dist/google'`, the error goes away but when building the application i got an error because there is no exported module in node_modules\@next\third-parties\dist\google.

package.json

![image](https://github.com/vercel/next.js/assets/62075475/f0670b24-9091-4857-bd53-74d32cba0727)

Error message:

Failed to compile.
./src/app/layout.tsx
Module not found: Package path ./dist/google is not exported from package /tmp/build_6a78ac44/node_modules/@next/third-parties (see exports field in /tmp/build_6a78ac44/node_modules/@next/third-parties/package.json)

**Comment by djshubs** [comment]
I have the same error.

**Comment by roryf** [comment]
Although my editor highlights the error, it works as expected in development server, but build command fails locally and on vercel.

**Comment by AntonyJudeShaman** [comment]
Had the same issue with this `import { GoogleTagManager } from '@next/third-parties/google'`

Use `npm install @next/third-parties` or `npm install @next/third-parties` based on your package manager.

Now import the module **GoogleTagManager** and it lets you use it without any error in both local development and production. 
It worked fine for me when i pushed it to **Vercel**

**Comment by kasyap-007** [comment]
This is due to the typescript's module resolution strategy.
update tsconfig.json to use `"moduleResolution": "Bundler",`

**Comment by z0n** [comment]
> update tsconfig.json to use `"moduleResolution": "Bundler",`

That does indeed fix GTM but unfortunately breaks a different module import. Is this something package authors need to fix?

**Comment by djshubs** [comment]
> > update tsconfig.json to use `"moduleResolution": "Bundler",`
> 
> That does indeed fix GTM but unfortunately breaks a different module import. Is this something package authors need to fix?

I have `Combobox` from [headlessui](https://github.com/tailwindlabs/headlessui) breaking because of it.

**Comment by huozhi** [comment]
We fixed it in v14.0.4-canary.40, please upragde!

**Comment by paqstd-dev** [comment]
Still not working in 14.0.4. 

> [!CAUTION]
> Cannot find module '@next/third-parties/google' or its corresponding type declarations.

**Comment by renanleonel** [comment]
> Still not working in 14.0.4.
> 
> Caution
> 
> Cannot find module '@next/third-parties/google' or its corresponding type declarations.

added this to my tsconfig.json, under paths

`"paths": {
            "@next/third-parties/google": [
                "./node_modules/@next/third-parties/dist/google"
            ]
        }`

and importing on layout.tsx

`import { GoogleTagManager } from '@next/third-parties/google';`

currently working on `"next": "^14.0.4",`

**Comment by paqstd-dev** [comment]
> > Still not working in 14.0.4.
> > Caution
> > Cannot find module '@next/third-parties/google' or its corresponding type declarations.
> 
> added this to my tsconfig.json, under paths
> 
> `"paths": { "@next/third-parties/google": [ "./node_modules/@next/third-parties/dist/google" ] }`
> 
> and importing on layout.tsx
> 
> `import { GoogleTagManager } from '@next/third-parties/google';`
> 
> currently working on `"next": "^14.0.4",`

Yes, that's what I did. That helped. Thank you.
But why not add this to the documentation then? This looks like a local crutch, but not a global one for everyone. Cause I'd like to use it out of the box

**Comment by renanleonel** [comment]
> > > Still not working in 14.0.4.
> > > Caution
> > > Cannot find module '@next/third-parties/google' or its corresponding type declarations.
> > 
> > 
> > added this to my tsconfig.json, under paths
> > `"paths": { "@next/third-parties/google": [ "./node_modules/@next/third-parties/dist/google" ] }`
> > and importing on layout.tsx
> > `import { GoogleTagManager } from '@next/third-parties/google';`
> > currently working on `"next": "^14.0.4",`
> 
> Yes, that's what I did. That helped. Thank you. But why not add this to the documentation then? This looks like a local crutch, but not a global one for everyone. Cause I'd like to use it out of the box

i agree, tried without this tsconfig.json and didn't work. hope they'll fix it soon

**Comment by DevYemi** [comment]
> 14.0.4-canary.40

Hi there, i upgraded to v14.0.4-canary.40 and I'm still getting the same error

**Comment by danwild** [comment]
Tagging as dupe of https://github.com/vercel/next.js/issues/58458

**Comment by ryancwalsh** [comment]
https://github.com/vercel/next.js/issues/58697#issuecomment-1830677388 helped me with my static site. Thanks.

**Comment by V-iktor** [comment]
Not fixed in 14.0.4



> > Although my editor highlights the error, it works as expected in development server, but build command fails locally and on vercel.
> 
> I added the following in my tsconfig under paths, and its allowing me to build locally. Yet to test remote.
> 
> ` "@next/third-parties/google": [ "./node_modules/@next/third-parties/dist/google" ]`

This works for me

**Comment by ETOPS7** [comment]
> > I added the following in my tsconfig under paths, and its allowing me to build locally. Yet to test remote.
> > ` "@next/third-parties/google": [ "./node_modules/@next/third-parties/dist/google" ]`
> 
> This works for me

It helps me too, but I guess crutch. Good to wait for official solution.

**Comment by isaacdarcilla** [comment]
> > Although my editor highlights the error, it works as expected in development server, but build command fails locally and on vercel.
> 
> I added the following in my tsconfig under paths, and its allowing me to build locally. Yet to test remote.
> 
> ` "@next/third-parties/google": [ "./node_modules/@next/third-parties/dist/google" ]`

This works for me  "@next/third-parties": "^14.0.4",

**Comment by Evavic44** [comment]
As of the latest canary release, you no longer need the `tsconfig` hack, simply upgrade `@next/third-parties` to the latest [canary version](https://www.npmjs.com/package/@next/third-parties?activeTab=versions)

```js
npm i @next/third-parties@14.0.5-canary.59
```

And then imports should work as expected:

```tsx
import { GoogleAnalytics } from "@next/third-parties/google";
```

Tested and working on `next 14.0.4`
