### ISSUE TITLE
Error: Cannot find module '@babel/helper-plugin-utils' after upgrading to 10.0.3

### ISSUE THREAD

**Issue by dylanesque** [vercel/next.js#20321]
# Bug report

## Describe the bug

I upgraded from Next version 9.4.1 to 10.0.3, and I received the following error after running `npm run dev`:

```
ready - started server on http://localhost:3000
error - ./node_modules/next/dist/client/next-dev.js   
Error: Cannot find module '@babel/helper-plugin-utils'
Require stack:
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\babel-plugin-graphql-tag\dist\index.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\compiled\babel\bundle.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\compiled\babel\code-frame.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\lib\typescript\diagnosticFormatter.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\lib\typescript\runTypeCheck.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\lib\verifyTypeScriptSetup.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\server\next-dev-server.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\server\next.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\server\lib\start-server.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\cli\next-dev.js
- C:\Users\Michael C.000\Desktop\React\app-boilerplate\node_modules\next\dist\bin\next
```
Deleting the package-lock.json and the node-modules folder had no effect.
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## Expected behavior

I expected the application to run as normal, instead of failing.

## System information

- OS: Windows 10
- Version of Next.js: 10.0.3
- Version of Node.js: 12.14.0
- Deployment: N/A
