### ISSUE TITLE
Cannot build with `typescript: 5.4.2`: Cannot find module 'next/dist/lib/metadata/types/metadata-interface.js' or its corresponding type declarations.

### ISSUE THREAD

**Issue by seheon99** [vercel/next.js#63271]
### Link to the code that reproduces this issue

https://github.com/Team-Crops/fit-web/tree/dev

### To Reproduce

1. Clone repository
    ```sh
	git clone git@github.com:team-crops/fit-web
	```
2. Change directory and Checkout `dev` branch
	```sh
	cd fit-web && git checkout dev
	```
3. Change typescript version to `5.4.2` and next version to canary in `package.json`
	```sh
	yarn add next@canary && yarn add -D typescript@5.4.2
	```
4. Install packages and build
	```sh
	yarn && yarn build
	```

```text
Cannot find module 'next/dist/lib/metadata/types/metadata-interface.js' or its corresponding type declarations.
```

### Current vs. Expected behavior

I expected to no error because `yarn run dev` works fine, but there is an type error

### Provide environment information

```text
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:28:44 UTC 2023
  Available memory (MB): 63966
  Available CPU cores: 4
Binaries:
  Node: 21.1.0
  npm: 10.1.0
  Yarn: 4.1.0
  pnpm: N/A
Relevant Packages:
  next: 14.2.0-canary.21 // Latest available version is detected (14.2.0-canary.21).
  eslint-config-next: 14.0.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, CLI (create-next-app)

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

It works fine when I change TypeScript version from `^5` to `5.3.2`

**Comment by devjiwonchoi** [comment]
Hi, have you tried using a different package manager, like `pnpm`? The issue doesn't seem to be from Next.js.

**Comment by seheon99** [comment]
Thanks, it works fine with `pnpm`. I will report this issue back to yarn.
