### ISSUE TITLE
Module not found error when using use client

### ISSUE THREAD

**Issue by indahud** [vercel/next.js#56868]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/wandering-dust-gl5k5z

### To Reproduce

1. Create a new client component
2. Try installing prettier package
3. Add prettier in client component inside the asynchronous function & call it `await prettier.format('<p>test html</p>', { parser: 'html' })`
4. Import the component in `app/page.tsx`

### Current vs. Expected behavior

It gives error like this
```bash
./node_modules/prettier/index.mjs:1:0
Module not found: Can't resolve 'module'
```
If i remove `use client` it works fine.
It should work on client side as well.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating Sysytem:
    Platform: Linux
    Arxh: x86
    Version: 6.1.55-1-MANJARO
Binaries:
    Node: v18.16.1
    npm - 9.5.1
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by zeekrey** [comment]
Prettier usually relies on node.js. However, if you want to use it in a browser, you can utilize the standalone version provided by 'prettier/standalone'. You can find detailed documentation on this topic here: [Prettier Browser Documentation](https://prettier.io/docs/en/browser).

I have forked your Codesandbox, and you can access it here: [Forked Codesandbox](https://codesandbox.io/p/sandbox/wandering-dust-gl5k5z).

Hope this helps. ✌🏻

**Comment by indahud** [comment]
Thanks @zeekrey works perfectly.

**Comment by lucgagan** [comment]
I have the opposite problem.

```ts
import * as babel from 'prettier/plugins/babel';
import * as estree from 'prettier/plugins/estree';
import * as typescript from 'prettier/plugins/typescript';
import { format } from 'prettier/standalone';

export const formatJavaScript = (code: string) => {
  return format(code, {
    parser: 'typescript',
    plugins: [babel, typescript, estree],
  });
};
```

This works on client side, but breaks on server-side.

```
 ⨯ src/utilities/formatJavaScript.ts (7:16) @ code
 ⨯ TypeError: (0 , prettier_standalone__WEBPACK_IMPORTED_MODULE_3__.format) is not a function
    at formatJavaScript (./src/utilities/formatJavaScript.ts:14:71)
    at convertSeleniumToPlaywright (./src/actions/convertSeleniumToPlaywright.ts:24:87)
   5 |
   6 | export const formatJavaScript = (code: string) => {
>  7 |   return format(code, {
     |                ^
   8 |     parser: 'typescript',
   9 |     plugins: [babel, typescript, estree],
  10 |   });
```

This was working correctly in v13 and broke after updating to v14.

**Comment by lucgagan** [comment]
https://github.com/vercel/next.js/discussions/57707
