### ISSUE TITLE
upgrade to @typescript-eslint/parser v6 in eslint-config-next

### ISSUE THREAD

**Issue by yf-yang** [vercel/next.js#52890]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Tue Jul 11 08:42:52 UTC 2023
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.7
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

ESLint (eslint-config-next)

### Link to the code that reproduces this issue or a replay of the bug

nope

### To Reproduce

nope

### Describe the Bug

I am using next as one repo of a monorepo, so for all of them I am using a global typescript eslint dependency. After upgrading typescript eslint to v6 (both rules and parser), other repos are working as expected, but next repo is corrupt because when computing one of the rule
```
TypeError: services.getTypeAtLocation is not a function
```

If I got it right, it is related to an [API breaking change](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#type-checker-wrapper-apis). Therefore, I check @typescript-eslint/parser's version, it is 5.62 in next repo, but it is 6.1 in other repos.

Therefore, maybe the problem is [eslint-config-next](https://github.com/vercel/next.js/blob/canary/packages/eslint-config-next/package.json)'s dependency, which is still `^5.42`

### Expected Behavior

Successfully run @typescript-eslint v6 plugin

**Comment by balazsorban44** [comment]
Thanks, you can follow this PR for updates: #52848

**Comment by cjkihl** [comment]
In the meanwhile, if you're using PNPM, you can use PNPM overrides to force using version 6.2.0:
Add to your `package.json`:

```json
 "pnpm": {
    "overrides": {
      "@typescript-eslint/parser": "6.2.0"
    }
  }
```

Then run `pnpm install` again

**Comment by kachkaev** [comment]
Upgrading to `eslint-config-next@13.4.13` also helps. Here is the output of `pnpm why @typescript-eslint/parser`:

## Before

```
devDependencies:
@typescript-eslint/eslint-plugin 6.2.0
└── @typescript-eslint/parser 6.2.1 peer
eslint-config-next 13.4.12
├── @typescript-eslint/parser 5.62.0
├─┬ eslint-import-resolver-typescript 3.5.5
│ ├─┬ eslint-module-utils 2.8.0
│ │ └── @typescript-eslint/parser 5.62.0 peer
│ └─┬ eslint-plugin-import 2.28.0 peer
│   ├── @typescript-eslint/parser 5.62.0 peer
│   └─┬ eslint-module-utils 2.8.0
│     └── @typescript-eslint/parser 5.62.0 peer
└─┬ eslint-plugin-import 2.28.0
  ├── @typescript-eslint/parser 5.62.0 peer
  └─┬ eslint-module-utils 2.8.0
    └── @typescript-eslint/parser 5.62.0 peer
eslint-plugin-import 2.28.0
├── @typescript-eslint/parser 6.2.1 peer
└─┬ eslint-module-utils 2.8.0
  └── @typescript-eslint/parser 6.2.1 peer
eslint-plugin-unused-imports 3.0.0
└─┬ @typescript-eslint/eslint-plugin 6.2.0 peer
  └── @typescript-eslint/parser 6.2.1 peer
```
  

## After

```
devDependencies:
@typescript-eslint/eslint-plugin 6.2.0
└── @typescript-eslint/parser 6.2.1 peer
eslint-config-next 13.4.13
├── @typescript-eslint/parser 6.2.1
├─┬ eslint-import-resolver-typescript 3.5.5
│ ├─┬ eslint-module-utils 2.8.0
│ │ └── @typescript-eslint/parser 6.2.1 peer
│ └─┬ eslint-plugin-import 2.28.0 peer
│   ├── @typescript-eslint/parser 6.2.1 peer
│   └─┬ eslint-module-utils 2.8.0
│     └── @typescript-eslint/parser 6.2.1 peer
└─┬ eslint-plugin-import 2.28.0
  ├── @typescript-eslint/parser 6.2.1 peer
  └─┬ eslint-module-utils 2.8.0
    └── @typescript-eslint/parser 6.2.1 peer
eslint-plugin-import 2.28.0
├── @typescript-eslint/parser 6.2.1 peer
└─┬ eslint-module-utils 2.8.0
  └── @typescript-eslint/parser 6.2.1 peer
eslint-plugin-unused-imports 3.0.0
└─┬ @typescript-eslint/eslint-plugin 6.2.0 peer
  └── @typescript-eslint/parser 6.2.1 peer
```

(`@typescript-eslint/parser 5.62.0` is gone)

What’s odd is that the problem with the parser only occurred for one developer in our team. Seems to be something to do with non-deterministic hoisting in `pnpm`.
