### ISSUE TITLE
Unit tests break when using `@headless/ui`-package

### ISSUE THREAD

**Issue by weyert** [vercel/next.js#54286]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Jest (next/jest)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/weyert/nextjs-jest-modularize-imports

### To Reproduce

1. Create Next.js application
2. Create component which uses `import { Dialog, Transition } from '@headlessui/react'`
3. Write unit tests that renders the componet
4. Run unit tests
5. Note the the test failing (see error below)

### Describe the Bug

When you try to run the unit tests you can get an error after upgrading to 13.4.9:

```
 FAIL  src/__tests__/pages/CallbackPage.test.tsx
  ● Test suite failed to run

    Cannot find module 'modularize-import-loader?name=Dialog&join=./components/dialog/dialog!@headlessui/react' from 'src/layouts/SiteLayout.tsx'

    Require stack:
      src/layouts/SiteLayout.tsx
      src/layouts/getLayoutComponent.tsx
      src/pages/auth/callback.tsx
      src/__tests__/pages/CallbackPage.test.tsx

      21 | import { useAuth } from '@/auth/usercontext/useAuth'
      22 |
    > 23 | interface SiteLayoutProps extends Omit<LayoutProps, 'Layout'> {
         |                ^
      24 |   children: React.ReactNode
      25 |   showCategoriesList?: boolean
      26 | }

      at Resolver._throwModNotFoundError (../../node_modules/.pnpm/jest-resolve@29.6.2/node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (src/layouts/SiteLayout.tsx:23:16)
      at Object.<anonymous> (src/layouts/getLayoutComponent.tsx:11:21)
      at Object.<anonymous> (src/pages/apps/auth/callback.tsx:37:29)
      at Object.<anonymous> (src/__tests__/pages/CallbackPage.test.tsx:13:19)
```

### Expected Behavior

I would expect unit tests to pass when not making any code changes but only upgrading to a newer version of Next when no breaking changes are listed in the release notes

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

Other platform

**Comment by weyert** [comment]
I have added a repro here: https://github.com/weyert/nextjs-jest-modularize-imports
When you run `npm run build` everything is fine:
```
❯ npm run build

> ui@0.0.0 build
> next build

- warn You have enabled experimental feature (externalDir) in next.config.js.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

- info Linting and checking validity of types  
- info Creating an optimized production build  
- info Compiled successfully
- info Collecting page data  
- info Generating static pages (2/2)
- info Finalizing page optimization  

Route (pages)                              Size     First Load JS
┌ λ /                                      15 kB            95 kB
├   /_app                                  0 B              80 kB
└ ○ /404                                   182 B          80.1 kB
+ First Load JS shared by all              80 kB
  ├ chunks/framework-63157d71ad419e09.js   45.2 kB
  ├ chunks/main-594acc6ec9f44333.js        33.4 kB
  ├ chunks/pages/_app-e057d3ea87146833.js  444 B
  └ chunks/webpack-0b5d8249fb15f5f3.js     939 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```

But when you try to run tests its failing with the following error:
```
❯ npm run test 

> ui@0.0.0 test
> env TZ=Etc/UTC jest --runInBand

- warn You have enabled experimental feature (externalDir) in next.config.js.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

 FAIL  src/layouts/__tests__/SiteLayout.test.tsx
  ● Test suite failed to run

    Cannot find module 'modularize-import-loader?name=Dialog&join=./components/dialog/dialog!@headlessui/react' from 'src/layouts/SiteLayout.tsx'

    Require stack:
      src/layouts/SiteLayout.tsx
      src/layouts/__tests__/SiteLayout.test.tsx

      21 |   const navIsOpen = true
      22 |   const setNavIsOpen = (value: boolean) => {
    > 23 |     console.log(`SiteLayout.setNavIsOpen() called value=${value}`)
         |                ^
      24 |   }
      25 |
      26 |   return (

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (src/layouts/SiteLayout.tsx:23:16)
      at Object.<anonymous> (src/layouts/__tests__/SiteLayout.test.tsx:7:21)

 FAIL  src/__tests__/pages/StartPage.test.tsx
  ● Test suite failed to run

    Cannot find module 'modularize-import-loader?name=Dialog&join=./components/dialog/dialog!@headlessui/react' from 'src/layouts/SiteLayout.tsx'

    Require stack:
      src/layouts/SiteLayout.tsx
      src/pages/index.tsx
      src/__tests__/pages/StartPage.test.tsx

      21 |   const navIsOpen = true
      22 |   const setNavIsOpen = (value: boolean) => {
    > 23 |     console.log(`SiteLayout.setNavIsOpen() called value=${value}`)
         |                ^
      24 |   }
      25 |
      26 |   return (

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (src/layouts/SiteLayout.tsx:23:16)
      at Object.<anonymous> (src/pages/index.tsx:21:60)
      at Object.<anonymous> (src/__tests__/pages/StartPage.test.tsx:6:55)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.937 s
Ran all test suites.
```

**Comment by LukasGerm** [comment]
I have the same issue. Is it fixed already? Can still reproduce in 1.7.17

**Comment by weyert** [comment]
Works for me in the last canary version

**Comment by ganicus** [comment]
What's the workable solution here?

**Comment by davecarlson** [comment]
> What's the workable solution here?

Waiting for 13.4.20 to be released! It's been fixed for weeks on canary, but for whatever reasons, we've had no new production release for over 3 weeks, which is annoying as there's a ton of fixes since .19, and we dont want to run a canary. ( as such we are currently stuck on .12 .....)

**Comment by t-alex-lopez** [comment]
Cannot find module 'modularize-import-loader?name=Tab&join=./components/tabs/tabs!@headlessui/react' from 'src/components_data/devtools/PantomathDevtools.tsx'
