### PR TITLE
Fix nested esm package default import resolving mismatch

### LINKED ISSUE #57584: Styled-components broken in 14.0.0
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/solitary-architecture-j3rg3n

### To Reproduce

Sandbox show an error about styled-components on NextJs 14.0.0 where on 13.5.6 it works no problem. 
```
> next dev

   ▲ Next.js 14.0.0
   - Local:        http://localhost:3000

 ✓ Ready in 1507ms
 ○ Compiling /page ...
 ✓ Compiled /page in 4.5s (641 modules)
 ⨯ node_modules/.pnpm/react95@4.0.0_react-dom@18.2.0_react@18.2.0_styled-components@5.3.11/node_modules/react95/dist/Anchor/Anchor.mjs (4:27) @ eval
 ⨯ TypeError: styled_components__WEBPACK_IMPORTED_MODULE_1__.a is not a function
    at __webpack_require__ (.../.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (.../.next/server/webpack-runtime.js:33:42)
    at eval (./app/_components/Moni.tsx:7:65)
    at (ssr)/./app/_components/Moni.tsx (.../.next/server/app/page.js:173:1)
    at __webpack_require__ (.../.next/server/webpack-runtime.js:33:42)
null
 ✓ Compiled /favicon.ico/route in 415ms (351 modules)
```

### Current vs. Expected behavior

I expect that styled-components work the same on 14.0.0 as they work on 13.5.6.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.9.2
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

My original problem occurred in private repo with custom styled-component libray which I can't share so I tried with any other public styled-component UI lib. 

> After upgrade to the NextJS 14.0.0 from 13.5.6 I immediately noticed that my root page does (FOUC, or flash of unstyled text). I'm using styled-components with this setup [styled-component-nextjs](https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-components) and it works fine with 13.5.6 but 14.0.0 gives FOUC right off the bat :(

Although I don't see any error within my private repo I can clearly see that something is broken with styled components with 14.0.0 as FOUC appears. On top of that my build increases by few kB just by updating to 14.0.0.

----
## NextJs 13.5.6 (Working) 
1. Build Size - ok
2. 2 Layout Renders - ok
3. StyledComponentRegistry in call tree - ok
4. globals.css present - ok
5. e.generateAndInjectStyles has some secondaryStyles - ok

Screenshot 2023-10-27 at 00 32 50
Screenshot 2023-10-27 at 11 54 17
Screenshot 2023-10-27 at 00 21 49

----
## NextJs 14.0.0 (NOT Working) 
1. Build Size - not ok (increase)
2. 3 Layout Renders - not ok -  FOUC (previously 2 )
3. StyledComponentRegistry NOT in call tree - not ok (NO styledcomponentrregistry)
4. globals.css NOT present - not ok
5. e.generateAndInjectStyles NO secondaryStyles - not ok

Screenshot 2023-10-27 at 00 31 14

Screenshot 2023-10-27 at 11 54 34

Screenshot 2023-10-27 at 00 22 17

<sub>[NEXT-1702](https://linear.app/vercel/issue/NEXT-1702/styled-components-broken-in-1400)</sub>

### PR DESCRIPTION
**Pull request by huozhi**
For app router bundling layers "SSR rendering" and "browser" layer, which are used for server side rendering and client, we should still apply the module resolving rules to all assets since we bundled everything, removed the default exclude conditions as they'll not apply the rules to node_modules. That could cause the mismatch resolving for package.

E.g. You have two dual packages A and B are both compatible for ESM and CJS, and both have default export. B is depent on A, but when you import B in a client component that will be SSR'd, it's picking up the CJS asset like the case described in #57584 .

Fixes #57584 
Closes NEXT-1702

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3d269499b82d59ca5a7eda7cc38421308e8f9bb8

`pnpm test-dev test/development/acceptance-app/app-hmr-changes.test.ts` 
- Error overlay - RSC build errors > should handle successive HMR changes with errors correctly

<details>
<summary>Expand output</summary>

  ● Error overlay - RSC build errors › should handle successive HMR changes with errors correctly

    expect(received).toContain(expected) // indexOf

    Expected substring: "A few years ago I tweeted"
    Received string:    "<head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width\"><meta name=\"next-head-count\" content=\"2\"><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1698705977677\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1698705977677\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1698705977677\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1698705977677\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1698705977677\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body style=\"overflow: hidden;\"><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1698705977677\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"ModuleParseError\",\"source\":\"server\",\"message\":\"Module parse failed: Cannot use 'import.meta' outside a module (52:16)\\nFile was processed with these loaders:\\n * ./node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/@next/react-refresh-utils/dist/loader.js\\n * ./node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/build/webpack/loaders/next-flight-client-module-loader.js\\n * ./node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js\\nYou may need an additional loader to handle the result of these loaders.\\n|                 // still a Refresh Boundary later.\\n|                 // @ts-ignore importMeta is replaced in the loader\\n\\u003e                 import.meta.webpackHot.accept();\\n|                 // This field is set when the previous version of this module was a\\n|                 // Refresh Boundary, letting us know we need to check for invalidation or\",\"stack\":\"ModuleParseError: Module parse failed: Cannot use 'import.meta' outside a module (52:16)\\nFile was processed with these loaders:\\n * ./node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/@next/react-refresh-utils/dist/loader.js\\n * ./node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/build/webpack/loaders/next-flight-client-module-loader.js\\n * ./node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js\\nYou may need an additional loader to handle the result of these loaders.\\n|                 // still a Refresh Boundary later.\\n|                 // @ts-ignore importMeta is replaced in the loader\\n\\u003e                 import.meta.webpackHot.accept();\\n|                 // This field is set when the previous version of this module was a\\n|                 // Refresh Boundary, letting us know we need to check for invalidation or\\n    at handleParseError (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/webpack/bundle5.js:28:401867)\\n    at /tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/webpack/bundle5.js:28:403614\\n    at processResult (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/webpack/bundle5.js:28:399309)\\n    at /tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/webpack/bundle5.js:28:400370\\n    at /tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8727\\n    at iterateNormalLoaders (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5565)\\n    at iterateNormalLoaders (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5650)\\n    at /tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5879\\n    at r.callback (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4039)\\n    at Object.ReactRefreshLoader (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/@next/react-refresh-utils/dist/loader.js:14:10)\\n    at LOADER_EXECUTION (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4134)\\n    at runSyncOrAsync (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4145)\\n    at iterateNormalLoaders (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5782)\\n    at iterateNormalLoaders (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5650)\\n    at /tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5879\\n    at r.callback (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4039)\\n    at Object.transformSource (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/build/webpack/loaders/next-flight-client-module-loader.js:34:17)\\n    at LOADER_EXECUTION (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4134)\\n    at runSyncOrAsync (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4145)\\n    at iterateNormalLoaders (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5782)\\n    at /tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5142\\n    at r.callback (/tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4039)\\n    at /tmp/next-install-97873450c45d402540bb2144561b73fe7fc9b2ebbb8d8e034b0a4a17b22934e0/node_modules/.pnpm/file+..+next-repo-309f91d6bf2b74a18caaad8557be95ff3c50e7320f5844b35e8793bb3cd875af+packages+n_aeb7o2ytmbwpic3vrica2g3hsi/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:166:23\"},\"gip\":true,\"scriptLoader\":[]}</script><div id=\"__next-build-watcher\" style=\"position: fixed; bottom: 10px; right: 20px; width: 0px; height: 0px; z-index: 99999;\"></div><next-route-announcer><p aria-live=\"assertive\" id=\"__next-route-announcer__\" role=\"alert\" style=\"border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: absolute; top: 0px; width: 1px; white-space: nowrap; overflow-wrap: normal;\"></p></next-route-announcer><nextjs-portal></nextjs-portal></body>"

      31 |     expect(
      32 |       await session.evaluate('document.documentElement.innerHTML')
    > 33 |     ).toContain('A few years ago I tweeted')
         |       ^
      34 |
      35 |     const pagePath = 'app/(post)/2020/develop-preview-test/page.mdx'
      36 |     const originalPage = await next.readFile(pagePath)

      at Object.toContain (development/acceptance-app/app-hmr-changes.test.ts:33:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ztanner — APPROVED** [review]

**Comment by khuezy** [comment]
Hoping this will resolve this too: https://github.com/vercel/next.js/issues/57622
Sounds like a similar problem.

**Comment by laugharn** [comment]
I'm pretty sure this PR is unfortunately leading to some libraries breaking. I put together minimal repro with @mux/mux-player-react here: https://github.com/laugharn/next-mux-repro

**Comment by jmeistrich** [comment]
This is also breaking Legend-State: https://github.com/LegendApp/legend-state/issues/222

Is there something we need to change in our bundling to be compatible with this?

**Comment by lukasIO** [comment]
minimal reproductions of the issue in https://github.com/vercel/next.js/issues/57962 and https://github.com/vercel/next.js/issues/58592

**Comment by LuisGilGB** [comment]
This addition also seemed to break apps that use [domino](https://www.npmjs.com/package/domino) (so, by extension, apps that use [turndown](https://www.npmjs.com/package/turndown) and, by extension of the latter, apps that use [remirror](https://www.npmjs.com/package/remirror)).

- [Sandbox](https://codesandbox.io/p/devbox/next-14-0-2-domino-build-error-bug-dylymw) to reproduce (builds break due to **`with` statements being used in strict mode**, the `sloppy.js` file at `domino` is where logic that must avoid JavaScrip's strict mode is encapsulated).

I've been trying and yes, the first canary release with this bug is `14.0.2-canary.1`. Still present at `14.0.4-canary.18`.

### Related stuff:
- Older bug, so strictly speaking not exactly the same thing; but might worth checking: #34796 
- Issue thread about the usage of `with` statements in `domino`: https://github.com/fgnass/domino/issues/153
