### ISSUE TITLE
next dev hangs forever (no error, no overlay) when a module request exceeds ~8.39M chars — bundled enhanced-resolve predates the non-regex fast path

### ISSUE THREAD

**Issue by MuzajsArcin** [vercel/next.js#97365]
### Link to the code that reproduces this issue

https://github.com/MuzajsArcin/nextjs-dev-hang-repro

(Refiling: #97364 was auto-closed and locked by the bot because the reproduction was inlined
in the body instead of linked as a repository. Same report, now with the repo.)

### To Reproduce

```bash
git clone https://github.com/MuzajsArcin/nextjs-dev-hang-repro
cd nextjs-dev-hang-repro && npm install
node generate.mjs        # writes src/big.mjs — one 13,280,481-char data: URI
npm run dev              # next dev -p 3247
curl --max-time 60 http://localhost:3247/
```

Pages Router, empty `next.config.mjs`, no custom webpack config. `src/big.mjs` is one line:

```js
export const wasmUrl = new URL("data:application/wasm;base64,AAAA…", import.meta.url).href;
```

## Current vs. Expected behavior

**Current:** compilation never finishes and the request never resolves. `curl` exits 28; the
browser spins indefinitely. The dev server prints only:

```
 ○ Compiling / ...
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
 ⨯ unhandledRejection: RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
```

**Expected:** either it compiles (Turbopack does, in ~1 s), or it fails with an error overlay
naming the module. A `RangeError` during compilation should not leave the request permanently
unresolved.

Two things make this unusually expensive to debug:

1. The single `at RegExp.exec` frame is **not** a truncated trace — the overflow is inside V8's
   regexp engine, so no JS frame points at the offending module. `--stack-trace-limit` does not
   help, and `--stack-size` does not either (tried up to 60 MB): this is V8's RegExp stack cap,
   not the JS call stack.
2. Because it surfaces as `unhandledRejection` rather than a compilation error, there is no
   overlay, no failed build, and no module path — just an infinite hang.

I only located it by preloading a patched `RegExp.prototype.exec` via `NODE_OPTIONS --require` and
logging `this.source` plus a fresh `new Error().stack` from inside the `catch` (the regexp frames
have unwound by then, so the caller chain is visible).

## Root cause

`parseIdentifier` in the bundled `enhanced-resolve` runs `PATH_QUERY_FRAGMENT_REGEXP` on **every**
module request. V8 throws `RangeError` once the subject exceeds its RegExp stack limit.

Bisected to the character on Node 22.23.2 / V8 12.4.254.21-node.56: the largest input that still
succeeds is **8,388,572** characters — 36 below 2^23 — identical for `"A".repeat(n)` and for a
`data:` URI of the same length.

The boundary is directly observable:

| request length | result |
|---|---|
| 8,388,572 | HTTP 500, ordinary error overlay |
| 8,388,573 | hangs forever |

**This is already fixed in `enhanced-resolve` itself.** Standalone 5.22.0 skips the regex unless
the identifier actually contains `\0`:

```js
const firstEscape = identifier.indexOf("\0");
if (firstEscape !== -1) { /* regex path */ }
// otherwise: linear indexOf scans, no regex at all
```

But `next/dist/compiled/webpack/bundle5.js` in 15.5.18 still carries the older version:

```js
const I=/^(#?(?:\0.|[^?#\0])*)(\?(?:\0.|[^#\0])*)?(#.*)?$/;
function parseIdentifier(v){const P=I.exec(v); ... }
```

(No `firstEscape`, no `dosPrefixEnd` — confirmed by string-searching the bundle.)

Driving webpack 5.107.2 + enhanced-resolve 5.22.0 through the Node API over the identical
generated module: **0 errors, build completes.** So plain webpack is fine; only Next's vendored
copy is affected.

## Suggested fixes

1. **Refresh the bundled `enhanced-resolve`** in `next/dist/compiled/webpack` to a version with
   the `\0` fast path. This alone removes the failure.
2. **Do not let a compiler `RangeError` become an infinite hang.** Even after (1), any future
   `unhandledRejection` inside compilation should reject the pending request with an error overlay
   rather than leaving it open forever. This is the part that cost the most debugging time.

## Where this came from (not synthetic)

`@mlightcad/cad-simple-viewer` ships an Emscripten `SINGLE_FILE=1` worker
(`dist/libredwg-parser-worker.js`) with a ~10 MB `.wasm` inlined as
`new URL("data:application/wasm;base64,…", import.meta.url)`. Any Next.js app that pulls that
package into a route's module graph loses `next dev` for that route entirely. In our app three
route families died at once; `next build --turbopack` stayed green the whole time, which made it
look like an app bug rather than a toolchain one.

## Environment

- Next.js **15.5.18** (webpack dev; `--turbopack` unaffected in both `dev` and `build`)
- Node **22.23.2**, V8 12.4.254.21-node.56
- macOS 26.6.1, arm64
- Reproduced on a clean checkout with an empty `next.config.mjs` (no custom webpack config)
