### ISSUE TITLE
[examples/with-redux-wrapper] doesn't work with "next-redux-wrapper": "7.0.2"

### ISSUE THREAD

**Issue by frozar** [vercel/next.js#26338]
### What example does this report relate to?

with-redux-wrapper

### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Google Chrome

### What operating system are you using?

Linux Ubuntu 18.04

### How are you deploying your application?

Vercel

### Describe the Bug

From the directory `examples/with-redux`, I installed the latest version available of `next-redux-wrapper`, 7.0.2, as I begin to use it in my main project. After npm installation step, I launch the example `npm run dev`.
Compilation seems to work, but as soon as I look at the page through google chrome, I got the following error:
```
TypeError: nextCallback is not a function
    at /home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:146:46
    at step (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:57:23)
    at Object.next (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:38:53)
    at /home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:32:71
    at new Promise (<anonymous>)
    at __awaiter (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:28:12)
    at makeProps (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:135:16)
    at /home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:186:46
    at step (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:57:23)
    at Object.next (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:38:53)
(node:22955) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dispatch' of undefined
    at eval (webpack-internal:///./pages/index.js:47:9)
    at /home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:143:52
    at step (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:57:23)
    at Object.next (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:38:53)
    at /home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:32:71
    at new Promise (<anonymous>)
    at __awaiter (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:28:12)
    at makeProps (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:135:16)
    at /home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:186:46
    at step (/home/frozar/wk/next.js/examples/with-redux-wrapper/node_modules/next-redux-wrapper/lib/index.js:57:23)
(node:22955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

### Expected Behavior

I expect to be able to see the example page. The example works correctly with previous version of `next-redux-wrapper`, 6.0.2

### To Reproduce

From `examples/with-redux-wrapper` directory, update `next-redux-wrapper`:
```
npm i next-redux-wrapper@^7.0.0
```
Launch the example:
```
npm run dev
```
Look at the page in a browser.

**Comment by ThangHuuVu** [comment]
Hello, I'd like to take this as my first next.js contribution

**Comment by Jashnm** [comment]
Hey, The way `next-redux-wrapper` is used version 7 onwards is different from 6x. 
You can follow the migration steps from here - [Upgrade from 6.x to 7.x](https://github.com/kirill-konshin/next-redux-wrapper#upgrade-from-6x-to-7x)  

I tried reproducing the error and 3rd step from migration steps solved it for me- 
> All signatures like ({store, req, res, ...}) => { ... } were changed to store => ({req, res, ...}) => { ... } in order to keep Next.js internals free of modifications and for better typings support.

@timneutkens should I update the example [with-redux-wrapper](https://github.com/vercel/next.js/tree/canary/examples/with-redux-wrapper) with the latest changes in `next-redux-wrapper` ?

**Comment by leerob** [comment]
Fixed with https://github.com/vercel/next.js/pull/26521

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
