### ISSUE TITLE
Next won't run after update to v11 using yarn dev

### ISSUE THREAD

**Issue by WillPwn4Food** [vercel/next.js#26203]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

16.3

### What browser are you using?

chrome

### What operating system are you using?

Windows 8

### How are you deploying your application?

yarn dev

### Describe the Bug

I've tested in two completely separate nextJS apps that worked fine prior to updating to the latest NextJS version.

Here is what the console pumps out on 'yarn dev':

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from D:\GitHub\ProjectName\.env.development
info  - Loaded env from D:\GitHub\ProjectName\.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
error - ./node_modules/next/dist/client/dev/amp-dev.js
SyntaxError: Unexpected token / in JSON at position 76
    at JSON.parse (<anonymous>)
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./node_modules/next/dist/client/dev/amp-dev.js
SyntaxError: Unexpected token / in JSON at position 76
    at JSON.parse (<anonymous>)
Error: Cannot find module 'D:\GitHub\ProjectName\.next\server\pages-manifest.json'
Require stack:
- D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\require.js
- D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\load-components.js
- D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\api-utils.js
- D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\next-server.js
- D:\GitHub\ProjectName\node_modules\next\dist\server\next.js
- D:\GitHub\ProjectName\node_modules\next\dist\server\lib\start-server.js
- D:\GitHub\ProjectName\node_modules\next\dist\cli\next-dev.js
- D:\GitHub\ProjectName\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.mod._resolveFilename (D:\GitHub\ProjectName\node_modules\next\dist\build\webpack\require-hook.js:4:1855)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at getPagePath (D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\require.js:1:735)
    at requirePage (D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\require.js:1:1397)
    at loadComponents (D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\load-components.js:1:1289)
    at DevServer.findPageComponents (D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\next-server.js:77:296)
    at DevServer.renderErrorToHTML (D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\next-server.js:139:209) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\next-server\\server\\require.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\next-server\\server\\load-components.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\next-server\\server\\api-utils.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\next-server\\server\\next-server.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\server\\next.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\cli\\next-dev.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\bin\\next'
  ]
}
Error: Cannot find module 'D:\GitHub\ProjectName\.next\fallback-build-manifest.json'
Require stack:
- D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\load-components.js
- D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\api-utils.js
- D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\next-server.js
- D:\GitHub\ProjectName\node_modules\next\dist\server\next.js
- D:\GitHub\ProjectName\node_modules\next\dist\server\lib\start-server.js
- D:\GitHub\ProjectName\node_modules\next\dist\cli\next-dev.js
- D:\GitHub\ProjectName\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.mod._resolveFilename (D:\GitHub\ProjectName\node_modules\next\dist\build\webpack\require-hook.js:4:1855)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at loadDefaultErrorComponents (D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\load-components.js:1:652)
    at DevServer.renderErrorToHTML (D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\next-server.js:139:962)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.render (D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\next-server.js:75:160)
    at async Object.fn (D:\GitHub\ProjectName\node_modules\next\dist\next-server\server\next-server.js:58:672) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\next-server\\server\\load-components.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\next-server\\server\\api-utils.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\next-server\\server\\next-server.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\server\\next.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\cli\\next-dev.js',
    'D:\\GitHub\\ProjectName\\node_modules\\next\\dist\\bin\\next'
  ]
}

This just repeats over and over and the browser just displays "Internal Server Error"

### Expected Behavior

I expect it to run as usual and load pages

### To Reproduce

yarn add next@latest react@latest react-dom@latest
yarn dev

**Comment by dareiff** [comment]
I had to do a bit of work to get this going as well. I ended up removing the version of next|vercel in my homebrew/node/npm directory, then everything went back to normal.

**Comment by Cow258** [comment]
To resolve this issue, I did the following things
### Modify `next.config.js`
```js
// Added the follow configs into next.config.js
module.exports = {
  cleanDistDir: false,
  images: {
    disableStaticImages: true,
  },
}
```
### Run command
```sh
yarn global remove create-next-app
yarn cache clean -f
rm -rf .next
rm -rf node_modules
rm yarn.lock
yarn
yarn add --dev eslint-config-next
yarn build
yarn dev
```

**Comment by WillPwn4Food** [comment]
> 
> 
> To resolve this issue, I did the following things
> ### Modify `next.config.js`
> 
> ```js
> // Added the follow configs into next.config.js
> module.exports = {
>   cleanDistDir: false,
>   images: {
>     disableStaticImages: true,
>   },
> }
> ```
> 
> ### Run command
> 
> ```shell
> yarn global remove create-next-app
> yarn cache clean -f
> rm -rf .next
> rm -rf node_modules
> rm yarn.lock
> yarn
> yarn add --dev eslint-config-next
> yarn build
> yarn dev
> ```

Hey, I gave this a shot, but unfortunately had the same results :(

I've found if I update my "next.config.js" file to have "webpack5: false," it will load and work again at least...

**Comment by ashwinvandijk** [comment]
Confirmed, none of the solutions given work, except using webpack 4 using @WillPwn4Food's answer.

**Comment by MaximeBernard** [comment]
Sounds like a duplicate of https://github.com/vercel/next.js/issues/26132

**Comment by jwilsson** [comment]
This sounds like the same issue as #26163. A possible fix is out in `v11.0.1-canary.2`.

**Comment by timneutkens** [comment]
Duplicate of #26163

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
