### ISSUE TITLE
Styled-components broken in 14.0.0

### ISSUE THREAD

**Issue by stychu** [vercel/next.js#57584]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/solitary-architecture-j3rg3n

### To Reproduce

Sandbox show an error about styled-components on NextJs 14.0.0 where on 13.5.6 it works no problem. 
```
> next dev

   ▲ Next.js 14.0.0
   - Local:        http://localhost:3000

 ✓ Ready in 1507ms
 ○ Compiling /page ...
 ✓ Compiled /page in 4.5s (641 modules)
 ⨯ node_modules/.pnpm/react95@4.0.0_react-dom@18.2.0_react@18.2.0_styled-components@5.3.11/node_modules/react95/dist/Anchor/Anchor.mjs (4:27) @ eval
 ⨯ TypeError: styled_components__WEBPACK_IMPORTED_MODULE_1__.a is not a function
    at __webpack_require__ (.../.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (.../.next/server/webpack-runtime.js:33:42)
    at eval (./app/_components/Moni.tsx:7:65)
    at (ssr)/./app/_components/Moni.tsx (.../.next/server/app/page.js:173:1)
    at __webpack_require__ (.../.next/server/webpack-runtime.js:33:42)
null
 ✓ Compiled /favicon.ico/route in 415ms (351 modules)
```

### Current vs. Expected behavior

I expect that styled-components work the same on 14.0.0 as they work on 13.5.6.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.9.2
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

My original problem occurred in private repo with custom styled-component libray which I can't share so I tried with any other public styled-component UI lib. 

> After upgrade to the NextJS 14.0.0 from 13.5.6 I immediately noticed that my root page does (FOUC, or flash of unstyled text). I'm using styled-components with this setup [styled-component-nextjs](https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-components) and it works fine with 13.5.6 but 14.0.0 gives FOUC right off the bat :(

Although I don't see any error within my private repo I can clearly see that something is broken with styled components with 14.0.0 as FOUC appears. On top of that my build increases by few kB just by updating to 14.0.0.

----
## NextJs 13.5.6 (Working) 
1. Build Size - ok
2. 2 Layout Renders - ok
3. StyledComponentRegistry in call tree - ok
4. globals.css present - ok
5. e.generateAndInjectStyles has some secondaryStyles - ok

![Screenshot 2023-10-27 at 00 32 50](https://github.com/vercel/next.js/assets/9383657/fa13fabc-6ca6-4b5c-9057-a4195a8c431b)
<img width="894" alt="Screenshot 2023-10-27 at 11 54 17" src="https://github.com/vercel/next.js/assets/9383657/9fb5c303-4222-4022-bb6a-4041041c77b3">
![Screenshot 2023-10-27 at 00 21 49](https://github.com/vercel/next.js/assets/9383657/e8bdde46-3001-4c04-8f5f-7f668816f1be)

----
## NextJs 14.0.0 (NOT Working) 
1. Build Size - not ok (increase)
2. 3 Layout Renders - not ok -  FOUC (previously 2 )
3. StyledComponentRegistry NOT in call tree - not ok (NO styledcomponentrregistry)
4. globals.css NOT present - not ok
5. e.generateAndInjectStyles NO secondaryStyles - not ok

![Screenshot 2023-10-27 at 00 31 14](https://github.com/vercel/next.js/assets/9383657/34c453a5-0041-4a72-ab7b-b3a4f7c6844b)

<img width="935" alt="Screenshot 2023-10-27 at 11 54 34" src="https://github.com/vercel/next.js/assets/9383657/7cf360e8-8db4-44d8-bbd8-9fd960759063">

<img width="1633" alt="Screenshot 2023-10-27 at 00 22 17" src="https://github.com/vercel/next.js/assets/9383657/58e0cf41-15e6-4d4c-b74d-462220b9bbea">

<sub>[NEXT-1702](https://linear.app/vercel/issue/NEXT-1702/styled-components-broken-in-1400)</sub>

**Comment by mryechkin** [comment]
I'm also seeing FOUC now after upgrading to `14.0`. Rolling back to `13.5.6` fixes the issue with no other code changes.

**Comment by huozhi** [comment]
This fix is landed in the latest canary [v14.0.2-canary.1](https://github.com/vercel/next.js/releases/tag/v14.0.2-canary.1)
