### ISSUE TITLE
[ESLint v10]: TypeError: contextOrFilename.getFilename is not a function when running ESLint v10

### ISSUE THREAD

**Issue by bennajah** [vercel/next.js#89764]
### Link to the code that reproduces this issue

https://github.com/bennajah/nextjs16

### To Reproduce

1. Create a `next.js` project or clone this repo
2. Upgrade `eslint` to v10 .
3. Run `eslint` 

### Current vs. Expected behavior

After upgrading ESLint to v10 in a Next.js project, running bun eslint causes the following error:

```PS
PS C:\Users\benna\dev\my-app> bun lint
$ eslint

Oops! Something went wrong! :(

ESLint: 10.0.0

TypeError: Error while loading rule 'react/display-name': contextOrFilename.getFilename is not a function
Occurred while linting C:\Users\benna\dev\my-app\app\layout.tsx
    at resolveBasedir (C:\Users\benna\dev\my-app\node_modules\eslint-plugin-react\lib\util\version.js:31:100)
    at detectReactVersion (C:\Users\benna\dev\my-app\node_modules\eslint-plugin-react\lib\util\version.js:85:19)
    at getReactVersionFromContext (C:\Users\benna\dev\my-app\node_modules\eslint-plugin-react\lib\util\version.js:116:25)
    at testReactVersion (C:\Users\benna\dev\my-app\node_modules\eslint-plugin-react\lib\util\version.js:181:28)
    at usedPropTypesInstructions (C:\Users\benna\dev\my-app\node_modules\eslint-plugin-react\lib\util\usedPropTypes.js:307:36)
    at Components.componentRule (C:\Users\benna\dev\my-app\node_modules\eslint-plugin-react\lib\util\Components.js:940:37)
    at createRuleListeners (C:\Users\benna\dev\my-app\node_modules\eslint\lib\linter\linter.js:497:15)
    at C:\Users\benna\dev\my-app\node_modules\eslint\lib\linter\linter.js:623:7
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\benna\dev\my-app\node_modules\eslint\lib\linter\linter.js:557:31)
```

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 12244
  Available CPU cores: 8
Binaries:
  Node: 24.13.0
  npm: 11.6.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 16.1.6 // Latest available version is detected (16.1.6).
  eslint-config-next: N/A
  react: 19.2.4
  react-dom: 19.2.4
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Linting

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

**Comment by simonhudson** [comment]
Also seeing same error for `react/no-direct-mutation-state` rule when running Lint in GH actions

<img width="988" height="130" alt="Image" src="https://github.com/user-attachments/assets/6579fe7a-b094-4734-a20e-f04bd30ecd9e" />

**Comment by jWytrzes** [comment]
Same here and also same with `react/no-direct-mutation-state` as mentioned

EDIT: And when I turn off both of them it changes to `react/no-render-return-value`, so probably it can go on like that

**Comment by OscarGauss** [comment]
**Temporary Fix for ESLint v10:**
This error happens because `eslint-plugin-react` (a dependency of `eslint-config-next`) uses the legacy `context.getFilename()` API for version auto-detection, which was removed in **ESLint v10**.
To fix this, you must explicitly define your React version in your `eslint.config.mjs` settings to bypass the auto-detection logic.
I've created a Gist with the corrected configuration for **Next.js + ESLint 10**: ["Next.js ESLint v10 Fix"](https://gist.github.com/OscarGauss/1f305edf5b7c103bb2ee32ba479f4261)
**Key change:**
```javascript
{
  settings: {
    react: { version: "19" } // Avoids auto-detection crash
  }
}
```

**Comment by t6adev** [comment]
It should be work for some cases.
https://www.npmjs.com/package/@eslint/compat

**Comment by bonesoul** [comment]
also having the issue here.

_Edit by maintainer bot: Comment was **automatically** minimized because it was considered unhelpful. (If you think this was by mistake, let us know). Please only comment if it adds context to the issue. If you want to express that you have the same problem, use the upvote 👍 on the issue description or subscribe to the issue for updates. Thanks!_

**Comment by la3rence** [comment]
Anyone see this issue with ESLint 10? The gist up above doesn't work for it.

> TypeError: scopeManager.addGlobals is not a function

**Comment by jonas-is-coding** [comment]
This is an ESLint 10 compatibility issue rather than a project-specific configuration problem. In the current state,  still depends on  behavior that assumes APIs changed in ESLint 10, which is why errors move between rules like , , and then other internals. For stable CI, the reliable option today is to pin ESLint to v9 when using . If ESLint 10 is required, the only consistent path is a fully custom flat config that does not depend on  until upstream compatibility is complete.

**Comment by jonas-is-coding** [comment]
Correction with exact package names:

This is an ESLint 10 compatibility issue rather than a project-specific configuration problem. In the current state, `eslint-config-next` still depends on `eslint-plugin-react` behavior that assumes APIs changed in ESLint 10, which is why errors move between rules like `react/display-name`, `react/no-direct-mutation-state`, and then other internals. For stable CI, the reliable option today is to pin ESLint to v9 when using `eslint-config-next`. If ESLint 10 is required, the only consistent path is a fully custom flat config that does not depend on `eslint-config-next` until upstream compatibility is complete.

**Comment by psychobolt** [comment]
@la3rence 

> Anyone see this issue with ESLint 10? The gist up above doesn't work for it.
> 
> > TypeError: scopeManager.addGlobals is not a function

That error is most likely JS parser. Are you using TypeScript or JavaScript ? 

For me, workaround is to import the TypeScript [config](https://nextjs.org/docs/app/api-reference/config/eslint#with-typescript) and manually set React version as suggested.

Maybe someone else can chime in on a solution for JavaScript only setup, but I think a proper patch would be ideal.

**Comment by NishargShah** [comment]
Guys, any update? For ESLint 10?

**Comment by engPabloMartinez** [comment]
is it planned to have support for eslint v10 in the next release? in eslint-config-next e.g. ?

**Comment by christopherjohnson3028-stack** [comment]
It does have support check it out

**Comment by nadiatazi262-tech** [comment]
Any updates u guys

**Comment by icyJoseph** [comment]
Looks very much like an upstream issue. I'll keep it open as per:

- https://github.com/jsx-eslint/eslint-plugin-react/issues/3977

Looks like this PR https://github.com/jsx-eslint/eslint-plugin-react/pull/3979 might land the fix upstream. If that lands and gets published, we shall re-evaluate here, and close this issue if that fixes the problem through Next.js' side.

- https://github.com/vercel/next.js/pull/90068

Not sure about this PR either, I rather see an upstream fix merged and published first.

**Comment by hyuntnchoi** [comment]
I removed `eslint-config-next` and added `@next/eslint-plugin-next` and the error was fixed
see [relevant doc](https://nextjs.org/docs/app/api-reference/config/eslint#using-the-plugin-directly)

**Comment by samfortunato** [comment]
doesn't fix the issue with eslint 10, but for anyone coming to here looking for a fix, i just downgraded to eslint v`9.39.4`, and it worked for me. pretty sure i'm on next v`16.0.10`.

```json
"devDependencies": {
  "eslint": "^9.39.4",
  "eslint-config-next": "^16.2.2"

  // ...
```

**Comment by GentryRiggen** [comment]
Confirming this still reproduces on `eslint-config-next@16.2.4` + `eslint@10.3.0` via `eslint-plugin-react@7.37.5`. We've deferred our ESLint v10 bump and stayed on `eslint@9.39.4` while waiting for jsx-eslint/eslint-plugin-react#3979 to land. Subscribing for the close.

**Comment by 314systems** [comment]
https://github.com/eslint/eslint/pull/20869

Why not switch to [@eslint-react/eslint-plugin](https://github.com/rel1cx/eslint-react)?

**Comment by raihannismara** [comment]
> **Temporary Fix for ESLint v10:** This error happens because `eslint-plugin-react` (a dependency of `eslint-config-next`) uses the legacy `context.getFilename()` API for version auto-detection, which was removed in **ESLint v10**. To fix this, you must explicitly define your React version in your `eslint.config.mjs` settings to bypass the auto-detection logic. I've created a Gist with the corrected configuration for **Next.js + ESLint 10**: ["Next.js ESLint v10 Fix"](https://gist.github.com/OscarGauss/1f305edf5b7c103bb2ee32ba479f4261) **Key change:**
> 
> {
>   settings: {
>     react: { version: "19" } // Avoids auto-detection crash
>   }
> }

works like a charm!

**Comment by lusu007** [comment]
@icyJoseph ESLint 9 reaches end of life on August 6, 2026, so users relying on `eslint-config-next` will be left without a supported ESLint version next week (https://eslint.org/version-support/).

What is the current plan for resolving the ESLint 10 compatibility issues? Given the approaching EOL date, this should be escalated and prioritized to avoid forcing users to remain on an unsupported ESLint release.

**Comment by icyJoseph** [comment]
Hi, @lusu007 - I'd love to resolve this issue too. It is one of the most reacted ones. 

From my notes, we still need https://github.com/jsx-eslint/eslint-plugin-react/pull/3979 to land, right?

We considered kind of applying the workaround at the top, but that's probably not a good idea.

**Comment by lusu007** [comment]
Thanks for the response @icyJoseph. Yes, `jsx-eslint/eslint-plugin-react#3979` seems to be the immediate blocker.

However, this also highlights a broader dependency and governance problem: critical tooling used by projects like Next.js can be blocked by a very small number of external maintainers. With ESLint 9 reaching EOL next week, is there anything the Next.js team could do to help move this forward or provide some guidance on a fallback?

It may also be worth considering a more resilient long-term approach, since a similar situation could otherwise arise again with a future breaking ESLint release.

**Comment by icyJoseph** [comment]
@lusu007 IIRC, the workaround from https://github.com/vercel/next.js/issues/89764#issuecomment-3928272828 should do the trick? You can take ESLint 10, and prevent the version auto detection branch from crashing?

**Comment by mmilanovic4** [comment]
For JavaScript-only projects the `settings.react.version` pin isn't enough on its own — linting still fails before reaching the react rules:

```
TypeError: scopeManager.addGlobals is not a function
    at addDeclaredGlobals (eslint/lib/languages/js/source-code/source-code.js:221:15)
```

`eslint-config-next` parses JS/JSX with Next's bundled `@babel/eslint-parser` (exposed as `eslint-config-next/parser`), whose scope manager predates ESLint 10's `ScopeManager#addGlobals`. TypeScript projects don't hit it because `eslint-config-next/typescript` swaps in `@typescript-eslint/parser`.

Overriding both works on `eslint@10.8.0` / `eslint-config-next@16.2.12`:

```js
import tsParser from "@typescript-eslint/parser";
import nextVitals from "eslint-config-next/core-web-vitals";

export default [
  ...nextVitals,
  {
    languageOptions: {
      parser: tsParser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    settings: {
      react: { version: "19" },
    },
  },
];
```

Needs `@typescript-eslint/parser@>=8.65.0` — the first version declaring `eslint: ^10` in its peer range. Caveat: this drops Babel parsing for JS files, so `next/babel`-specific syntax would no longer parse.

To be clear, this is a stopgap and not something anyone should have to keep in their config long-term — I'm posting it mainly so JS projects aren't blocked in the meantime. Hoping `eslint-config-next` can support ESLint 10 out of the box once jsx-eslint/eslint-plugin-react#3979 lands.

**Comment by KeroZelvin** [comment]
Confirming the two-part workaround above in a mixed JavaScript/TypeScript production app:

- Node `24.18.1`, npm `11.16.0`, `next` / `eslint-config-next` `16.2.12`, and ESLint `10.8.0`.
- Pinning `settings.react.version` to `"19"` cleared the initial `contextOrFilename.getFilename` crash, but JavaScript and MJS files then failed at `scopeManager.addGlobals`.
- Adding `@typescript-eslint/parser@8.65.0` only for `**/*.{js,mjs,cjs,jsx}` fixed that second failure while leaving the TypeScript parser configuration intact.
- A clean `npm ci`, full lint, `tsc --noEmit`, `next build`, and the complete CI suite all passed; the same artifact completed its production release checks.

The scoped override is important for mixed projects; applying the parser globally can unnecessarily replace the TypeScript config inherited from `eslint-config-next/typescript`.

One remaining caveat: npm still reports ESLint peer-range warnings from the bundled React, import, and jsx-a11y plugins. They did not block this release, but this is still a stopgap rather than out-of-the-box ESLint 10 support.

**Comment by cbartens** [comment]
Adding a workaround for the reported crash, plus a second blocker that sits behind it.

## Workaround for `contextOrFilename.getFilename is not a function`

`eslint-config-next` sets `settings.react.version = 'detect'` (`dist/index.js:143`). `eslint-plugin-react` only calls `detectReactVersion()` when the configured version is literally the string `'detect'` (`lib/util/version.js:113-116`), and that is the path that reaches the removed `context.getFilename()` (`version.js:31`).

Pinning an explicit version after the config spread skips that branch entirely:

```js
// eslint.config.js
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";

export default [
  ...nextCoreWebVitals,
  { settings: { react: { version: "19.2.4" } } }, // your React version
];
```

Confirmed on **eslint 10.8.1** + **eslint-config-next 16.3.0** + React 19.2.4: the `react/display-name` / `getFilename` error no longer occurs.

## But this is not a full fix — a second blocker follows

With the above applied, linting fails at the next step:

```
TypeError: scopeManager.addGlobals is not a function
    at addDeclaredGlobals (eslint/lib/languages/js/source-code/source-code.js:221:15)
    at SourceCode.finalize (source-code.js:1090:3)
```

ESLint 10 calls `scopeManager.addGlobals()` whenever a config declares `languageOptions.globals` under a custom parser. `eslint-config-next` declares **1174 globals**, so this always fires.

The parser is Next's own:

```
$ npx eslint --print-config <file>
parser: eslint-config-next/parser@16.2.10
```

```js
// eslint-config-next/dist/parser.js
var _eslintparser = require("next/dist/compiled/babel/eslint-parser");
```

`addGlobals` appears **0 times** in `next/dist/compiled/babel/eslint-parser`.

## Why this points at the vendored Babel version

Babel has addressed this directly and ruled out a Babel 7 fix:

- [babel/babel#17934](https://github.com/babel/babel/issues/17934) — *"Babel 7 will not support ESLint 10."*
- [babel/babel#17804](https://github.com/babel/babel/issues/17804) — *"For now you can try Babel 8.0.0-rc.2"*

Both closed as duplicates pointing to Babel 8.

So `eslint-config-next` appears blocked on Next vendoring **Babel 8's** `@babel/eslint-parser`, independent of the `eslint-plugin-react` issue in the title.

For reference, this is not typescript-eslint: `@typescript-eslint/scope-manager` implements `addGlobals` (`dist/ScopeManager.js:106`) since ~8.55.0, per [typescript-eslint#11762](https://github.com/typescript-eslint/typescript-eslint/issues/11762).

## Scope

In a pnpm monorepo, only the Next app is affected — packages using a plain typescript-eslint flat config (no `globals` block) lint clean on eslint 10.8.1. So this is isolated to `eslint-config-next`, not a general ESLint 10 migration problem.

**Comment by nanduxdev** [comment]
Got the same error reacr/display-name:
Oops! Something went wrong! :(

ESLint: 10.10.0

TypeError: Error while loading rule 'react/display-name': contextOrFilename.getFilename is not a function
Occurred while linting /Users/nandannagane/Desktop/skill-trail/app/auth/layout.tsx
