### ISSUE TITLE
(App Router) Higher order function component support

### ISSUE THREAD

**Issue by garronej** [vercel/next.js#44307]
Hello next pepoles :)  

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```raw
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:36 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6020
  Available memory (MB): 65536
  Available CPU cores: 12
Binaries:
  Node: 22.12.0
  npm: 10.9.0
  Yarn: 1.22.22
  pnpm: 9.15.3
Relevant Packages:
  next: 15.1.4 // Latest available version is detected (15.1.4).
  eslint-config-next: 11.0.1
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 4.9.4
Next.js Config:
  output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/garronej/mui-next-appdir-demo/tree/higher_order_function_component

### To Reproduce

```bash
git clone https://github.com/garronej/mui-next-appdir-demo
cd mui-next-appdir-demo
git checkout higher_order_function_component
yarn
yarn dev
```

### Describe the Bug

Can't use higher order functions that returns components like:  

```tsx
"use client";

export function createMyComponent() {

	function MyComponent() {

		return <h1>Hello World</h1>;

	}

	return { MyComponent };

}
```

We get:  
```raw
Server Error
TypeError: (0 , _shared_MyComponent__WEBPACK_IMPORTED_MODULE_2__.createMyComponent) is not a function
```  

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/6702424/209359022-f5985294-b2d5-4f6f-8e93-0e22f2d570b2.png">

### Expected Behavior

I would expect it to work as it makes it impossible to make existing API compatible with AppDir without introducing breaking changes.  

Thank you for your work!

**Comment by TillHeinzel** [comment]
In this particular case, shouldn't it be
```
"use client";

export function createMyComponent() {

	function MyComponent() {

		return <h1>Hello World</h1>;

	}

	return <MyComponent />;

}
```
?

This way it would be an actual component being returned, right?

**Comment by garronej** [comment]
Hello @TillHeinzel,  

No this isn't the usecase.  

 ```tsx
 "use client";

export function createMyComponent() {

	function MyComponent() {

		return <h1>Hello World</h1>;

	}

	return { MyComponent };

}
 ```
is to be used like:   
```tsx
// app/pages.tsx  

import React from "react";
import { createMyComponent } from "../shared/MyComponent";

const { MyComponent } = createMyComponent();

function DefaultPage() {
  return (
    <>
      <MyComponent />
    </>
  );
}

export default DefaultPage;
```

**Comment by lelabo-m** [comment]
I second this issue as I already mentioned this problem in an other issue #44030 about compound components.

**Comment by garronej** [comment]
This is still not working in 15.1.
I updated the reproduction repo.   

![image](https://github.com/user-attachments/assets/99177ae3-d104-4464-b51a-9e3daf6e985c)

**Comment by marcoshernanz** [comment]
Thanks for the report. This is expected React Server Components behavior. `createMyComponent` is exported from a `"use client"` module, so a Server Component receives a client reference and cannot invoke it on the server. This is the same boundary behavior explained in #44030. Call the factory inside a Client Component, or remove `"use client"` if the factory can run on the server. Closing as a duplicate of #44030.
