### ISSUE TITLE
Next 9.4.3 - Error: Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by frankn11** [vercel/next.js#13480]
# Bug report

After updating my project to the new release, I'm unable to start a dev server and end up with an error. It was working perfectly with the 9.4.2 release.

## Describe the bug

After running the `npm run dev`, I'm getting this error in my ternimal:

```
Error: Cannot find module 'fs-extra'
Require stack:
- /Users/franknoel/Dev/freelance/Global/node_modules/next/dist/lib/verifyTypeScriptSetup.js
- /Users/franknoel/Dev/freelance/Global/node_modules/next/dist/server/next-dev-server.js
- /Users/franknoel/Dev/freelance/Global/node_modules/next/dist/server/next.js
- /Users/franknoel/Dev/freelance/Global/node_modules/next/dist/server/lib/start-server.js
- /Users/franknoel/Dev/freelance/Global/node_modules/next/dist/cli/next-dev.js
- /Users/franknoel/Dev/freelance/Global/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/franknoel/Dev/freelance/Global/node_modules/next/dist/lib/verifyTypeScriptSetup.js:1:125)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/franknoel/Dev/freelance/Global/node_modules/next/dist/lib/verifyTypeScriptSetup.js',
    '/Users/franknoel/Dev/freelance/Global/node_modules/next/dist/server/next-dev-server.js',
    '/Users/franknoel/Dev/freelance/Global/node_modules/next/dist/server/next.js',
    '/Users/franknoel/Dev/freelance/Global/node_modules/next/dist/server/lib/start-server.js',
    '/Users/franknoel/Dev/freelance/Global/node_modules/next/dist/cli/next-dev.js',
    '/Users/franknoel/Dev/freelance/Global/node_modules/next/dist/bin/next'
  ]
}
```

## To Reproduce

Update Next.js to 9.4.3 with NPM. 
See the additionnal context section for my `package.json`.

## Expected behavior

The `npm run dev` command should start a dev server without any issue.

## System information

- OS: macOS
- Version of Next.js: 9.4.3
- Version of Node.js: 12.14.0

## Additional context

Here's my `package.json`:

```
...
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "François Noël",
  "license": "ISC",
  "dependencies": {
    "@brainhubeu/react-carousel": "^1.15.5",
    "@madebyconnor/rich-text-to-jsx": "^2.1.3",
    "clsx": "^1.1.0",
    "contentful": "^7.14.4",
    "formik": "^2.1.4",
    "google-map-react": "^1.1.7",
    "lodash": "^4.17.15",
    "next": "^9.4.3",
    "next-seo": "^4.5.0",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-google-recaptcha": "^2.0.1",
    "react-select": "^3.1.0",
    "react-svg": "^11.0.23",
    "react-use-media": "^0.3.0",
    "sass": "^1.26.5"
  },
  "devDependencies": {}
...
```

**Comment by frankn11** [comment]
If necessary, I can also provide the complete `npm` log file.

**Comment by Timer** [comment]
Duplicate of #13479, sorry about this. Getting a new release on npm immediately.

Please downgrade to `9.4.2` for now! Will be fixed in `9.4.4` in ~20 minutes.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
