### ISSUE TITLE
[regression] "'useContext' is not exported from 'react'" error message in latest canary, works fine in v14.1.0

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#62187]
### Link to the code that reproduces this issue

https://github.com/stefanprobst/issue-next-browserslist

### To Reproduce

1. clone repo, `pnpm install`
2. `pnpm run build`
3. see compilation error message:

```
./node_modules/.pnpm/next@14.1.1-canary.58_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/client/components/navigation.js
Attempted import error: 'useContext' is not exported from 'react' (imported as 'useContext').

Import trace for requested module:
./node_modules/.pnpm/next@14.1.1-canary.58_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/client/components/navigation.js
./node_modules/.pnpm/next@14.1.1-canary.58_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/api/navigation.js
./node_modules/.pnpm/next-intl@3.7.0_next@14.1.1-canary.58_react@18.2.0/node_modules/next-intl/dist/esm/server/react-server/RequestLocale.js
./node_modules/.pnpm/next-intl@3.7.0_next@14.1.1-canary.58_react@18.2.0/node_modules/next-intl/dist/esm/server.react-server.js
./app/[locale]/opengraph-image.tsx
./node_modules/.pnpm/next@14.1.1-canary.58_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-metadata-route-loader.js?page=%2F%5Blocale%5D%2Fopengraph-image%2Froute&isDynamic=1!./app/[locale]/opengraph-image.tsx?__next_metadata_route__
./node_modules/.pnpm/next@14.1.1-canary.58_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2F%5Blocale%5D%2Fopengraph-image%2Froute&page=%2F%5Blocale%5D%2Fopengraph-image%2Froute&pagePath=private-next-app-dir%2F%5Blocale%5D%2Fopengraph-image.tsx&appDir=%2Fdata%2FDevelopment%2Fplayground%2F__tmp%2Fissue-next-browserslist%2Fapp&appPaths=%2F%5Blocale%5D%2Fopengraph-image&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/[locale]/opengraph-image.tsx?__next_edge_ssr_entry__
```

### Current vs. Expected behavior

- when using the latest stable *version 14.1.0* there is no error message, see [this branch](https://github.com/stefanprobst/issue-next-browserslist/tree/latest-stable) in the issue reproduction
- when *not* using the edge runtime [here]() i also don't see an error message
- also not sure if this is a warning or error message (as `next build` does complete)

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.15.3
Relevant Packages:
  next: 14.1.1-canary.58 // Latest available version is detected (14.1.1-canary.58).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local)

<sub>[NEXT-2519](https://linear.app/vercel/issue/NEXT-2519/[regression]-usecontext-is-not-exported-from-react-error-message-in)</sub>

**Comment by huozhi** [comment]
You're using notFound API from `next/navigation` in `i18n.ts`, seems like that file is also going to be used for og image. But og image are basically the app route where we're using `react-server` condition, and should return a 404 response for responding "not found" instead of call `notFound`() API. If you comment out that API it works well.

**Comment by stefanprobst** [comment]
thanks for investigating! to clarify, v14.1.0 not showing that error message was actually incorrect?

**Comment by stefanprobst** [comment]
also not sure what you are suggesting to comment out -- when removing `notFound()` (like [here](https://github.com/stefanprobst/issue-next-browserslist/commit/5b5a8448c8922ebab3b6d8e209a0074730fbc71e)) is still see the same error message.

**Comment by steven-tey** [comment]
Running into the same error as well – looks like it's an issue with the edge runtime + `useContext` hook
