### ISSUE TITLE
with-web-worker doesn't work with 10.1

### ISSUE THREAD

**Issue by vuki656** [vercel/next.js#23542]
### What example does this report relate to?

with-web-worker 

### What version of Next.js are you using?

10.1.2

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying your application?

next dev

### Describe the Bug

When "next dev" is ran, the app crashes and produces the following: 

Error: Cannot find module 'webpack/lib/ParserHelpers'

### Expected Behavior

The example app should start normally when running "next dev"

### To Reproduce

1. Clone https://github.com/vercel/next.js/tree/canary/examples/with-web-worker
2. Install deps 
3. Run yarn dev

Full stack trace

```
Error: Cannot find module 'webpack/lib/ParserHelpers'
Require stack:
- /home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/worker-plugin/dist/worker-plugin.js
- /home/domagojvukovic/IdeaProjects/with-web-worker-app/next.config.js
- /home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/next-server/server/config.js
- /home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/next-server/server/next-server.js
- /home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/server/next.js
- /home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/server/lib/start-server.js
- /home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/cli/next-dev.js
- /home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.mod._resolveFilename (/home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/worker-plugin/dist/worker-plugin.js:5:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/worker-plugin/dist/worker-plugin.js',
    '/home/domagojvukovic/IdeaProjects/with-web-worker-app/next.config.js',
    '/home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/next-server/server/config.js',
    '/home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/next-server/server/next-server.js',
    '/home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/server/next.js',
    '/home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/server/lib/start-server.js',
    '/home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/cli/next-dev.js',
    '/home/domagojvukovic/IdeaProjects/with-web-worker-app/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.

```
-----------------------------

Tried:
- Bumping react to the latest version
- Bumping worker-plugin to the latest version
- Setting 
```
 future: {
    webpack5: true
  }
```
- Manually installing webpack 5

**Comment by Sebubu** [comment]
Same problem here. I tried the example on `master` and `canary`. Both don't work.

**Comment by ijjk** [comment]
This example appears to be working with the latest version of Next.js `v10.1.3` so I'm going to close this now, feel free to respond with additional info if you are still encountering problems with this!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
