### PR TITLE
Pin undici in tests

### PR DESCRIPTION
**Pull request by mischnic**
undici 7 was released 30 minutes ago and broke the tests because Turbopack now has troubles with its `node:sqlite` import.

You can see the test failure in https://github.com/vercel/next.js/pull/73261#issuecomment-2504054040

```
Error: Cannot find module 'node:sqlite': Unsupported external type Url for commonjs reference
    at <unknown> (.next/server/chunks/ssr/c1118_undici_e1ac85._.js:35:29147)
    at [project]/node_modules/.pnpm/undici@7.0.0/node_modules/undici/lib/cache/sqlite-cache-store.js [app-rsc] (ecmascript) (.next/server/chunks/ssr/c1118_undici_e1ac85._.js:35:29278)
    at instantiateModule (.next/server/chunks/ssr/[turbopack]_runtime.js:590:23)
    at getOrInstantiateModuleFromParent (.next/server/chunks/ssr/[turbopack]_runtime.js:645:12)
    at commonJsRequire (.next/server/chunks/ssr/[turbopack]_runtime.js:147:20)
    at [project]/node_modules/.pnpm/undici@7.0.0/node_modules/undici/index.js [app-rsc] (ecmascript) (.next/server/chunks/ssr/c1118_undici_e1ac85._.js:116:5860)
    at instantiateModule (.next/server/chunks/ssr/[turbopack]_runtime.js:590:23)
    at getOrInstantiateModuleFromParent (.next/server/chunks/ssr/[turbopack]_runtime.js:645:12)
    at esmImport (.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/app/undici/page.js [app-rsc] (ecmascript) <internal part 2> (.next/server/chunks/ssr/[root of the server]__83c897._.js:1:5666) {
```

https://github.com/nodejs/undici/blob/1cfe0949053aac6267f11b919cee9315a27f1fd6/index.js#L52-L59

https://github.com/nodejs/undici/blob/1cfe0949053aac6267f11b919cee9315a27f1fd6/lib/cache/sqlite-cache-store.js#L3

Closes PACK-3556

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ca0c79e219cb0979d4a447374104ecde1b87c7f1

`pnpm test-start-turbo test/e2e/app-dir/css-order/css-order.test.ts` (turbopack)
- css-order turbo > should load correct styles navigating back again interleaved-a -> interleaved-b -> interleaved-a -> interleaved-b
- css-order turbo > should load correct styles navigating back again pages-interleaved-a -> pages-interleaved-b -> pages-interleaved-a -> pages-interleaved-b
- css-order turbo > should load correct styles on first
- css-order turbo > should load correct styles on second
- css-order turbo > should load correct styles on third
- css-order turbo > should load correct styles on first-client
- css-order turbo > should load correct styles on second-client
- css-order turbo > should load correct styles on interleaved-a
- css-order turbo > should load correct styles on interleaved-b
- css-order turbo > should load correct styles on big-interleaved-a
- css-order turbo > should load correct styles on big-interleaved-b
- css-order turbo > should load correct styles on reversed-a
- css-order turbo > should load correct styles on reversed-b
- css-order turbo > should load correct styles on partial-reversed-a
- css-order turbo > should load correct styles on partial-reversed-b
- css-order turbo > should load correct styles on pages-interleaved-a
- css-order turbo > should load correct styles on global-first
- css-order turbo > should load correct styles on global-second
- css-order turbo > should load correct styles on vendor

<details>
<summary>Expand output</summary>

  ● css-order turbo › should load correct styles navigating back again first -> second -> first -> second

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again first -> third -> first -> third

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again first -> first-client -> first -> first-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again first -> second-client -> first -> second-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again second -> first -> second -> first

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again second -> third -> second -> third

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again second -> first-client -> second -> first-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again second -> second-client -> second -> second-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again third -> first -> third -> first

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again third -> second -> third -> second

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again third -> first-client -> third -> first-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again third -> second-client -> third -> second-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again first-client -> first -> first-client -> first

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again first-client -> second -> first-client -> second

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again first-client -> third -> first-client -> third

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again first-client -> second-client -> first-client -> second-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again second-client -> first -> second-client -> first

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again second-client -> second -> second-client -> second

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again second-client -> third -> second-client -> third

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again second-client -> first-client -> second-client -> first-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again interleaved-a -> interleaved-b -> interleaved-a -> interleaved-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again interleaved-b -> interleaved-a -> interleaved-b -> interleaved-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again big-interleaved-a -> big-interleaved-b -> big-interleaved-a -> big-interleaved-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again big-interleaved-b -> big-interleaved-a -> big-interleaved-b -> big-interleaved-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-first -> pages-second -> pages-first -> pages-second

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-first -> pages-third -> pages-first -> pages-third

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-second -> pages-first -> pages-second -> pages-first

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-second -> pages-third -> pages-second -> pages-third

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-third -> pages-first -> pages-third -> pages-first

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-third -> pages-second -> pages-third -> pages-second

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-interleaved-a -> pages-interleaved-b -> pages-interleaved-a -> pages-interleaved-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-interleaved-b -> pages-interleaved-a -> pages-interleaved-b -> pages-interleaved-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-reversed-a -> pages-reversed-b -> pages-reversed-a -> pages-reversed-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-reversed-b -> pages-reversed-a -> pages-reversed-b -> pages-reversed-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-partial-reversed-a -> pages-partial-reversed-b -> pages-partial-reversed-a -> pages-partial-reversed-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles navigating back again pages-partial-reversed-b -> pages-partial-reversed-a -> pages-partial-reversed-b -> pages-partial-reversed-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on first

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on second

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on third

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on first-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on second-client

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on interleaved-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on interleaved-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on big-interleaved-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on big-interleaved-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on reversed-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on reversed-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on partial-reversed-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on partial-reversed-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on pages-first

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on pages-second

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on pages-third

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on pages-interleaved-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on pages-interleaved-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on pages-reversed-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on pages-reversed-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on pages-partial-reversed-a

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on pages-partial-reversed-b

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on global-first

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on global-second

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● css-order turbo › should load correct styles on vendor

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).
