### ISSUE TITLE
Vercel monorepo routing error "cannot find module var/task[...]api/any-valid-route.js" after Next upgrade

### ISSUE THREAD

**Issue by dimroth** [vercel/next.js#23719]
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

12.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When upgrading Nextjs to 10.0.9 from Nextjs 10.0.8. Next API routing doesn't work in a monorepo setup after build on Vercel.
Keep receiving this error: `Cannot find module var/task/packages/nextjs/.next/server/pages/api/any-valid-route.js`

### Expected Behavior

"/api/any-valid-route" should be accessible after build and deploy

### To Reproduce

Minimal reproduction repository: [https://github.com/dimroth/aircampus-repro](https://github.com/dimroth/aircampus-repro)
Clone the repository
Try upgrading next to 10.0.9 in `packages/nextjs/package.json` and trigger a build on Vercel. Build should pass but access to "/api/check-domain" will fail once deployed.

![Capture d’écran 2021-04-01 à 16 54 46](https://user-images.githubusercontent.com/19348229/113670547-8f28e100-96b5-11eb-9e40-ebf90b4b395a.png)

**Comment by ijjk** [comment]
Hi, this should be corrected now, please re-deploy your application and give it a try!

**Comment by ijjk** [comment]
This patch should now be available, sorry for the delay, please re-deploy your application and give it a try!

**Comment by dimroth** [comment]
@ijjk thanks for the feedback.

I tried with Next 10.1.3 but it still doesn't work (with a different error message though) :
![Capture d’écran 2021-04-27 à 09 36 06](https://user-images.githubusercontent.com/19348229/116203580-22e15080-a73c-11eb-9320-0ae83b8dd4bb.png)

**Comment by ijjk** [comment]
@dimroth that error can be caused by having `NODE_ENV=development` set as an environment variable, removing that variable should resolve this. We are landing a change that will automatically override incorrect `NODE_ENV` values during a deploy.

**Comment by dimroth** [comment]
@ijjk indeed, sorry for this unrelated error. Vercel had set a `NODE_ENVIRONMENT=staging` for my staging phase in their new environment variables interface. I have no clue how it came here! Thanks again for the support 🙏

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
