### PR TITLE
Add puppeteer to external packages list

### LINKED ISSUE #49383: [NEXT-1136] Puppeteer error with Next13 app dir : TypeError: oe is not a function
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.15
      pnpm: 8.3.1
    Relevant packages:
      next: 13.4.1-canary.2
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/friendly-violet-44ognx?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A20%7D%5D

### To Reproduce

Try to navigate to the path /api/scraper

### Describe the Bug

Server Error
TypeError: oe is not a function
image

### Expected Behavior

When using the pages directory, it correctly returns the h1 of the page, on the other hand, when migrating it to the api directory, it returns that error.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-1136](https://linear.app/vercel/issue/NEXT-1136/puppeteer-error-with-next13-app-dir-typeerror-oe-is-not-a-function)</sub>

### PR DESCRIPTION
**Pull request by timneutkens**
## What?

Add puppeteer to the list of packages that can't be bundled, as it breaks when bundled as shown in #49383.

Fixes #49383
Fixes NEXT-1136

### CODE REVIEW

**Comment by timneutkens** [comment]
Current dependencies on/for this PR:
* canary
  * **PR #49597** <a href="https://app.graphite.dev/github/pr/vercel/next.js/49597" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/49597?utm_source=stack-comment).

File: packages/next/src/lib/server-external-packages.json [hunk 1]
```diff
@@ -23,6 +23,7 @@
   "postcss",
   "prettier",
   "prisma",
+  "puppeteer",
```
Comment (kachkaev) [inline packages/next/src/lib/server-external-packages.json:26]:
```suggestion
  "playwright",
  "postcss",
  "prettier",
  "prisma",
  "puppeteer",
```

Is it possible to do the same with [`playwright`](https://www.npmjs.com/package/playwright)? I have to use a [trick with `eval()`](https://github.com/kachkaev/website/blob/c3a149befaf26835e0c13991fb1a344e2e189059/app/%5Blocale%5D/update-profiles/shared/handler-helpers.ts#L35-L38) to make it work inside a Next.js route handler. It’s a cron job.

**Review by feedthejim — APPROVED** [review]

File: packages/next/src/lib/server-external-packages.json (hunk 1 above)
Comment (kachkaev) [reply packages/next/src/lib/server-external-packages.json:26]: Done by @jocarrd in https://github.com/vercel/next.js/pull/49649, thanks!
