### PR TITLE
fix: path issues on linux machines when build created on windows

### LINKED ISSUE #58244: Generating incorrect paths on assembly
### Link to the code that reproduces this issue

https://github.com/alexop1000/nextjs-issue-reproduction/tree/master

### To Reproduce

1. Build your next application on Windows (npm run build)
2. Build the docker image (for example, ``docker build --pull --rm -f "Dockerfile" -t nexttest:latest "."``)
3. Run the docker image on a Linux machine, or on Docker desktop.

### Current vs. Expected behavior

The user gets an internal error 500 when visiting your website. You get "Error: Cannot find module 'next/dist\client\components\static-generation-async-storage-external.js'" on server logs. The specifics can be found in [this discussion](https://github.com/vercel/next.js/discussions/56010).
Example error message output:
```bash
2023-11-09 10:52:50  ⨯ Error: Cannot find module 'next/dist\client\components\static-generation-async-storage.external.js'
2023-11-09 10:52:50 Require stack:
2023-11-09 10:52:50 - /usr/src/app/.next/server/app/_not-found.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/server/require.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/server/next-server.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/server/next.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/server/lib/start-server.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/cli/next-start.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/lib/commands.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/bin/next
2023-11-09 10:52:50     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
2023-11-09 10:52:50     at /usr/src/app/node_modules/next/dist/server/require-hook.js:54:36
2023-11-09 10:52:50     at Module._load (node:internal/modules/cjs/loader:901:27)
2023-11-09 10:52:50     at Module.require (node:internal/modules/cjs/loader:1115:19)
2023-11-09 10:52:50     at mod.require (/usr/src/app/node_modules/next/dist/server/require-hook.js:64:28)
2023-11-09 10:52:50     at require (node:internal/modules/helpers:130:18)
2023-11-09 10:52:50     at 5319 (/usr/src/app/.next/server/app/_not-found.js:1:612)
2023-11-09 10:52:50     at t (/usr/src/app/.next/server/webpack-runtime.js:1:127)
2023-11-09 10:52:50     at 2564 (/usr/src/app/.next/server/chunks/349.js:1:117695)
2023-11-09 10:52:50     at t (/usr/src/app/.next/server/webpack-runtime.js:1:127) {
2023-11-09 10:52:50   code: 'MODULE_NOT_FOUND',
2023-11-09 10:52:50   requireStack: [
2023-11-09 10:52:50     '/usr/src/app/.next/server/app/_not-found.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/server/require.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/server/next-server.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/server/next.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/server/lib/start-server.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/cli/next-start.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/lib/commands.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/bin/next'
2023-11-09 10:52:50   ]
2023-11-09 10:52:50 }
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: arm64
  Version: SMP Fri Aug 18 21:57:12 PDT 2023
Binaries:
  Node: 20.8.1
  npm: 10.1.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.0
  react: 18.2.0
  react—don: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Operating System (Windows, MacOS, Linux)

### Additional context

If you look in the discussion forum, you can see that it works in version 13.4.19.
You can also see that people have identified the specific problem that needs to be resolved.
The line:
```js
return `commonjs ${localRes.replace(/.*?next[/\\]dist/, "next/dist")}`
```
Has to be replaced with:
```js
return `commonjs ${localRes.replace(/.*?next[/\\]dist/, "next/dist").replace(/\\/g, "/")}`
```
In the file "\node_modules\next\dist\build\handle-externals.js", to generate the correct paths.

### PR DESCRIPTION
**Pull request by keyur2582**
### What?
The user gets an internal error 500 when visiting your website. You get "Error: Cannot find module 'next/dist\client\components\static-generation-async-storage-external.js'" on server logs. The specifics can be found in https://github.com/vercel/next.js/discussions/56010.

### Why?
If build was created on windows it is using '\\' in the paths whereas it has to be replaced with '/'. If the same build is deployed to linux based machines like app engine, it throws the error above.

### How?
By replacing 
`return `commonjs ${localRes.replace(/.*?next[/\\]dist/, "next/dist")}`
with 
`return `commonjs ${localRes.replace(/.*?next[/\\]dist/, "next/dist").replace(/\\/g, "/")}``
in
`next\build\handle-externals.js`

Closes NEXT-58244
Fixes #58244

-->

### CODE REVIEW

**Comment by alexop1000** [comment]
Do you have any update on getting this merged? A lot of us are waiting for this tiny fix🙏

**Comment by clearly-outsane** [comment]
Looking forward to this!

**Comment by alexop1000** [comment]
Hi @ijjk @ztanner or anyone, sorry for the ping, but could we get a review? It's a one-line fix so it should only take a few minutes of your time, and help a lot of people.

**Comment by RamboCambo** [comment]
@ztanner Following suit from @alexop1000 Pinging this too as it is still happening on Dec 30.

**Comment by spsesha** [comment]
Pinging this to follow up, this is still happening. Please take a look into this as this is simple fix
@timneutkens @ijjk @ztanner

**Comment by Enngage** [comment]
Yes, please... just merge this PR for the sake of all of us.

**Comment by timneutkens** [comment]
Hey, thanks for looking into this! I just had a look and this change looks fine, it seems the tests did not run because of the branch not being editable and I can't trigger a branch update either, probably because it was opened on an organization instead of an individual. I've opened https://github.com/vercel/next.js/pull/60116 so that this change can be landed, you'll be credited in the same way, as it's the same commits.
