### PR TITLE
Fix validator.ts import path in isolated dev builds

### PR DESCRIPTION
**Pull request by agadzik**
In dev mode with strictRouteTypes enabled, the generated validator.ts file in `.next/dev/types/` was importing from `./routes.js`, but `routes.d.ts` doesn't exist in that directory - only `route-types.d.ts` does. This caused `TS2307: Cannot find module './routes.js'`.

Changed the import path from `./routes.js` to `./route-types.d.ts` in generateValidatorFileStrict().

### CODE REVIEW

**Comment by agadzik** [comment]
not a bug

**Comment by runderworld** [comment]
hi @agadzik , is this expected behavior or was there something you were doing wrong which resolved the issue for you?  

it's been an issue since we upgraded to 16.x, not sure why typegen is generating that path for TS in our next dev builds.

**Comment by agadzik** [comment]
> hi @agadzik , is this expected behavior or was there something you were doing wrong which resolved the issue for you?
> 
> it's been an issue since we upgraded to 16.x, not sure why typegen is generating that path for TS in our next dev builds.

@eps1lon mind clarifying
