### ISSUE TITLE
Module "react" has no exported member 'cache'

### ISSUE THREAD

**Issue by LamsaLL** [vercel/next.js#49707]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023
Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.19
      pnpm: N/A
Relevant packages:
      next: 13.4.2
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/distracted-johnson-so7m95?file=%2Fpackage.json%3A7%2C5

### To Reproduce
Add this line in page.tsx:
```import { cache } from "react";```
Then install dependencies (from codesandbox):
```yarn``` or ```npm install```

### Describe the Bug

 **Downgrading Next.js version to 13.2.4 fix the issue** but on upper versions, it throws the following error :  

![import-error](https://github.com/vercel/next.js/assets/56052339/018821c0-1619-4862-b33f-326ac3bcc821)

It seems that when installing packages my next.dt.ts file become empty :

```ts
// next.d.ts
import React = require('.');

export {};

declare module '.' {}
```

And normally it should contain cache function : 

```ts
// next.d.ts
...
// tslint:disable-next-line ban-types
export function cache<CachedFunction extends Function>(fn: CachedFunction): CachedFunction;
...
```

### Expected Behavior

Importing React cache() should work

**Comment by khuezy** [comment]
The sandbox loads the page w/o issue. I don't see that error in the logs either.

**Comment by LamsaLL** [comment]
In page.tsx : 
![import-error](https://github.com/vercel/next.js/assets/56052339/018821c0-1619-4862-b33f-326ac3bcc821)

**Comment by brett-minca** [comment]
Since upgrading to 13.4.2, I'm seeing something that might be related:

`(0 , react__WEBPACK_IMPORTED_MODULE_0__.cache) is not a function`

But, this only happens when running next dev.  It works just fine in production build.

**Comment by kasvith** [comment]
I also have the same problem

**Comment by iSuslov** [comment]
Same here. Works only with `"react": "18.3.0-canary-4cd706566-20230512"` dependency.
