### ISSUE TITLE
Cannot find module 'sharp' 

### ISSUE THREAD

**Issue by testerez** [vercel/next.js#56607]
### Link to the code that reproduces this issue

https://github.com/testerez/test-next-sharp-import-error

### To Reproduce

1. deploy the project to Vercel
2. open deployed app and notice that the image is not loading
3. check Vercel Logs to see the error. 

### Current vs. Expected behavior

When updating nextjs from v13.5.3 to v13.5.4 I started getting this error once deployed on Vercel:
```
Error: Cannot find module 'sharp'
```

I'm using sharp to resize images and it was woking well before this minor next update. It's also working locally with no issue. I created a minimal repo to reproduce the error. You can test it locally, it should work and display a red image. But once deployed to Vercel, you should get the error.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.15.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.8.0
Relevant Packages:
  next: 13.5.4
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

<sub>[NEXT-1674](https://linear.app/vercel/issue/NEXT-1674/cannot-find-module-sharp)</sub>

**Comment by balazsorban44** [comment]
This seems to be a regression but we are aware: https://github.com/vercel/next.js/pull/56048/files#r1349165267

We will have a look, thanks!

**Comment by huozhi** [comment]
Closed as fixed. Releated tracing fixes: #56674, please upgrade to 13.5.5
