### ISSUE TITLE
XRegExp is not a function when importing ravendb client in server components or pages (works in 13.5) using plain javascript (works with typescript)

### ISSUE THREAD

**Issue by erikarenhill** [vercel/next.js#57657]
### Link to the code that reproduces this issue

https://gist.github.com/erikarenhill/6aa4c77e0887a323746952de168ffabf

### To Reproduce

1. create a new project with next-create-app, select no when asked if you want to use typescript
2. install ravendb client (5.4.1) (npm i ravendb)
3. import { DocumentStore } from 'ravendb'  in a server component or page
4. run the project, npm run dev

### Current vs. Expected behavior

Expected behaviour: The page loads correctly

Current behaviour: crash with Error: XRegExp is not a function

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I have reproduced it locally using both node 18 and 20.

As it works with next 13.5 I'm adding this bug to the next project, as it looks like it can not resolve dependencies for libraries used correctly in the same way as 13.5.
