### ISSUE TITLE
rt.toLowerCase is not a function on fresh next js init

### ISSUE THREAD

**Issue by AkipTsaqif** [vercel/next.js#64465]
### Link to the code that reproduces this issue

https://github.com/AkipTsaqif/next-js-init-error

### To Reproduce

1. do `npx create-next-app@latest` and follow the steps as usual
2. do `npm run dev`
3. next js runs but produces error on the terminal, saying `rt.toLowerCase is not a function at \node_modules\next\dist\compiled\webpack\bundle5.js:30:274042`

### Current vs. Expected behavior

next js should not produces those error

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32704
  Available CPU cores: 6
Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

based on [this SO question](https://stackoverflow.com/questions/78321779/typeerror-rt-tolowercase-is-not-a-function-nextjs), that just been asked recently, this happens on next js 14.2

**Comment by dannywamuya** [comment]
I am losing my mind right now going through this same problem reinitializing but no difference. The page also initially renders and cant reload again. All from new app initializations.

**Comment by kobysysouvanh** [comment]
I am also having this issue on 14.2.1

**Comment by abdulkareemolumoh** [comment]
I am having same issues. I started exprencing it ever since i updated my nextjs to 14.2.1

**Comment by jovar-dev** [comment]
The same issue. NextJS 14.2.1

**Comment by dannywamuya** [comment]
How far back has anyone had to downgrade to get it sorted?

**Comment by Oelshehawi** [comment]
Managed to temp fix it by just going into the bundle5.js file and just replacing rt.toLowerCase() -> rt.toString().toLowerCase()

**Comment by madrosir** [comment]
The same issue. NextJS 14.2.1

**Comment by PolGubau** [comment]
I tried to downgrade to 14.0.4 but still happening

**Comment by timneutkens** [comment]
Hey everyone, I've had a look at the reproduction repository but I'm unable to trigger the same error. We tried both macOS, Windows, and Codesandbox but it doesn't trigger. It'd be helpful to get more information that "same issue" for this, to let people know you're running into the same issue you can use the GitHub 👍 feature. Posting "same issue" is not taken into account when sorting issues by how many people are running into them.

Is everyone that commented on this issue using Windows? Something else? Which version of Node.js? Tip: you can run `next info` to get this information.

**Comment by rawic** [comment]
Hi,
I am also experiencing this issue with the rt.toLowerCase is not a function error when running `yarn dev` in a project. Here’s the output from running next info in my environment, which might help in identifying any commonalities causing this problem:

```
Version: Windows 11 Pro Education
  Available memory (MB): 32702
  Available CPU cores: 16
Binaries:
  Node: 20.11.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
Done in 1.84s.
```

**Comment by husen1003** [comment]
I am also getting the same issue:

`Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 15973
  Available CPU cores: 8
Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: 8.7.5
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).       
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A`

**Comment by Hugo-Delattre** [comment]
> Additionally, I've found that rolling back to Next.js version 14.1.4 resolves this issue.

I had the same issue on latest version, I confirm that rolling back to Next.js 14.1.4 solved it (thanks Rawic!)

**Comment by alexanderwford** [comment]
I'm also having this issue

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 131017
  Available CPU cores: 16
Binaries:
  Node: 21.6.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

**Comment by Poylar** [comment]
`Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 16307
  Available CPU cores: 16
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.15.5
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.4
Next.js Config`

downgrade to 14.1.2 not fixed the problem, only 14.0.2 fixed

**Comment by alexanderwford** [comment]
Disabling the Console Ninja VS Code Extension fixed this for me.

**Comment by xspaceboy** [comment]
Seems like Next.js 14.2 version doesn't support Console Ninja VS Code Extension.
Oh, Maybe Console Ninja VS Code Extension need to update fit to Next.js 14.2 version.

**Comment by pwglownia** [comment]
you guys are brilliant, it really seems to be connected to Console Ninja Extension.

**Comment by watercubz** [comment]
I have the same error when trying to create an api in version 14.2.1 of nextjs, in the api/hello/hello.ts path it tells me that there was an error with the webpack compiler
![imagen_2024-04-15_184715125](https://github.com/vercel/next.js/assets/112292926/c8a62db0-55f4-473e-a0cb-fd27b64b9808)

**Comment by user-222002** [comment]
im also facing this issue....

**Comment by PrinzEugen39** [comment]
Hello, so im new developer here with minimum experience. Can you tell me how to recognize problem like this? Like how did we found that console ninja was the source of this problem

**Comment by CarrettaRiccardo** [comment]
> Reference in new issue
> Report conten

After disabling Console Ninja, clean `.next` and `node_modules` and reinstall dependencies to work.
It seems like to happen again **when installing a new dependency** and **Console Ninja is enabled**.

**Comment by timneutkens** [comment]
Seems that the Console Ninja extension changes the internals of all frameworks, i.e. it changes Next.js internals to preload code. The code of their extension is heavily mangled and can't be audited. 

Was able to confirm it adds additional code to Next.js internals and that's why it's breaking:

![CleanShot 2024-04-16 at 11 26 57@2x](https://github.com/vercel/next.js/assets/6324199/0a2d24b5-9ef4-451d-8bf7-b81772d319df)

That type of changing internals is going to break between any version really, not just for Next.js but for any framework that extension supports.

I'd like to avoid having to add integrity checks for core files to Next.js as it's quite slow. Guess we'll have to add a big warning to Next.js when console ninja is detected.

**Comment by mohammednazim007** [comment]
This issue occurred for console Ninja. Update your vs code extension console Ninja & run again

**Comment by ArtemGovorov** [comment]
Hi, Console Ninja extension team member here. I can confirm the issue was caused by the patch Console Ninja makes in order to support Next.js. The behaviour is clearly [described in the extension docs](https://github.com/wallabyjs/console-ninja?tab=readme-ov-file#how-does-it-work).

As soon as the issue has been brought up to our attention, we [have fixed it](https://github.com/wallabyjs/console-ninja/issues/287) in less than an hour, the extension version 1.0.306 should be working with the latest version of Next.js.

@timneutkens Typically, our patches to other tools are quite small and only include our loader at the start of a tool entry files. Unfortunately, with Next.js that packs its own minified version of webpack, it is slightly harder for us. We are working on a better version of the patch that should not break Next.js if it fails to apply and will point to Console Ninja in case of any issues.

**Comment by AkipTsaqif** [comment]
> As soon as the issue has been brought up to our attention, we [have fixed it](https://github.com/wallabyjs/console-ninja/issues/287) in less than an hour, the extension version 1.0.306 should be working with the latest version of Next.js.

Finally thank you! At first I thought this is a Next Js issue since it doesn't mention anything about anything other than the webpack itself.

**Comment by timneutkens** [comment]
@ArtemGovorov thanks for the additional explanation 🙏  I think it would be very helpful if you add a warning / log somewhere to ensure that people are aware that Console Ninja has edited the internals of a framework and might break the framework. I.e. seems a similar issue happened with SvelteKit and they weren't able to figure out the problem for a while as well: https://github.com/sveltejs/kit/issues/10252

**Comment by ArtemGovorov** [comment]
@timneutkens Great idea, thanks! Apart from making sure our patches should not break target tools, we went ahead and added/released the following message to all CLI tools we integrate with:

<img width="858" alt="Screenshot 2024-04-17 at 11 09 58 AM" src="https://github.com/vercel/next.js/assets/979966/d83ba0d3-f622-464c-acc6-f906e148b4c1">

(the URL describes the behaviour of patching modules, and how to quickly undo it).

**Comment by timneutkens** [comment]
Awesome, thank you!
