### ISSUE TITLE
Config issues when combining distDir and output:"export"

### ISSUE THREAD

**Issue by karelFourie** [vercel/next.js#61105]
### Link to the code that reproduces this issue

https://github.com/karelFourie/NextIssueReproduction/tree/main/next-issue-reproduction

### To Reproduce

1. Create a new app using create-react-app (14.1.0)
2. Change next.config.mjs file to include both distDir: "build/testBuild" & output:"export"
3. Run npm run dev
4. Error messaging turns up in the console

### Current vs. Expected behavior

I used create-next-app to create a vanilla next app and have tested that it works in its base state. When I change the next.config to include both distDir and output I get the following error message when I spin up the dev server:

`⨯ Error: Cannot find module '.../testing14-1-0/build/testBuild/server/middleware-manifest.json'`

### Provide environment information

```bash
Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.10.5
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

**Note:** Config combination was not an issue in 14.0.1

**Canary checks:**
`14.0.5-canary.10`: Broken
`14.0.5-canary.9`: Works as intended

<sub>[NEXT-2433](https://linear.app/vercel/issue/NEXT-2433/config-issues-when-combining-distdir-and-outputexport)</sub>

**Comment by matthewwolfe** [comment]
In 13.x it looks like when changing the `distDir` nextjs will output to that directory during dev mode, but in 14.x nextjs outputs to `.next` regardless of what is set as `distDir`.

**Comment by matthewwolfe** [comment]
@karelFourie can you confirm that `14.0.5-canary.10` is broken and `14.0.5-canary.9` works as intended.

**Comment by karelFourie** [comment]
@matthewwolfe Can confirm, the config works in `14.0.5-canary.9` but not in `14.0.5-canary.10`.

**Comment by DarkGuy10** [comment]
Same as #61041

**Comment by aleksijohansson** [comment]
I'm facing this issue as well!

**Comment by kimwoodfield** [comment]
> Same as #61041

Ran into this issue today as well. Trying to output static files to a `dist` folder by updating `next.config.msj` breaks `next dev`. I was able to unblock myself by setting it back to an empty object for now.

My error looked like this in case anyone else stumbles across it:
```
✓ Ready in 1863ms
 ○ Compiling / ...
 ✓ Compiled / in 1725ms (919 modules)
 ✓ Compiled /not-found in 328ms (924 modules)
 ⨯ Error: Cannot find module '/app/source/dist/server/middleware-manifest.json'
Require stack:
- /app/source/node_modules/next/dist/server/next-server.js
- /app/source/node_modules/next/dist/server/dev/next-dev-server.js
- /app/source/node_modules/next/dist/server/next.js
- /app/source/node_modules/next/dist/server/lib/start-server.js
```

**Comment by AlbinoGeek** [comment]
This should have huge attention as it's **a regresssion in a minor version**.

We have been forced to lock our projects to `~14.0` to avoid this update.

**Comment by ccmvn** [comment]
I can also confirm this bug which starts occurring from 14.1.0. When you downgrade to 14.0.4 everything works again without any problems

**Comment by ijjk** [comment]
Hi, the provided reproduction appears to be building without error in the latest version and latest canary, could someone seeing this provide an updated reproduction where it's failing?

**Comment by DarkGuy10** [comment]
> Hi, the provided reproduction appears to be building without error in the latest version and latest canary, could someone seeing this provide an updated reproduction where it's failing?

It's the dev server that's failing. Building works (has worked) fine even in 14.1.0

**Comment by kimwoodfield** [comment]
@ijjk  

I'm experiencing the same as @DarkGuy10 and @matthewwolfe. 

`next build` and `next start` scripts works as expected on the latest version. It's the `next dev` script that is broken after updating `next.config` file with the properties mentioned above.

**Comment by blakerutledge** [comment]
Also chiming in here with failing dev server in this manner described, using 14.1.0.

Reverted to 14.0.4 to continue being able to work ... !

**Comment by ijjk** [comment]
Hi, this should now be fixed in `v14.1.1-canary.54` of Next.js, please upgrade and give it a try!

**Comment by DarkGuy10** [comment]
If this is fixed,  #61041 and #61105 can be closed as well I guess

**Comment by ccmvn** [comment]
> If this is fixed,  #61041 and #61134 can be closed as well I guess

I can also confirm that the bug has been fixed

**Comment by stavros-k** [comment]
Also https://github.com/vercel/next.js/issues/61905

**Comment by ijjk** [comment]
Hi, @stavros-k this was not released in those backports, we added a notice to those releases mentioning only some critical fixes were included and not all fixes/changes from canary.

**Comment by stavros-k** [comment]
Ah, I guess got too excited!
Thanks for answering on a closed issue!
Will wait for the next minor release (I guess?)

**Comment by ijjk** [comment]
Hi, the above fix is now available in `v14.1.3`, please update and give it a try!
