### ISSUE TITLE
Next fails to build when using webpack's CompressionPlugin

### ISSUE THREAD

**Issue by awareness481** [vercel/next.js#22510]
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

v14.15.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Xubuntu 20.04

**How are you deploying your application?**

N/A

**Describe the Bug**

Using webpack's [CompressionPlugin](https://webpack.js.org/plugins/compression-webpack-plugin/) makes Next's build process fail with following error message

```
> Build error occurred
Error: Cannot find module 'webpack'
```
[Full error log](https://github.com/awareness481/Next-With-CompressionPlugin-bug/blob/main/error.log)

This was working in Next v10.0.5. **Note**, I haven't found which is latest working version of Next.

**Expected Behavior**

To build and create the compressed files.

**To Reproduce**

1. Clone https://github.com/awareness481/Next-With-CompressionPlugin-bug
2. Install deps
3. Run `npm run build`
4. Observe failed build

I'm not sure if Next.js is expected to work with webpack's CompressionPlugin or webpack's core plugins, but it was working in earlier versions which is why I decided to file this issue.

**Comment by timneutkens** [comment]
Duplicate of #21679

**Comment by awareness481** [comment]
Sorry about the duplicate! I sincerely forgot to search if the issue already exists before creating one.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
