### ISSUE TITLE
Failed to load external module with turbopack and bun

### ISSUE THREAD

**Issue by Haaxor1689** [vercel/next.js#86866]
### Link to the code that reproduces this issue

https://github.com/Haaxor1689/next-turbopack-issue-repro

### To Reproduce

1. `bun i`
2. `bun --bun dev` (--bun is important to run with bun runtime)

### Current vs. Expected behavior

You get following error when importing anything from "@aws-sdk/client-s3".

```
Failed to load external module @aws-sdk/client-s3-ecbef8e33fd0b8f0: ResolveMessage: Cannot find module '@aws-sdk/client-s3-ecbef8e33fd0b8f0' from 'C:\Projects\reproduction-app\.next\dev\server\chunks\ssr\[root-of-the-server]__8c5801f7._.js'
```

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 65451
  Available CPU cores: 16
Binaries:
  Node: 23.10.0
  npm: 10.9.2
  Yarn: N/A
  pnpm: 10.7.0
Relevant Packages:
  next: 16.1.0-canary.14 // Latest available version is detected (16.1.0-canary.14).
  eslint-config-next: N/A
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Since Bun is not in `next info` - I'm using Bun v1.3.2
This issue was already reported once by me and closed as fixed here #86652. This solved the issue in 16.1.0-canary.10 for node runtime but the issue in bun runtime still persists.

**Comment by catosaurusrex2003** [comment]
Same issue here.

Turbopack build fails in Next.js 16 when `thread-stream` / `pino` / `WalletConnect` dependencies are installed.

I upgraded from Next.js `16.0.1` → `16.0.7` due to the security advisory:
https://nextjs.org/blog/CVE-2025-66478

At the same time, I also upgraded React because of the critical RSC vulnerability:
[https://react.dev/blog/2025/12/03/critical-security-vulnerability-in-react-server-components](https://react.dev/blog/2025/12/03/critical-security-vulnerability-in-react-server-components?utm_source=chatgpt.com)

```
"react": "19.2.0" → "19.2.1",
"react-dom": "19.2.0" → "19.2.1"
```

But the build did not start failing after the React upgrade.
The failures began only after upgrading Next.js.

After moving to `16.0.7`, my production build shows the same Turbopack errors reported in this issue (Missing module type, Unknown module type, Parsing ecmascript failed) originating from thread-stream test files.

Everything was working correctly in Next.js 16.0.1.

I am not using bun

**Comment by CosAnca** [comment]
I'm having the same issue with Turbopack build failures in a project where I have `pino` installed and upgraded Next.js from `16.0.1` to `16.0.7`.

Although not ideal, using the `--webpack` flag on the build command, does build the project successfully.

I'm using `pnpm@10.71` with:

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.1.0: Mon Oct 20 19:32:41 PDT 2025; root:xnu-12377.41.6~2/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 22.20.0
  npm: 10.9.3
  Yarn: 1.22.22
  pnpm: 10.7.1
Relevant Packages:
  next: 16.0.7 // Latest available version is detected (16.0.7).
  eslint-config-next: N/A
  react: 19.2.1
  react-dom: 19.2.1
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

**Comment by Haaxor1689** [comment]
@catosaurusrex2003 and @CosAnca if you are not using Bun runtime then try canary 10 where my previous issue was fixed in. Canary 12+ should contain the security fix but I wasn't able to confirm that anywhere.

**Comment by catosaurusrex2003** [comment]
@CosAnca, @Haaxor1689  
`--webpack` flag on the build command, works perfectly 👍 , 
thanks

**Comment by mischnic** [comment]
Strange, https://github.com/vercel/next.js/pull/86697 should have fixed that.

Could you verify if running it with Node instead of Bun works fine? Then it seems like a bug in bun

**Comment by Haaxor1689** [comment]
Yes, running in node instead of bun works, or running with webpack and bun also works.

**Comment by mischnic** [comment]
I recommend that you report this to bun then.

**Comment by Haaxor1689** [comment]
Here is the [Bun issue](https://github.com/oven-sh/bun/issues/25370).

**Comment by catosaurusrex2003** [comment]
> [@CosAnca](https://github.com/CosAnca), [@Haaxor1689](https://github.com/Haaxor1689)
> `--webpack` flag on the build command, works perfectly 👍 ,
> thanks

Update: 
The build is successful with webpack, but many of my the crypto wallet libraries I am using dont work well with webpack.

So I reverted back to turbopack and made the following changes for it to work

```ts
// next.config.ts
const nextConfig: NextConfig = {
  /* config options here */
  devIndicators: false,
  turbopack: {
    resolveAlias: {
      pino: "pino/browser", // these were the libraries which were giving me error while bulding
      "pino/lib/transport": "pino/browser",
      "thread-stream": "./lib/empty.js",
    },
  },
};
```

```ts
// ./lib/empty.js
export default {};
export const empty = {};

```

@mischnic  I am using node

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #36~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct 15 15:45:17 UTC 2
  Available memory (MB): 31189
  Available CPU cores: 12
Binaries:
  Node: 22.16.0
  npm: 11.5.1
  Yarn: N/A
  pnpm: 10.12.1
Relevant Packages:
  next: 16.0.7 // Latest available version is detected (16.0.7).
  eslint-config-next: N/A
  react: 19.2.1
  react-dom: 19.2.1
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

**Comment by kkoudelka** [comment]
Updating `next.config.ts` worked for me (turbopack and yarn v4):

```ts
const nextConfig: NextConfig = {
  ...
  serverExternalPackages: ["pino"],
};
```

**Comment by CosAnca** [comment]
I confirm that adding "pino" into the `serverExternalPackages` config, successfully builds the app using pnpm and Turbopack now.
Thank you for the tip @kkoudelka

**Comment by Haaxor1689** [comment]
@kkoudelka and @CosAnca your issue should be fixed since canary10 with the previous issue, this only regards bun + turbopack

but I'll go try setting it as an external package and see if that helps in bun

**Edit:** nope, putting it to `serverExternalPackages` does not seem to fix this bun + turbopack issue, guess I have to suffer the webpack dev mode slowness

**Comment by hvqzao** [comment]
This seems strangely related to turbopack caching.

`bun clean` and `bun dev` triggers the error:

```
⨯ Error: Failed to load external module @mui/material-nextjs-078508446b75cbc9/v15-pagesRouter: ResolveMessage: Cannot find module '@mui/material-nextjs-078508446b75cbc9/v15-pagesRouter' from '/home/[...]/next/dev/server/chunks/ssr/[turbopack]_runtime.js'
```

The problem does not seem to go away in time. app need to be terminated and restarted, then the problem does not reoccur.

I made a copy of `.next` folder, ^C the app and rerun `bun dev`. Error no longer appears, running diff on `.next` and `.next.backup` gives:

```
Only in .next/dev/cache/turbopack/ea1df5f2: 00000001.sst
Only in .next/dev/cache/turbopack/ea1df5f2: 00000002.sst
Only in .next/dev/cache/turbopack/ea1df5f2: 00000003.sst
Only in .next/dev/cache/turbopack/ea1df5f2: 00000004.sst
Only in .next/dev/cache/turbopack/ea1df5f2: 00000005.sst
Only in .next/dev/cache/turbopack/ea1df5f2: 00000006.sst
Only in .next/dev/cache/turbopack/ea1df5f2: 00000007.sst
Only in .next/dev/cache/turbopack/ea1df5f2: 00000008.sst
Only in .next/dev/cache/turbopack/ea1df5f2: 00000009.meta
Only in .next/dev/cache/turbopack/ea1df5f2: 00000010.meta
Only in .next/dev/cache/turbopack/ea1df5f2: 00000011.meta
Only in .next/dev/cache/turbopack/ea1df5f2: 00000012.meta
Only in .next/dev/cache/turbopack/ea1df5f2: 00000013.meta
Binary files .next/dev/cache/turbopack/ea1df5f2/CURRENT and next.1/dev/cache/turbopack/ea1df5f2/CURRENT differ
Only in .next/dev/cache/turbopack/ea1df5f2: LOG
```

I'm curious how this is to be resolved on prod, as my app has no write access to `.next` folder there, so the trick with rerun will not fix things.

**Update:**
I've found some recent options for turbopack filesystem caching but setting them to true or false does not seem to make any difference. https://nextjs.org/docs/app/api-reference/config/next-config-js/turbopackFileSystemCache

**Update 2:**
dev behavior is proper on next@16.0.10, faulty on next@16.1.0.

**Comment by gustavovalverde** [comment]
Additional data point: macOS ARM64 + `@tensorflow/tfjs-node`

**Environment:**
- macOS 15 (Darwin 25.0.0) ARM64 (Apple Silicon)
- Bun 1.3.5
- Next.js 16.1.1-canary.6 → downgraded to 16.0.10

**Affected package:** `@tensorflow/tfjs-node` (native module with libtensorflow C library)

**Error:**
```
Failed to load external module @tensorflow/tfjs-node-d87e48818a8a4a7f: 
Error [ERR_DLOPEN_FAILED]: Library not loaded: libtensorflow.2.dylib
```

The Turbopack hash mismatch also caused the native library download to fail silently during `bun install`, resulting in broken symlinks in `node_modules/@tensorflow/tfjs-node/deps/lib/`. This is unique to native modules with C library dependencies.

Downgrading to Next.js 16.0.10 fixes both the module resolution AND the native library download. No custom postinstall scripts needed.

Adding `serverExternalPackages` did NOT fix this for Bun runtime (as noted by @Haaxor1689).

**Comment by l-you** [comment]
The same goes with PayloadCMS + PostgreSQL. `serverExternalPackages` does not help.
```
⨯ Error: Failed to load external module @payloadcms/db-postgres-0bcdb796bf5a68b7: ResolveMessage: Cannot find package 'jose' from '/app/node_modules/payload/dist/auth/strategies/jwt.js'
    at externalImport (.next/server/chunks/ssr/[turbopack]_runtime.js:518:19)
    at processTicksAndRejections (null)
```

**Comment by l-you** [comment]
After many tries, I managed to fix my case for the following error.
```
⨯ Error: Failed to load external module @payloadcms/db-postgres-0bcdb796bf5a68b7: ResolveMessage: Cannot find package 'jose' from '/app/node_modules/payload/dist/auth/strategies/jwt.js'
    at externalImport (.next/server/chunks/ssr/[turbopack]_runtime.js:518:19)
    at processTicksAndRejections (null)
```

I just removed `serverExternalPackages: ['@payloadcms/db-postgres', 'jose’],` from the `next.config.ts` and install packages in Dockerfile via `RUN bun install --frozen-lockfile --linker=isolated`. `linker=isolated` option avoids symlinks inside the `node_modules`.

@gustavovalverde please, check whether `--linker=isolated` works for you.

**Comment by okandship** [comment]
this is what claude code came up with to make `sharp` work in local dev/prod with bun+turbopack:

```ts
import { createRequire } from "node:module";

/**
 * Load sharp, working around a Turbopack + Bun dev server bug.
 *
 * Turbopack externalises native packages by creating hashed symlinks
 * (e.g. `sharp-20c6a5da84e2135f`) in `.next/dev/node_modules/`.
 * Bun's require() cannot resolve these hashed names, so the normal
 * `import("sharp")` that Turbopack rewrites fails at runtime.
 *
 * In development we use createRequire anchored to the project root to
 * resolve sharp directly from the real node_modules. In production the
 * normal require works because vercel externalises sharp correctly.
 *
 * @see https://github.com/vercel/next.js/issues/86866
 * @see https://github.com/oven-sh/bun/issues/25370
 */
let sharp: typeof import("sharp");

if (process.env.NODE_ENV === "development") {
  const req = createRequire(`${process.cwd()}/`);
  sharp = req("sharp");
} else {
  sharp = require("sharp");
}

export default sharp;
```

**Comment by TerryHenrard** [comment]
### Additional data point: regression confirmed in 16.2.0 (stable) on Vercel with Bun runtime

**Environment:**
- Windows 11, Bun 1.3.11
- Vercel preview deployment with `bunVersion: "1.x"` in `vercel.json`
- Next.js App Router with ElysiaJS catch-all route handler (`app/api/[[...slugs]]/route.ts`)

**What works:**
- Next.js 16.1.6 ✅
- Next.js 16.1.7 ✅

**What breaks:**
- Next.js 16.2.0 ❌

**Error (from Vercel runtime logs):**
```
Failed to handle /api/auth/sign-in/email?nxtPslugs=auth%2Fsign-in%2Femail
Error: Failed to load external module bun: Error: Cannot find module 'bun'
```

**Reproduction:**
Any `import { S3Client, randomUUIDv7 } from 'bun'` in server-side code triggers the error on Vercel when using Next.js 16.2.0 with `bunVersion: "1.x"`. The same code works perfectly on 16.1.7.

**`package.json` scripts:**
```json
{
  "dev": "bun run --bun next dev",
  "build": "bun run --bun next build"
}
```

**`vercel.json`:**
```json
{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "bunVersion": "1.x"
}
```

This confirms a clear regression between 16.1.7 and 16.2.0 for the Bun runtime on Vercel. Downgrading to 16.1.7 resolves the issue.

**Comment by Tomato6966** [comment]
On ubuntu24 with nextjs 16.1.7 nor 16.0 nor 16.2 and bun 1.3.11 it does not work, it still says
Error: Failed to load external module bun: Error: Cannot find module 'bun'

It works on ubuntu22 tho.

**Comment by gaearon** [comment]
As far as I understand, the remaining issue here is a Bun bug tracked in https://github.com/oven-sh/bun/issues/25370.
