### ISSUE TITLE
infinite refresh loop and crashes in next.js 16.2.7

### ISSUE THREAD

**Issue by ken-spencer** [vercel/next.js#94634]
### Link to the code that reproduces this issue

https://github.com/ken-spencer/ff-refresh-bug

### To Reproduce

In Firefox, pages that use PPR  go into an infinite refresh loop. Doesn't seem to happen in 16.2.6 but does in 16.2.7 &  16.2.9

```jsx
// app/page.tsx
import { Suspense } from "react";

async function Slow() {
  await new Promise((resolve) => setTimeout(resolve, 500));
  return <div>Loaded</div>;
}

export default function Page() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <Slow />
    </Suspense>
  );
}
```

### Current vs. Expected behavior

don't expect an infinite reload loop. 

### Provide environment information

```bash
/bin/sh: yarn: command not found
/bin/sh: pnpm: command not found

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.5.0: Mon Apr 27 20:41:26 PDT 2026; root:xnu-12377.121.6~2/RELEASE_ARM64_T8132
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 24.16.0
  npm: 11.13.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 16.2.9 // Latest available version is detected (16.2.9).
  eslint-config-next: N/A
  react: 19.2.7
  react-dom: 19.2.7
  typescript: 6.0.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Partial Prerendering (PPR)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

seems fine after build, but running dev is cursed

**Comment by icyJoseph** [comment]
Hi, this doesn't seem to be PPR related at all. Nor Cache Components. I was able to narrow it down to `16.2.1-canary.46` as the first version where the issue happens. I'll post back when I know more.

**Comment by icyJoseph** [comment]
Oh well, typical triaging mistake, I did not verify the very latest canary - as of `16.3.0-canary.30` this fix landed: https://github.com/vercel/next.js/pull/94128

The next minor/patch should contain this fix. Could you just verify `next@canary` on your end?

**Comment by BruceHubbard** [comment]
I was working on upgrading our app from 16.1.7 to 16.2.7 to mitigate the recent npm security vulnerabilities and I see a similar thing locally.  We're using pages router and when any page loads we see this error about 10-12 times:

`WebSocket connection to 'wss://<my_local_url>/_next/webpack-hmr' failed:`

After 10-12 times repeating that error the page refreshes.  This is on chrome.  I tried every version between 16.2.0 and 16.2.9 and all have that problem, only rolling back to 16.1.7 fixes it.

**Comment by ken-spencer** [comment]
So far seems to be resolved in canary.

**Comment by icyJoseph** [comment]
@BruceHubbard - try with `next@canary` pls, we have done some fixes to Pages Router, that got affected by the Next.js Adapter API, but AFAIK it hasn't landed on stable just yet.

**Comment by BruceHubbard** [comment]
When I run with the latest Canary (16.3.0-canary.30) I get an swc error:

`Uncaught Error: Cannot find module '@swc/helpers/_/_wrap_reg_exp'`

Looks like that helper isn't in `@swc/helpers@0.5.15` which is being pulled in by next

**Comment by icyJoseph** [comment]
Hi, that's not the latest canary, please do install `next@canary`, we are in `16.3.0-canary.47` at the time of writing.

**Comment by BruceHubbard** [comment]
I tried `canary.47` but get the same error (which is happening on the server):

`index.tsx:951 Uncaught Error: Cannot find module '@swc/helpers/_/_wrap_reg_exp'`

and then on the client in addition to that error I see the error:

`WebSocket connection to 'wss://workday.localqa.vndly.com/_next/hmr' failed:`

10-12 times and then the page refreshes.  This is after `rm -rf .next` and `npm install` and that version shows in the console output so it's definitely on `canary.47`.  The server error is weird I tried to comment out code to try and isolate the problem but it seems to be caused by certain imports of local files.  If I remove the import the error goes away (but not the websocket one) but even commenting out all of the code in the included file does not fix the problem, only removing the import.

**Comment by icyJoseph** [comment]
@BruceHubbard this looks like an entirely different issue. Any change you can try to isolate to a minimal repro? I am about to close this issue whenever the fix lands on stable.

My motivation for a new issue on your end:

- symptoms are not the same
- we know nothing of your setup, besides Webpack and Pages Router?
- we have no repository to try to replicate

**Comment by BruceHubbard** [comment]
@icyJoseph Yep sounds good.  I'll try to get a repo to reproduce it and open a different issue.

**Comment by edsztukowski** [comment]
The latest canary version fixed the problem for me.

**Comment by sanicode** [comment]
this patches work for me : 
```
diff --git a/node_modules/next/dist/client/dev/debug-channel.js b/node_modules/next/dist/client/dev/debug-channel.js
index b4f67e7..72ac8c8 100644
--- a/node_modules/next/dist/client/dev/debug-channel.js
+++ b/node_modules/next/dist/client/dev/debug-channel.js
@@ -59,7 +59,12 @@ function wasServedFromCache() {
     try {
         // There is exactly one PerformanceNavigationTiming entry per page load.
         const entry = performance.getEntriesByType('navigation')[0];
-        return entry?.transferSize === 0;
+        if (!entry) return false;
+        // Firefox reports transferSize===0 during streaming, causing false positives.
+        // Use two signals that only fire on a real cache restore:
+        // - type==='back_forward' for browser-history navigation
+        // - responseStart===0 && responseEnd>0 for Safari tab duplication
+        return entry.type === 'back_forward' || (entry.responseStart === 0 && entry.responseEnd > 0);
     } catch  {
         return false;
     }
```

**Comment by grgcnnr** [comment]
Fixed in 16.3 canary for me too. bring on the release.

**Comment by mischnic** [comment]
Closing this as it's fixed already.
You can try using `next@preview` for a preview release of 16.3

**Comment by jimrandomh** [comment]
Can this be backported to 16.2? It's still present as of 16.2.10, and this bug is quite critical if it manifests (not only does it make Firefox and Safari users unable to load the site, it causes them to go into a DDoS-y refresh loop).

**Comment by BruceHubbard** [comment]
I figured out my problem above.

After bailing on `16.2.7` after my problems above I now tried again this time with `16.2.12`.  I encountered a similar error in the browser while developing:

`'wss://<my_custom_domain>/_next/webpack-hmr' failed`

and that happens about 10 times and then the browser auto-refreshes.  Somewhere between 16.1.7 and 16.2.7 something got more strict when using a custom domain during local development and I just needed to set the `allowedDevOrigins` property in my `next.config.js` and now everything works properly.  Just putting it here in case someone hits this issue with a similar error.

**Comment by piofinn** [comment]
@BruceHubbard can you tell me more about how you fixed your issue? I'm currently getting the same (or very similar) error as you about `swc`:

> `Module not found: Can't resolve '@swc/helpers/_/_wrap_reg_exp'`

This is on 16.3.0, if that matters. I'm not sure if I understood you completely, but I want to try your fix before I open a new issue.

**Comment by BruceHubbard** [comment]
@piofinn Are you using a custom url for local development (not localhost but something custom)?  For me that was the problem and then I had to add `allowedDevOrigins` to my `next.config.js`: https://nextjs.org/docs/app/api-reference/config/next-config-js/allowedDevOrigins
