### ISSUE TITLE
Error: Cannot find module '../../webpack-runtime.js' in next.config.js due to Webpack v5

### ISSUE THREAD

**Issue by deadcoder0904** [vercel/next.js#28111]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next export

### Describe the Bug

I have a post-script for Next.js to generate RSS feed that looks like:

```js
if (!options.dev && options.isServer) {
	const originalEntry = config.entry

	config.entry = async () => {
		const entries = { ...(await originalEntry()) }
		entries['./scripts/build-rss'] = './scripts/build-rss.js'
		return entries
	}
}
```

It gives an error on Next v11.1.0 which uses Webpack v5 underhood saying:

> Error: Cannot find module '../../webpack-runtime.js'

It used to work on Webpack v4 (or Next v10) before. Even Tailwind Blog does it that way & it works for them as they are on the old version -> https://github.com/tailwindlabs/blog.tailwindcss.com/blob/master/next.config.js#L85-L93

### Expected Behavior

It should work on Next v11.1.0

### To Reproduce

See the **main** branch to see it not working on Next v11 which uses Webpack v5 -> https://github.com/deadcoder0904/next-script-rss-error/tree/main

See the **old-version** branch to see it working on Next v10 which uses Webpack v4 -> https://github.com/deadcoder0904/next-script-rss-error/tree/old-version

Install the dependencies & make sure perfect dependencies are installed, i.e, v11 for **main** branch & v10 for **old-version** branch as they change when using `git checkout`.

And then run `npm run build:development` which runs `next build && npm run export && npm run rss:development`

**Comment by Manubi** [comment]
Did you find out how to fix this? :)

**Comment by deadcoder0904** [comment]
@Manubi nope. This is hella weird. Nobody knows.

@leerob used `.mjs` files but it won't work for me without duplicating code. I have functions that use absolute imports using `@/utils/mdx` to generate RSS so I can't use `.mjs`

So now the alternative I'm trying is to generate `rss`, `sitemap` & other stuff in `pages/tags.tsx` file in `getStaticProps` but I prefer this method.

Would love a solution to this :)

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
