### ISSUE TITLE
Error Prerendering Not-Found page 

### ISSUE THREAD

**Issue by Kamasah-Dickson** [vercel/next.js#60297]
### Link to the code that reproduces this issue

https://github.com/SATSAT-Ai/SATSAT-Ai

### To Reproduce

1. npm i
2. npm run build

### Current vs. Expected behavior

the error is about pre-rendring of the not-found page. the not-found page is at app/not-found.
![294646764-eef2f6eb-9ca3-4d7b-b066-a2a9bf1cf692](https://github.com/vercel/next.js/assets/86136379/84d26776-bc13-4e8c-9a20-6d28a0f32fac)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro   
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

### Additional context

running build in my ide on version 13.5.6 caught the error, I updated to next 14.0.4 and not errors were caught while building but when I pushed to Vercel, compilation failed due to pre-rendering of the not-found page.

**Comment by waigel** [comment]
Duplicate of #58576

**Comment by Kamasah-Dickson** [comment]
> Duplicate of #58576

I made a mistake and it was closed by bot

**Comment by Kamasah-Dickson** [comment]
looks like when i use version 13.5.6 I am able to catch the error when i run npm run build locally and even vercel does not catch the error. I upgraded to Next 14 to see it the errors would be solved and there were no errors locally when i run npm build locally but vercel is able to detect the an error when building.

**Comment by Kamasah-Dickson** [comment]
This is how the error looks like when  vercel is compiling but there is nothing wrong with the /not-found page it is also in the right directory app/not-found.

![download](https://github.com/vercel/next.js/assets/86136379/93ea175c-8a81-4c9f-9eda-a4a72f19840a)

**Comment by Kamasah-Dickson** [comment]
I have been able to fix the problem preventing me to deploy the project but there is still an error which i think is not from my project but if it is not really a big deal I can close the issue.

![download](https://github.com/vercel/next.js/assets/86136379/5c649093-d1eb-4f9f-8d01-3d726188d461)
