### ISSUE TITLE
Turbopack generates external module references with hashes that don't match installed packages when node_modules structure differs

### ISSUE THREAD

**Issue by yWilliamLima** [vercel/next.js#87737]
### Link to the code that reproduces this issue

https://github.com/Aluisio/test-styled-components

### To Reproduce

1. Create a Next.js 16.1.1+ project with OpenTelemetry instrumentation
2. Add `instrumentation.ts` file that imports `@opentelemetry/auto-instrumentations-node`
3. Build the project in a CI/CD environment (e.g., GitHub Actions) using `pnpm install --frozen-lockfile` followed by `next build`
4. Create a tar.gz archive **excluding** `node_modules` directory
5. Extract the tar.gz in a different environment
6. Run `pnpm install` to install dependencies
7. Run `next start` to start the production server

### Expected Behavior

The application should start successfully, loading the instrumentation hook without errors.

### Current Behavior

The application fails to start with the following error:

```
Error: An error occurred while loading instrumentation hook: Failed to load external module require-in-the-middle-a99415fa67232f7f: Error: Cannot find module 'require-in-the-middle-a99415fa67232f7f'
Require stack:
- /path/to/.next/server/chunks/[root-of-the-server]__39a9a9e1._.js
- /path/to/.next/server/chunks/[turbopack]_runtime.js
- /path/to/.next/server/instrumentation.js
```

The Turbopack bundler generates external module references with hashes (e.g., `require-in-the-middle-a99415fa67232f7f`) based on the `node_modules` structure during the build. When dependencies are reinstalled in a different environment, the `node_modules` structure may differ (especially with pnpm's symlink/hoisting behavior), causing the hash to not match the actual installed package.

### Workaround

Using `--webpack` flag in the build script resolves the issue:

```json
{
  "scripts": {
    "build": "next build --webpack"
  }
}
```

However, this defeats the purpose of using Turbopack as the default bundler in Next.js 16.

### Provide environment information

```bash
**Operating System:**

- Platform: linux
- Arch: x64
- Version: Ubuntu (GitHub Actions runner)

**Binaries:**

- Node: 24.11.1
- pnpm: 10.25.0

**Relevant Packages:**

- next: 16.1.1
- react: 19.2.3
- react-dom: 19.2.3
- @opentelemetry/auto-instrumentations-node: 0.67.3
- require-in-the-middle: 8.0.1
- import-in-the-middle: 2.0.1
```

### Which area(s) are affected? (Select all that apply)

Output

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

**Next.js Config:**

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
```

**Note:** The issue occurs even with `serverExternalPackages` configured:

```javascript
const nextConfig = {
  serverExternalPackages: [
    "require-in-the-middle",
    "import-in-the-middle",
    "@opentelemetry/auto-instrumentations-node",
    // ... other OpenTelemetry packages
  ],
};
```

### Why this happens

1. **Local development works**: When building and running locally, the same `node_modules` structure is used for both build and runtime, so the hashes match.

2. **CI/CD fails**: The build is created with `node_modules` structure A (from CI environment), generating hashes based on that structure. When the tar.gz is extracted and dependencies are reinstalled locally, the `node_modules` structure may be different (structure B), causing hash mismatches.

3. **Root cause**: Turbopack generates external module references with content-based hashes that depend on the `node_modules` directory structure. This is problematic when:
   - Using pnpm (which uses symlinks and hoisting)
   - Building in one environment and running in another
   - Reinstalling dependencies after extracting a build artifact

### Impact

This issue affects:

- Projects using OpenTelemetry instrumentation (common in production applications)
- CI/CD pipelines that build artifacts without `node_modules` and reinstall dependencies later
- Projects using pnpm as package manager
- Any project that needs to build in one environment and run in another

### Testing

Tested against:

- Next.js 16.1.1 (current)
- Next.js 16.0.0 (same issue)
- Next.js 15.x with Webpack (works correctly)

The issue appears to be introduced when Turbopack became the default bundler for production builds in Next.js 16.

**Comment by jitendra-bhandure** [comment]
getting same error, any update on this

_Edit by maintainer bot: Comment was **automatically** minimized because it was considered unhelpful. (If you think this was by mistake, let us know). Please only comment if it adds context to the issue. If you want to express that you have the same problem, use the upvote 👍 on the issue description or subscribe to the issue for updates. Thanks!_

**Comment by arolariu** [comment]
Based on my comment from https://github.com/vercel/next.js/issues/87686#issuecomment-3690396866

Can you try with the following config in your `next.config.ts` file? CC: @yWilliamLima, @jitendra-bhandure 

```ts
  transpilePackages: ["import-in-the-middle", "require-in-the-middle"],
```

I'm also running the `@opentelemetry/` packages in my project and this fixed it for me.
I didn't need to configure any `serverExternalPackages` array, though - it worked with just `transpilePackages`.

**Comment by pascual-cano-allhuman** [comment]
is there any way of opting out from making the node module dependencies part of the build? We should be able to have a clean build and install the dependencies separately. This idea of embedding packages as part of the build with a hash is also causing problem to us and it looks like a really unconventional pattern.

**Comment by hasankhurshid29** [comment]
`[Error: ENOENT: no such file or directory, open '[root]/public/.next/node_modules/@hookform/resolvers-7a17b6f70f9232cf'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '[root]/public/.next/node_modules/@hookform/resolvers-7a17b6f70f9232cf'
}
Error: ENOENT: no such file or directory, open '[root]/public/.next/node_modules/@hookform/resolvers-7a17b6f70f9232cf'`

I am also having this error on ci when upgrading to 16.1.1 whereas on 16.0.10 everything was fine 
Also one difference I noticed is in 16.1.1 in .next folder we have node_modules whereas 16.0.10 doesn't have node_modules

**Comment by taletski** [comment]
@pascual-cano-allhuman I believe you can force packages to symlink to `node_modules` instead of bundling them into `.next` with [`serverExternalPackages`](https://nextjs.org/docs/app/api-reference/config/next-config-js/serverExternalPackages) since Next v16.1. Don't think that this is possible for the entire `node_modules` though.

**Comment by taletski** [comment]
@yWilliamLima, as discussed in #87686, the issue seems to be broken symlinks for `require-in-the-middle` and its downstream dependencies (e.g. `@opentelemetry/*`).

Since you’re using `tar`, symlinks inside `.next` should be preserved. This makes me suspect that the symlinks point to a different location than where the packages are actually installed in the runtime container.

Could you please share the directory structure for both the **build** container and the **runtime** container? Specifically, it would be helpful to see:
- Where `@opentelemetry/*` is installed in each container
- Where `.next/node_modules/@opentelemetry/*` symlinks point to at **runtime** container

**Comment by pascual-cano-allhuman** [comment]
@taletski In our project we are not using Server Components, we are entirely in the Pages Router side. How comes that the newest version is still bundling dependencies? Shouldn't be able to opt out of bundling with a single config flag without keeping the list of exceptions manually?
This behaviour seems related to turbopack in production. The dependencies are not bundled if we add the --webpack modifier.

**Comment by taletski** [comment]
@pascual-cano-allhuman I agree that having a flag for full opt out might be beneficial in some cases. Happy to discuss in a separate feature request issue to have more room for it, to have more chances to convince maintainers and to keep the scope narrow here.

**Comment by pascual-cano-allhuman** [comment]
I created a discussion about being able to opt out from external packages completely: #87891

**Comment by karlismelderis-mckinsey** [comment]
> Since you’re using tar, symlinks inside .next should be preserved. This makes me suspect that the symlinks point to a different location than where the packages are actually installed in the runtime container.

I followed this hint in our project and found that symlinks in `.next/node_modules` where pointing to nowhere

had to fix node_modules `COPY` target in our Dockerfile and everything is back to normal

In our case had to add extra `../../` to preserve node_modules "relative" distance from `.next/node_modules` and avoid recreating symlinks

**Comment by yWilliamLima** [comment]
The issue was actually the symbolic links created in .next/node_modules. Adjusting the compression command solved the problem. Thanks!

**Comment by mischnic** [comment]
So is this issue resolved?
It's unfortunate that your setup broke here, but https://github.com/vercel/next.js/pull/86375 describes the benefits of this approach.

**Comment by msheakoski** [comment]
I was also experiencing this issue since 16.1 while building in a monorepo and using `turbo prune`. Here is how I fixed it:

I have a basic Turborepo monorepo:
```
apps/
  myapp/
packages/
  leftpad/
pnpm-lock.yaml
```

In my CI/CD the workflow looks like:
```
turbo prune --scope=myapp --out-dir=pruned/myapp
pushd pruned/myapp/apps/myapp
pnpm install
pnpm build
popd
```

I noticed the below warning while building which clued me into what was happening. Because my pruned monorepo was inside of my main monorepo, when Next.js was building, the transitive dependencies in `.next/node_modules` were symlinking to `PROJECT_DIR/node_modules` instead of `PROJECT_DIR/pruned/myapp/node_modules` and when I copied only the pruned monorepo after building, of course the symlinks were no longer pointing to the correct place.

```
⚠ Warning: Next.js inferred your workspace root, but it may not be correct.
 We detected multiple lockfiles and selected the directory of PROJECT_DIR/pnpm-lock.yaml as the root directory.
 To silence this warning, set `turbopack.root` in your Next.js config, or consider removing one of the lockfiles if it's not needed.
   See https://nextjs.org/docs/app/api-reference/config/next-config-js/turbopack#root-directory for more information.
 Detected additional lockfiles: 
   * PROJECT_DIR/pruned/myapp/pnpm-lock.yaml
```

Following the advice of the warning above, I added `turbopack.root` to my next.config.ts and after that, transitive dependencies in `.next/node_modules` correctly symlinked to `PROJECT_DIR/pruned/myapp/node_modules` after building:
```typescript
let nextConfig: NextConfig = {
  turbopack: {
    root: path.join(__dirname, "../.."),
  },
}
```

**Comment by flodev** [comment]
I have the same monorepo structure as @msheakoski in my project
```
apps/
  myapp/
packages/
  leftpad/
```

locally with npm run dev everything works fine.
In our Dockerfile then we had the issue and the symlinks were not copied and if they would they would have been wrong.

So we are doing the following

```
COPY app/.next/standalone/app ./
COPY app/.next/standalone/node_modules ./node_modules
COPY app/.next/static ./.next/static
COPY app/public ./public
```

as you may notice we didnt copy the app/.next/node_modules.
So to have the symlinks eventually we do the following:

```
RUN if [ -d ".next/node_modules" ]; then \
        cd node_modules && \
        for link in ../.next/node_modules/*; do \
            if [ -L "$link" ]; then \
                hashed_name=$(basename "$link"); \
                pkg_name=$(echo "$hashed_name" | sed 's/-[0-9a-f]*$//'); \
                if [ -d "$pkg_name" ] && [ ! -e "$hashed_name" ]; then \
                    echo "Creating symlink: $hashed_name -> $pkg_name"; \
                    ln -sf "$pkg_name" "$hashed_name"; \
                fi; \
            fi; \
        done; \
    fi
```

this basically lists symlinks in .next/node_modules and creates then those symlinks in the node_modules folder so that the hashed packages point to the original packages.  
import-in-the-middle-ac114f323ad7e863 -> import-in-the-middle

**Comment by arolariu** [comment]
> I have the same monorepo structure as @msheakoski in my project
> ```
> apps/
>   myapp/
> packages/
>   leftpad/
> ```
> 
> locally with npm run dev everything works fine.
> In our Dockerfile then we had the issue and the symlinks were not copied and if they would they would have been wrong.
> 
> So we are doing the following
> 
> ```
> COPY app/.next/standalone/app ./
> COPY app/.next/standalone/node_modules ./node_modules
> COPY app/.next/static ./.next/static
> COPY app/public ./public
> ```
> 
> as you may notice we didnt copy the app/.next/node_modules.
> So to have the symlinks eventually we do the following:
> 
> ```
> RUN if [ -d ".next/node_modules" ]; then \
>         cd node_modules && \
>         for link in ../.next/node_modules/*; do \
>             if [ -L "$link" ]; then \
>                 hashed_name=$(basename "$link"); \
>                 pkg_name=$(echo "$hashed_name" | sed 's/-[0-9a-f]*$//'); \
>                 if [ -d "$pkg_name" ] && [ ! -e "$hashed_name" ]; then \
>                     echo "Creating symlink: $hashed_name -> $pkg_name"; \
>                     ln -sf "$pkg_name" "$hashed_name"; \
>                 fi; \
>             fi; \
>         done; \
>     fi
> ```
> 
> this basically lists symlinks in .next/node_modules and creates then those symlinks in the node_modules folder so that the hashed packages point to the original packages.  
> import-in-the-middle-ac114f323ad7e863 -> import-in-the-middle

This seems like an awful developer experience...

Either we're not understanding properly this change or the documentation of this breaking change is very bad.

A developer shouldn't have to "patch" his dependencies to work.

**Comment by mischnic** [comment]
> So we are doing the following
> ```
> COPY app/.next/standalone/app ./
> COPY app/.next/standalone/node_modules ./node_modules
> COPY app/.next/static ./.next/static
> COPY app/public ./public
> ```
> as you may notice we didnt copy the app/.next/node_modules.

But `app/.next/standalone/app/.next/node_modules` should be copied over that way.

Could you share a small reproduction with a Dockerfile so I reproduce that?

**Comment by flodev** [comment]
> This seems like an awful developer experience...

I second that.

Here comes a minimal reproducible example @mischnic.

[https://github.com/flodev/next-dependency-bug](https://github.com/flodev/next-dependency-bug)

its basically a turbo mono repo with a dockerfile that includes pino.

**Comment by avens19** [comment]
This is my workaround script which works with namespaced packages:

```
RUN if [ -d ".next/node_modules" ]; then \
        cd .next/node_modules && \
        for link in ./*; do \
            if [ -L "$link" ]; then \
                target=$(readlink "$link"); \
                new_target=$(echo "$target" | sed 's#^../../../../../#../../#'); \
                echo "Creating symlink: $link -> $new_target"; \
                rm "$link"; \
                ln -s "$new_target" "$link"; \
            fi; \
        done; \
        for link in ./**/*; do \
            if [ -L "$link" ]; then \
                target=$(readlink "$link"); \
                new_target=$(echo "$target" | sed 's#^../../../../../#../../#'); \
                echo "Creating symlink: $link -> $new_target"; \
                rm "$link"; \
                ln -s "$new_target" "$link"; \
            fi; \
        done; \
    fi
```

**Comment by paralin** [comment]
Bun + TurboPack with a basic app is broken: https://gist.github.com/paralin/b6122f55896eb40b88aeebb211c7e496

**Comment by Koyamie** [comment]
Any fix for this?

_Edit by maintainer bot: Comment was **automatically** minimized because it was considered unhelpful. (If you think this was by mistake, let us know). Please only comment if it adds context to the issue. If you want to express that you have the same problem, use the upvote 👍 on the issue description or subscribe to the issue for updates. Thanks!_

**Comment by websaid** [comment]
We're hitting this exact issue in a monorepo (pnpm workspaces) deploying to a Linux-based hosting environment where **symlinks are not preserved** during the packaging/deployment process. After trying to fix this rather less successful together with copilot, I've let copliot create the following summary which might help to fix the issue:

---

## Our Project

- Next.js 16.2.4 with Turbopack (production build)
- pnpm monorepo with workspace packages

## The Problem in Detail

When building with Turbopack, any package listed in `serverExternalPackages` (or auto-externalized by Turbopack) gets:

1. A **content-hash suffix** appended to the package name (e.g. `@react-pdf/renderer-e8022cf52cffe77f`)
2. A **relative symlink** created at `.next/node_modules/@react-pdf/renderer-e8022cf52cffe77f` pointing to the actual package in the pnpm store:
   ```
   ../../../../../node_modules/.pnpm/@react-pdf+renderer@4.5.1_react@19.2.5/node_modules/@react-pdf/renderer
   ```
3. Server chunks reference the hashed name: `require("@react-pdf/renderer-e8022cf52cffe77f")`

This breaks in any deployment scenario where:

- Symlinks are not preserved during packaging (e.g. certain archive formats, artifact stores)
- The relative path distance between `.next/node_modules` and the package store changes
- The `node_modules` structure differs between build and runtime (as described in the original issue)

## Key Findings

- **`serverExternalPackages` does not prevent the hash** — it still generates hash-suffixed externals with symlinks
- **`output: "standalone"`** copies the dependency tree but **still uses symlinks** for the `.next/node_modules/` hash references (it does NOT dereference them)
- **`transpilePackages`** can force bundling instead of externalizing, which avoids the symlink entirely — but it seems not to be reliable, this didn't fix the problem for me.
- The hash appears to be derived from the resolved canonical path through pnpm's `.pnpm/` store, not from the package content itself — meaning the same package version can produce different hashes depending on the `node_modules` layout

## Suggested Fix Directions

1. **For `output: "standalone"`**: The NFT trace already copies the actual package files. The symlinks in `.next/node_modules/` should be **dereferenced** (replaced with copies or junctions) in the standalone output, since the whole point of standalone is to produce a self-contained deployment artifact.

2. **General fix**: Provide a configuration option to disable hash-suffixed externals entirely. When a package is in `serverExternalPackages`, it should be referenced by its bare specifier (`@react-pdf/renderer`) and resolved via standard Node.js module resolution at runtime — no symlinks needed.

3. **Alternative**: Instead of symlinks, write a `package.json` with an `exports` map in `.next/node_modules/` that redirects the hashed name to the real package. This would survive environments without symlink support.

## Workarounds We've Explored

| Approach                                                          | Result                                                                                                      |
| ----------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------- |
| `serverExternalPackages`                                          | ❌ Still produces hash + symlink                                                                            |
| Removing `serverExternalPackages` (let Turbopack decide)          | ❌ Turbopack auto-externalizes the package anyway, still produces hash + symlink                            |
| `transpilePackages`                                               | ❌ Did not prevent Turbopack from externalizing and hashing the package                                     |
| `output: "standalone"`                                            | ⚠️ Symlink resolves within standalone, but still breaks without symlink support                             |
| `next build --webpack`                                            | ✅ No hash-suffixed externals, but loses Turbopack benefits                                                 |
| Pre-bundling the package with tsup/esbuild in a workspace package | ✅ Eliminates the external import from the app's perspective                                                |


## Reproduction Note

This is trivially reproducible in any pnpm monorepo where a workspace package imports from an npm dependency that Turbopack decides to externalize. The workspace indirection causes a different resolution path → different hash → the symlink approach becomes the only way to resolve it at runtime.

**Comment by ellingtontrevor642-art** [comment]
That is a valid point updating accordingly

**Comment by avens19** [comment]
Ya this got so much worse when I switched to pnpm and their isolated linking. For now I'm just putting the entire monorepo node_modules in my docker image and maintaining the monorepo path inside the docker image. The unfortunate thing is that the .pnpm folder looks different when you install with just the required packages (we use nx which generates a scoped package.json). I even tried copying the symlink targets into `.next/node_modules` but the packages rely on other hoisted dependencies so that was also a no-go. Likely the best course of action would be to use pnpm install --node-linker=hoisted, then run the build, then do a new pnpm install with the scoped package.json also with --node-linker=hoisted. I can report back if this works. I'll still need to either maintain the folder structure in the docker image or use my symlink rewrite fix from above

**Comment by wisdomstar94** [comment]
It was normal in next `v16.0.10`. 
but after updating to next `v16.2.6`, I got the same issue. Hope it's resolved soon..

Also, I'm using yarn v4.

**Comment by CS-Rose** [comment]
Confirming this still reproduces on **Next 16.2.1** with `@prisma/client@^7.5.0`. Adding a couple data points I didn't see in the thread:

**Environment:** Windows Server 2022 (on-prem IIS reverse proxy → standalone bundle, not Docker), Node 20, npm. So this isn't pnpm-specific or container-specific — the same hashed-module bug occurs on a plain `npm ci` + `next build` + standalone output on Windows.

**Error shape:**
```
Error: Failed to load external module @prisma/client-2c3a283f134fdcb6/runtime/client: Cannot find module '@prisma/client-2c3a283f134fdcb6/runtime/client'
Require stack:
  - .next/server/chunks/[root-of-the-server]__08x63m3._.js
  - .next/server/chunks/[turbopack]_runtime.js
  - .next/server/app/api/admin/stats/route.js
    at Context.externalRequire (.next/server/chunks/[turbopack]_runtime.js:624:15)
```

The build succeeds; the failure is at request time when the route module evaluates.

**`serverExternalPackages` does not work around it.** Adding `serverExternalPackages: ["@prisma/client", "@prisma/adapter-mssql"]` to `next.config.ts` produces the *exact same* hashed-name error. Turbopack appears to apply the content hash before/independently of the externalization, so declaring the package external doesn't bypass it. Worth flagging since `serverExternalPackages` is the documented escape hatch for runtime-loaded server deps.

**`--webpack` workaround confirmed working.** `next build --webpack` produces a working standalone bundle (and runs Next's proper file tracing, which Turbopack skips — our zipped bundle went from 7 MB broken to 19 MB working). Pinning that in `package.json` for now.

**Comment by mtirmbenton** [comment]
Is there any update to this? I don't see any good solutions to acommodate this from a monorepo (we use nx).

**Comment by avens19** [comment]
I ended up switching to a standalone build and it's working perfectly (with a much smaller image size). It creates a fully self-contained node_modules inside the standalone folder

**Comment by mtirmbenton** [comment]
When you say standalone do you mean you stopped using a monorepo or are you referring to some other nextjs config?

**Comment by avens19** [comment]
https://nextjs.org/docs/pages/api-reference/config/next-config-js/output#automatically-copying-traced-files

**Comment by mtirmbenton** [comment]
avens19, I appreciate the link, but I am running into the same situation as websaid above. Even after using standalone output the links are still created. Are you using a monorepo structure?

**Comment by avens19** [comment]
Yes I'm using a monorepo. I found that symlinks are created, but they resolve to the .pnpm folder inside node_modules inside the standalone folder, not to the root monorepo node_modules. So the standalone folder is portable. Is that not what you're seeing? My docker file simply copies the standalone folder and then copies public and static into it and it's working great. What error are you seeing when you do this?

**Comment by mtirmbenton** [comment]
I am using npm and my links are going to the root of the project.

**Comment by cipriancaba** [comment]
Same failure on Vercel deploys with bun isolated installs — narrowed down: 16.3 drops NFT target files for ESM externals only (16.2.9 is fine)

We hit this exact class of failure deploying a Turborepo monorepo (bun with isolated/pnpm-style store at node_modules/.bun) to Vercel. Sharing since maintainers noted a lack of clean repros, and we could isolate a precise 16.2.9-vs-16.3 delta.

Setup: next@16.3.0-preview.5 (also reproduced through the 16.3 canary line; 16.2.9 is clean), App Router, Turbopack build, deployed to Vercel.

What we see: Turbopack externalizes server packages behind content-hashed aliases and emits symlinks for them — that part is by design and works on 16.2.9, where each route's .nft.json traces both the alias symlink and its store target files. On 16.3, target files are traced only for CJS externals. For ESM externals, the .nft.json contains only the alias symlink:

For our /auth route on the identical codebase:

```
┌───────────────────────────────────────────────────┬───────────────┬──────────────────────────────────┐
│          external (hashed alias emitted)          │ module format │ target files in .nft.json (16.3) │
├───────────────────────────────────────────────────┼───────────────┼──────────────────────────────────┤
│ pg, @prisma/client runtime, require-in-the-middle │ CJS           │ ✅ traced                        │
├───────────────────────────────────────────────────┼───────────────┼──────────────────────────────────┤
│ resend, ai, @ai-sdk/google, postcss, prettier     │ ESM           │ ❌ zero — alias symlink only     │
└───────────────────────────────────────────────────┴───────────────┴──────────────────────────────────┘
```

grep -rl '.bun/resend' .next --include='*.nft.json' → empty on 16.3, non-empty on 16.2.9.

Consequence on Vercel: the lambda is packed strictly from the NFT trace, so /var/task contains a dangling resend-<hash> symlink → ERR_MODULE_NOT_FOUND → HTTP 500 for every server action / RSC importing any ESM external. Local next start hides it because the real store exists on disk — only deploys break.

Suspected origin: the 16.3-only endpoint-tracing rewrite (crates/next-api/src/nft.rs, #94224 chain). #93849 (pino + pnpm on Vercel) looks like the same bug and was bot-closed for a missing repro.

Workaround we're shipping in case it helps others: a post-next build script that walks the alias symlinks the build emits under .next/node_modules and, for each alias whose store target is missing from a .nft.json, appends the target package's dependency closure (files + the isolated-store symlink graph). That restores green E2E on Vercel.

**Comment by ClearflySystems** [comment]
6 months and still not fixed??? My build fails because it's looking for @prisma/client-##########.ts but the generated prisma file is just prisma/client.ts. Had to resort to webpack, which makes turbo pointless and redundant. This eco-system should not be this fragile when it comes to simply building a deployment package.

**Comment by cipriancaba** [comment]
Follow-up to my comment above: we've now isolated our Vercel/bun variant at chunk level and it turned out to be a distinct, more precise trigger than the "all ESM externals" framing — an ESM `serverExternalPackage` reached via a `'use client'` component lands in a shared SSR-layer chunk, and endpoints that pull that shared chunk without owning the import get the alias without its store target files. Filed separately with the full mechanism, per-chunk evidence, and a partial minimal repro (the last mile needs app-scale chunk bin-packing, which is likely why clean repros are scarce here): #95815

**Comment by chungweileong94** [comment]
This is probably one of the annoying bugs ever, where in my case, I have issues with multiple packages, where it keeps generating some broken symlinks under `.next/standalone/apps/web/.next/node_modules`.

Thanks to @cipriancaba’s workaround ideal, I figured out a way to patch the package symlinks. I'm going to be honest, AI wrote 100% of the code. In case someone needs it, here is the script: https://gist.github.com/chungweileong94/6ebb8fb6ad1affbf58b84d88ebe4c101. 

I would say fallback to Webpack is the stable way to go, and wait for the actual fix from the NextJS team.

**Comment by codeagencybe** [comment]
Any news yet on this? It's been quite some time. Is there anything in progress /ETA?

**Comment by chungweileong94** [comment]
> Any news yet on this? It's been quite some time. Is there anything in progress /ETA?

It's fixed in the latest 16.3 version. At least from what I can tell.

**Comment by cachho** [comment]
> > Any news yet on this? It's been quite some time. Is there anything in progress /ETA?
> 
> It's fixed in the latest 16.3 version. At least from what I can tell.

I still get

```
> Build error occurred
Error: ENOENT: no such file or directory, open '/vercel/path0/.next/next-server.js.nft.json'
    at ignore-listed frames {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/vercel/path0/.next/next-server.js.nft.json'
}
Error: Command "timeout 45m next build -d --turbopack" exited with 1
```

when upgrading to 16.3.3 - pretty sure that was related to this bug or I wouldn't be subscribed to this issue. Works in `16.1.7`.

**Comment by christophsaile** [comment]
Same here, when updating from `next: 16.2.11` to `next: 16.3.4` I get the following error when I open the vercel preview link in the PR.

(error extracted from vercel logs)
```
2026-09-01 12:23:29.021 [error] Error running the exported Web Handler: Error: Failed to load external module require-in-the-middle-27cc81ffbded37e7: Error: Cannot find module 'require-in-the-middle-27cc81ffbded37e7'
Require stack:
- /var/task/.next/server/chunks/[root-of-the-server]__0vumsna._.js
- /var/task/.next/server/chunks/[turbopack]_runtime.js
- /var/task/.next/server/middleware.js
- /var/task/___next_launcher.cjs
- /opt/rust/nodejs.js
    at Context.externalRequire [as x] (.next/server/chunks/[turbopack]_runtime.js:572:15)
    at module evaluation (.next/server/chunks/[root-of-the-server]__0vumsna._.js:2:2197)
    at instantiateModule (.next/server/chunks/[turbopack]_runtime.js:757:9)
    at getOrInstantiateModuleFromParent (.next/server/chunks/[turbopack]_runtime.js:781:12)
    at Context.esmImport [as i] (.next/server/chunks/[turbopack]_runtime.js:352:20)
    at module evaluation (.next/server/chunks/0za7_12gotn1._.js:2:65429)
    at instantiateModule (.next/server/chunks/[turbopack]_runtime.js:757:9)
    at getOrInstantiateModuleFromParent (.next/server/chunks/[turbopack]_runtime.js:781:12)
    at Context.commonJsRequire [as r] (.next/server/chunks/[turbopack]_runtime.js:373:12)
    at module evaluation (.next/server/chunks/0za7_12gotn1._.js:22:42050)
```
