### ISSUE TITLE
Error: Cannot find module 'react-is' - Production build

### ISSUE THREAD

**Issue by gunnartorfis** [vercel/next.js#30705]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS, M1

### How are you deploying your application?

next start

### Describe the Bug

next dev is working as expected. 
When I run `next build` followed by `next run` and visit the URL, I get the following error in the console and a large part of the application renders blank. 

<img width="651" alt="image" src="https://user-images.githubusercontent.com/5333875/139594681-47f8afbb-ae2d-4025-a45f-34825a4df8e5.png">

### Expected Behavior

It probably shouldn't throw this error, unless I'm missing something in my setup. 

### To Reproduce

There isn't much more context I can give, I think. 
I'm not sure if it helps to get my entire package.json but I will of course post it if someone needs it for debugging.

**Comment by imranbarbhuiya** [comment]
Hi @gunnartorfis, do you happen to have a repository that reproduces this issue?

**Comment by imranbarbhuiya** [comment]
> I'm not sure if it helps to get my entire package.json but I will of course post it if someone needs it for debugging.

Do you've that dependency in `dependency` list? **Not in dev dep**
Run `npm install` again and check.

Else send your package.json page here or if you have a repo which reproduces this issue then send that.

**Comment by gunnartorfis** [comment]
I just tried creating a fresh new Next project, building and running, and I get the same error! 👀 

**Steps to reproduce**

1. `yarn create next-app`
2. `yarn build`
3. `yarn run`
4. Check the browser's console

A few of my dependencies list react-is as their dependency (not even peer dependency), so it should be installed.  
Even installing it myself doesn't do the job.

**Comment by imranbarbhuiya** [comment]
@gunnartorfis, sorry, but I'm not able to reproduce your issue. I've created next app with the following steps.

- `yarn create next-app`
- `yarn build`
- `yarn start`


And it's working fine for me. Also, there is no script present for `yarn run` it's yarn start. If you still have the issue, try updating `nextjs` to latest (v12.0.2).

**Comment by gunnartorfis** [comment]
Hi mate, thanks for the replies. 
I did exactly that, I didn't run next directly but through yarn. I tried updating next to 12.0.2 without success.

What version of Node are you using?

**Comment by rokoroku** [comment]
Same issue here:
I found below codes from production chunk:
```
.next/serverless/chunks/726.js:        const { isValidElementType  } = __webpack_require__(Object(function webpackMissingModule() { var e = new Error("Cannot find module 'react-is'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
.next/serverless/chunks/730.js:                Object(function webpackMissingModule() { var e = new Error("Cannot find module 'undefined'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
```

Node v14.18.1
Nextjs v12.0.2

**Comment by gunnartorfis** [comment]
Its at least not tied to our Node versions then. Are you running on Mac M1 as well?

**Comment by imranbarbhuiya** [comment]
> What version of Node are you using?

I'm also using node 16.13.0. It's probably related to your OS.

**Comment by gunnartorfis** [comment]
Would be interesting to know if @rokoroku is using an M1 as well.

**Comment by pablocdev** [comment]
Same issue here in my two Next projects, using Windows 11, Node 16.13 and Next 12.0.2

![image](https://user-images.githubusercontent.com/23481169/139706447-57439e36-7f31-496c-ad1e-5bee5c5ee7f1.png)

**Comment by IgorNoskov** [comment]
Same issue, using Ubuntu 21.01, Node 14.17.6 and Next 12.0.2

**Comment by imranbarbhuiya** [comment]
Anyone of you please share your repo link here. As I'm not able to reproduce the error.

Using
- os windows 11
- node 16.13.0
- next 12.0.2

**Comment by gunnartorfis** [comment]
https://github.com/gunnartorfis/react-is-module-not-found

Here's a reproducible example. It's untouched from create-next-app.

**Comment by rokoroku** [comment]
> Would be interesting to know if @rokoroku is using an M1 as well.

No, I'm not.

**Comment by gunnartorfis** [comment]
Does anyone have an idea for a workaround?

**Comment by IgorNoskov** [comment]
I get this error, when I create a build for cypress tests with this command `NODE_ENV=test yarn build`

**Comment by mythz** [comment]
Just started getting this error today from `next export` builds which was referencing `"next": "latest"`, resolved it by downgrading to v11:

    $ npm i next@11

- Windows 10
- node v14.15.5
- Works in `11.1.2`, Cannot find module `react-is` in `12.0.2`, `12.0.11 or `12.0.0`

**Comment by avaranze** [comment]
Just upgraded Next.js to v12.0.2 and started getting this error.

- Next.js version: 12.0.2
- NodeJS version: 16.11.1
- Browser: Chrome 95.0.4638.69 (Official Build) (64-bit)
- Deployment:
	  ```
	  next build && next export -o dist && http-server --port 3000 --gzip --brotli --no-index --proxy http://localhost:3000/index.html? dist
	  ```
- Windows 10 x64 Pro

Output in Chrome console:

```
Uncaught Error: Cannot find module 'react-is'
    at main-0fa08952f8da178c.js:1
    at main-0fa08952f8da178c.js:1
    at u (main-0fa08952f8da178c.js:1)
    at Generator._invoke (main-0fa08952f8da178c.js:1)
    at Generator.forEach.e.<computed> [as next] (main-0fa08952f8da178c.js:1)
    at A (main-0fa08952f8da178c.js:1)
    at a (main-0fa08952f8da178c.js:1)
```

Let me know if I can provide any other assistance to track down the issue.

**Comment by imranbarbhuiya** [comment]
> https://github.com/gunnartorfis/react-is-module-not-found
> 
> Here's a reproducible example. It's untouched from create-next-app.

![image](https://user-images.githubusercontent.com/74945038/140462452-81644ae6-d835-4b97-a445-0d47c2257780.png)


I've cloned your repo and started, it's working fine without any error. Probably this issue is related to OS or anything else.
@gunnartorfis

**Comment by neodon** [comment]
@gunnartorfis Can you load the URL in a browser and check the console? That's where I was seeing the error.

**Comment by gunnartorfis** [comment]
Yes @neodon the screenshot in the original post is from the browser's console. 

When building with Docker I don't encounter this error, nor with Vercel. 
We've had people with various OSs and Node versions report this issue. So far in this post we've had: 
- macOS M1 Big Sur
- Windows 10
- Ubuntu 21.10
- Node 16
- Node 17
- Node 14

**Comment by pablocdev** [comment]
I've tried to reproduce the issue with a clean `npx create-next-app` and I'm not able to get this error on browser console.

Also tried to reproduce it with @gunnartorfis repo and still can not reproduce it on Windows 11, and Node 16.

![image](https://user-images.githubusercontent.com/23481169/140499278-200de482-7be6-4678-82d8-f2017bbd445e.png)

![image](https://user-images.githubusercontent.com/23481169/140499429-3af30fd8-9fbb-4cf1-9c8c-ae89ee833a91.png)

But **error is still present in both of my current projects**, which works well with Next 11.x. The problem is that both are part of a big monorepo, and cannot give public access to it.

I'm trying to create a new repo and force error, but no idea of how... Anyone can help with that?

**Comment by neodon** [comment]
Are you using npm workspaces?  I tried reproducing the issue as well in a docker container, but no luck.  The next thing I was going to try was having the Next.js app be a workspace in a project.

**Comment by gunnartorfis** [comment]
No worries! 😀
No I'm not using workspaces or monorepo whatsoever. 

I literally just created a new project in my Desktop folder and ran it up.

**Comment by psayeed1990** [comment]
Getting the same issue, same console error. Some part of my app isn't working but build is successful. It works fine in local but when deployed, Debian 11, my package.json -
`"scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint"
    },
    "dependencies": {
        "next": "12.0.2",
        "react": "17.0.2",
        "react-dom": "17.0.2",
        "react-is": "^17.0.2"
    },
    "engines": {
        "node": "16.13.0",
        "npm": "8.1.0"
    },`

**Comment by webheybro** [comment]
Same error for me, with :

- node 16
- next 12.0.3
- react 17.0.2
- react-dom 17.0.2

Work in local but not with docker...

**Comment by Tkaixiang** [comment]
Same issue here with nextjs production build (works in dev mode):
- Node 14
- next 12.0.2
- react 17.0.2
- react-dom 17.0.2

**Comment by calbrecht** [comment]
Happened to me as well :joy: 

Make sure `NODE_ENV=production` while `next build` instead of `NODE_ENV=development`.

**Comment by neodon** [comment]
@calbrecht This does not appear to be the issue, at least for me.  Changing `NODE_ENV` had no effect on the error about missing `react-is`.

**Comment by Tkaixiang** [comment]
> Happened to me as well 😂
> 
> Make sure `NODE_ENV=production` while `next build` instead of `NODE_ENV=development`.

This seems to have fixed it for me

**Comment by neodon** [comment]
@calbrecht @Tkaixiang So it looks like this actually does fix the issue for me.  I ran a `git clean -xfd` to clear my `node_modules` directory and any Next caches.  Now it works.  Thanks everyone!

**Comment by neodon** [comment]
In case anyone is interested, here is a docker-compose file that reproduces the issue:

```yaml
version: '3'

services:
  app:
    image: node:16-slim
    ports:
      - '8080:8080/tcp'
    environment:
      NODE_ENV: $NODE_ENV
    command: >-
      bash -c '
        npx create-next-app@latest app --use-npm --with-static-export
        cd app

        # Static export does not work out of the box due to the Image component
        grep -v Image pages/index.js >pages/index.js2 && mv pages/index.js2 pages/index.js

        npx next build
        npx next export

        npx http-server --proxy http://localhost:8080/index.html? out
      '
```

Drop that in a directory by itself, then run `docker-compose up`.  Open http://127.0.0.1:8080 in your browser and check the console logs after a refresh.  There should be no errors.

Hit CTRL+C to stop the container.  Next, run `NODE_ENV=development docker-compose up`.  Reloading the page should now show the error in the console.

**Comment by sandra-goag** [comment]
We're facing the same issue, but the error is only printed in development so it was really hard to find. Is there any workaround to fix this?

**Comment by DanielElport** [comment]
Same issue here, but only since we split our app into smaller chunks via webpack

**Comment by sanders-vag** [comment]
Just an update: it didn't work for me either to use NODE_ENV=production

**Comment by adikari** [comment]
I am having the same issue. setting NODE_ENV does not solve the issue.

**Comment by calbrecht** [comment]
NODE_ENV **must not** be set to `development` while building the app with `next build`, probably you would have to clear your .next directory too.

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.0.4-canary.10`, please update and give it a try!

**Comment by boba1987** [comment]
`NODE_ENV=production npm run build` worked for me

**Comment by timneutkens** [comment]
This has been released in 12.0.4

**Comment by maxmag-soft** [comment]
:( 9 hours lost to project not even being started...

$ node -v
v12.22.5
$ npm -v
7.5.2

//package.json
"react": "17.0.2",
"next": "12.0.8",

$ firebase deploy
> Build error occurred

```
(node:82295) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react'
Require stack:
- /home/mining/dev/next/.next/server/pages/_document.js
- /home/mining/dev/next/arcadia/node_modules/next/dist/server/require.js
- /home/mining/dev/next/arcadia/node_modules/next/dist/server/load-components.js
- /home/mining/dev/next/arcadia/node_modules/next/dist/build/utils.js
- /home/mining/dev/next/arcadia/node_modules/next/dist/build/worker.js
- /home/mining/dev/next/arcadia/node_modules/jest-worker/build/workers/processChild.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.689 (/home/mining/dev/next/.next/server/pages/_document.js:1058:18)
    at __webpack_require__ (/home/mining/dev/next/.next/server/webpack-runtime.js:25:42)
    at Object.105 (/home/mining/dev/next/.next/server/pages/_document.js:414:38)
    at __webpack_require__ (/home/mining/dev/next/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/mining/dev/next/.next/server/pages/_document.js:1068:39)
    at /home/mining/dev/next/.next/server/pages/_document.js:1069:28
(node:82295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:82295) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:82295) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react'
```


```
Error: Cannot find module 'react'
Require stack:
- /home/mining/dev/next/.next/server/pages/_document.js
- /home/mining/dev/next/arcadia/node_modules/next/dist/server/require.js
- /home/mining/dev/next/arcadia/node_modules/next/dist/server/load-components.js
- /home/mining/dev/next/arcadia/node_modules/next/dist/build/utils.js
- /home/mining/dev/next/arcadia/node_modules/next/dist/build/worker.js
- /home/mining/dev/next/arcadia/node_modules/jest-worker/build/workers/processChild.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by apotdevin** [comment]
This problem is back in release 12.0.9

**Comment by alexparish** [comment]
@timneutkens Would it be possible to re-open this issue? There seems to be a regression in 12.0.9

**Comment by alexparish** [comment]
I've managed to resolve this issue. Documenting here in case it's useful to anyone else.

Next moved `react-is` from "dependencies" to "devDependencies" in its package.json as part of a change published in 12.0.9: https://github.com/vercel/next.js/pull/32742/commits/70822edcdb9b3a281d573ed6fadffa0c4e2b3c4b

My Docker image only contains production dependencies since I use the `yarn --production` command in my Dockerfile to ensure devDependencies aren't installed.

Since the `react-is` is a dependency of at least one of the packages I use (styled-components) I needed to ensure `react-is` is in my dependencies and available to the application. Adding this dependency resolved the issue.

**Comment by amroczeK** [comment]
> I managed to resolve the issue that was throwing this error in my project. Documenting here in case it's useful to anyone following this issue.
> 
> The `react-is` package was moved from "dependencies" to "devDependencies" in Next's package.json as part of a change published in 12.0.9: [70822ed](https://github.com/vercel/next.js/commit/70822edcdb9b3a281d573ed6fadffa0c4e2b3c4b)
> 
> My Docker image only contains production dependencies to ensure it’s as small as possible. I use the `yarn --production` command in my Dockerfile to ensure devDependencies aren't installed.
> 
> Since `react-is` is a peerDependency of at least one of the packages I use ([styled-components](https://github.com/styled-components/styled-components/blob/v5.3.3/packages/styled-components/package.json#L80)) I needed to ensure `react-is` is still available to my application after upgrading to Next 12.0.9. Adding this package to the "dependencies" section of my package.json file resolved the issue.

Thanks this resolved the deployment error I was getting in Vercel

**Comment by balazsorban44** [comment]
For self-hosting, we recommend the official `outputStandalone` mode as it can result in an 80% smaller image size in docker deployments:


https://nextjs.org/blog/next-12-1#self-hosted-nextjs-improvements
