### ISSUE TITLE
[Next@11.0.2-canary23] Cannot find module 'next/dist/next-server/lib/router-context' or its corresponding type declarations.

### ISSUE THREAD

**Issue by wadehammes** [vercel/next.js#27572]
### What version of Next.js are you using?

11.0.2-canary23

### What version of Node.js are you using?

15.8.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

In the latest canary, I cannot find where `RouterContext` was moved to. This is working fine in 11.0.1. I am using this for custom test renderer, without it its going to break a lot of tests.

### Expected Behavior

Import should work fine as it does in 11.0.1. If it has moved, can you tell me where?

### To Reproduce

Try to import RouterContext 

`import { RouterContext } from "next/dist/next-server/lib/router-context";`

**Comment by wadehammes** [comment]
I see the files were moved from `next-server` to `server` in canary-4, but the `router-context` files never made it over...is this deprecated for a reason or was it removed in err?

**Comment by wadehammes** [comment]
File has been moved to `next/dist/shared/lib/router-context` if anyone stumbles upon this

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
