### ISSUE TITLE
with-emotion, with-styled-components: Do not work with Yarn 2 (berry)

### ISSUE THREAD

**Issue by simnalamburt** [vercel/next.js#20410]
# Bug report

## Describe the bug
"with-emotion" example don't work with Yarn 2 (berry). Tested with yarn 2.4.0.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to "examples/with-emotion"
2. Prepare lastest yarn executable (2.4.0)
3. Run `yarn && yarn dev`

## Expected behavior
Up and running Next.js dev server

## Screenshots
```console
$ yarn dev
ready - started server on http://localhost:3000
error - ./.yarn/$$virtual/next-virtual-2f33d32051/0/cache/next-npm-10.0.4-e9908bac70-5ec6818d46.zip/node_modules/next/dist/client/next-dev.js
Error: Cannot find module '@emotion/babel-plugin' from '/home/username/workspace/with-emotion'
    at Array.map (<anonymous>)
    at Generator.next (<anonymous>)
    at loadFileChain.next (<anonymous>)
```

![image](https://user-images.githubusercontent.com/4435445/102958351-0039f380-4520-11eb-97b5-341186329013.png)

## System information

- OS: Windows 10 20H2, Debian 10, WSL2. `Linux redacted 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux`
- Version of Next.js: 10.0.4
- Version of Node.js: 15.5.0
- Deployment: next dev

## Additional contexts
I think https://github.com/vercel/next.js/commit/64850a83487b23fd081ec73ee6a0fa6ca7de9105 has caused this issue.

**Comment by simnalamburt** [comment]
Same issue can be reproduced with "with-styled-components"

![image](https://user-images.githubusercontent.com/4435445/102959176-2d87a100-4522-11eb-8b97-f56518e086f7.png)

**Comment by mlabrum** [comment]
I've hit the same issue, I even tried upgrading to webpack 5.

I did find a workaround though, change your babelrc to babelrc.js and require any plugin.

For example:
```js
module.exports = {
  "presets": [require.resolve("next/babel")],
  "plugins": [[require.resolve("babel-plugin-styled-components"), { "ssr": true }]]
}
```

**Comment by simnalamburt** [comment]
@mlabrum Wow thanks! Maybe we can make patch using your workarounds 👍

**Comment by ludofischer** [comment]
Both examples work with 10.0.5. Updating Babel in https://github.com/vercel/next.js/pull/20586 might have solved this as it apparently solved https://github.com/vercel/next.js/issues/19334 .

**Comment by simnalamburt** [comment]
Thanks for the update! I’m closing this issue as this fixed in https://github.com/vercel/next.js/pull/20586

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
