### ISSUE TITLE
Updating from 12.1.4 to 12.1.5: Error: Cannot find module 'next/dist/shared/lib/router/utils/routing-items.js'

### ISSUE THREAD

**Issue by davidye** [vercel/next.js#36234]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.3
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

After updating from 12.1.4 => 12.1.5 (and 12.1.6-canary.3) I get this build error. Downgrading back to 12.1.4 resolves the issue.

> next -p 8080

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'next/dist/shared/lib/router/utils/routing-items.js'
Require stack:
- /Users/me/hello/client/.next/server/pages/_app.js
- /Users/me/hello/client/node_modules/next/dist/server/require.js
- /Users/me/hello/client/node_modules/next/dist/server/load-components.js
- /Users/me/hello/client/node_modules/next/dist/build/utils.js
- /Users/me/hello/client/node_modules/next/dist/build/output/store.js
- /Users/me/hello/client/node_modules/next/dist/build/output/index.js
- /Users/me/hello/client/node_modules/next/dist/cli/next-dev.js
- /Users/me/hello/client/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/Users/me/hello/client/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object../utils/routing-items (/Users/me/hello/client/.next/server/pages/_app.js:1229:18)
    at __webpack_require__ (/Users/me/hello/client/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/dist/shared/lib/router/router.js:45:21)
    at Object../node_modules/next/dist/shared/lib/router/router.js (/Users/me/hello/client/.next/server/pages/_app.js:99:1)
    at __webpack_require__ (/Users/me/hello/client/.next/server/webpack-runtime.js:33:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/me/hello/client/.next/server/pages/_app.js',
    '/Users/me/hello/client/node_modules/next/dist/server/require.js',
    '/Users/me/hello/client/node_modules/next/dist/server/load-components.js',
    '/Users/me/hello/client/node_modules/next/dist/build/utils.js',
    '/Users/me/hello/client/node_modules/next/dist/build/output/store.js',
    '/Users/me/hello/client/node_modules/next/dist/build/output/index.js',
    '/Users/me/hello/client/node_modules/next/dist/cli/next-dev.js',
    '/Users/me/hello/client/node_modules/next/dist/bin/next'
  ]
}

### Expected Behavior

Build correctly

### To Reproduce

See stack trace, 'next/dist/shared/lib/router/utils/routing-items.js' is missing from node_modules.

**Comment by davidye** [comment]
OK - I was able to fix this issue by deleting ~/.next. Seems like a build cache bug. Latest version removed routing-items.js but cached build files still require it?

**Comment by switz** [comment]
> OK - I was able to fix this issue by deleting ~/.next. Seems like a build cache bug. Latest version removed routing-items.js but cached build files still require it?

+1 this fixed it for me, thanks.

**Comment by timneutkens** [comment]
Did you upgrade Next.js while running the app and didn't reboot after upgrading? Just trying to figure out how to reproduce this.

**Comment by davidye** [comment]
I'm not sure whether Next.js was running during the npm install. But afterwards, restarting with `next -p 8080` would fail with this error. Tried upgrading / downgrading several times and this only resolved after I removed .next.

**Comment by timneutkens** [comment]
That's quite unexpected as the Next.js version is part of the cache key which would mean that any up/downgrade would invalidate the cache.

**Comment by D-Pagey** [comment]
> OK - I was able to fix this issue by deleting ~/.next. Seems like a build cache bug. Latest version removed routing-items.js but cached build files still require it?

Had the same issue and this fixed for me as well 👍

**Comment by davidye** [comment]
> That's quite unexpected as the Next.js version is part of the cache key which would mean that any up/downgrade would invalidate the cache.

It's happened again upon upgrading to 12.1.6

Error: Cannot find module 'next/dist/server/denormalize-page-path.js'

This time I've backed up the problematic ~/.next folder. Let me know if I can help provide additional debugging.

**Comment by untitledlt** [comment]
> Error: Cannot find module 'next/dist/server/denormalize-page-path.js'

I'm getting the same error. 
Downgraded to 12.1.5 until this will be fixed.

**Comment by timneutkens** [comment]
This will most likely be fixed in #36666, just published a new canary version that has that PR: https://github.com/vercel/next.js/releases/tag/v12.1.7-canary.3

**Comment by Alexolo** [comment]
> > Error: Cannot find module 'next/dist/server/denormalize-page-path.js'
> 
> I'm getting the same error. Downgraded to 12.1.5 until this will be fixed.

I had the same error. But for me it was due to having `"next": ^12.1.5"` in my package.json and not including a lock-file when building from the dist-folder, so the resulting build used "12.1.6" instead. 
Locking to 12.1.5 solved it, and I'm looking into copying the lock-file from my monorepo as a build-step to mitigate such issues.

**Comment by BrendanSluke** [comment]
`Error: Cannot find module 'next/dist/server/denormalize-page-path.js'`

Similar to @Alexolo ...

Resolved by changing `package.json` and `package-lock.json` references to next from `12.1.6` to `12.1.5`.

And then deleting node_modules and `npm i` all packages again.

**Comment by Okpainmo** [comment]
Simply deleting the .next folder and running the server afresh("pnpm run dev") resolved the issue for me.

**Comment by Isaac-Tait** [comment]
I was also getting a similar error message:

`error - Error: Cannot find module 'next/dist/shared/lib/router/utils/is-bot.js'`

I tried downgrading `next` from 12.1.6 to 12.1.4 but then I was getting this error message:

`error - Error: Cannot find module 'next/dist/shared/lib/router/utils/remove-trailing-slash.js'`


So, I deleted `.next` and afterward I was able to run `yarn dev` without triggering the error.

**Comment by engineergit** [comment]
@davidye I am facing same error as you mentioned :
Just deleting the .next folder and running npm start again has fixed the issue for me

**Comment by SnowzyTech** [comment]
> OK - I was able to fix this issue by deleting ~/.next. Seems like a build cache bug. Latest version removed routing-items.js but cached build files still require it?



> OK - I was able to fix this issue by deleting ~/.next. Seems like a build cache bug. Latest version removed routing-items.js but cached build files still require it?

Thanks, man this saved a life!

**Comment by ameshkin** [comment]
Appears as if the new raw blitz app is broken.  I am unable to get it working even after deleting .next and node modules folders

**Comment by ZeeshanAhmadKhalil** [comment]
Getting this issue when deployed to AWS elastic Beanstalk:

```
Error: Cannot find module 'next/dist/server/future/route-modules/route-module.js'
Jul 24 09:37:53 ip-172-31-85-238 web: Require stack:
Jul 24 09:37:53 ip-172-31-85-238 web: - /var/app/current/.next/server/pages/_app.js
Jul 24 09:37:53 ip-172-31-85-238 web: - /var/app/current/node_modules/next/dist/server/require.js
Jul 24 09:37:53 ip-172-31-85-238 web: - /var/app/current/node_modules/next/dist/server/next-server.js
Jul 24 09:37:53 ip-172-31-85-238 web: - /var/app/current/node_modules/next/dist/server/next.js
Jul 24 09:37:53 ip-172-31-85-238 web: - /var/app/current/node_modules/next/dist/server/lib/start-server.js
Jul 24 09:37:53 ip-172-31-85-238 web: - /var/app/current/node_modules/next/dist/cli/next-start.js
Jul 24 09:37:53 ip-172-31-85-238 web: - /var/app/current/node_modules/next/dist/lib/commands.js
Jul 24 09:37:53 ip-172-31-85-238 web: - /var/app/current/node_modules/next/dist/bin/next
```

On my local PC `yarn start` works find. But on AWS its giving issue

**Comment by luohao123** [comment]
Same issue here, didn't have any ~/.next folder, delete .next in project root didn't help.

**Comment by Daidalos117** [comment]
Getting this issue when brand new project generated by `blitz new`.

**Comment by colburncodes** [comment]
@Daidalos117 I was able to resolve the error by simply running `npm i next@latest react@latest react-dom@latest eslint-config-next@latest ` after creating blitz my project.

**Comment by colburncodes** [comment]
I had the same issue running `npm i next@latest react@latest react-dom@latest eslint-config-next@latest` after creating my project addressed the issue.

**Comment by Unsleeping** [comment]
i changed it to `"next/dist/shared/lib/app-router-context.shared-runtime"` on next version `"next": "14.1.0",` and this helped me

**Comment by samcx** [comment]
Closing this since there is no <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> for this!
