### ISSUE TITLE
v12.1.5 next_1.default is not a function on path with no default import

### ISSUE THREAD

**Issue by dontsave** [vercel/next.js#36361]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.1.2
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

noticing a regression between 12.1.2 which works and 12.1.5 which breaks on building a path which does not import next default from next. we get the `next_1.default is not a function` but the route tsx does not import next as default. it does import types from `next` but that was working in 12.1.2. babel `7.17.8` webpack `5.70.0`

### Expected Behavior

build succeeds

### To Reproduce

dont have time to generate a minimal repro at the moment. the build is working in 12.1.2 however

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think this was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
