### ISSUE TITLE
Causes an error when any folder in the path starts with "ud"

### ISSUE THREAD

**Issue by EnderWolf50** [vercel/next.js#36078]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.13.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.6
      react: 18.0.0
      react-dom: 18.0.0

### How are you deploying your application? (if relevant)

pnpm run dev

### Describe the Bug

As the title says, I found that I could not successfully run the project using `pnpm run dev` or `yarn run dev` when any of the folders in the path started with "ud".

I've tested this on two computers (both windows) and I get the same error, here is what I got:
```
> ud-test@0.1.0 dev D:\Dev\ud-test
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
error - ./node_modules/.pnpm/next@12.1.5-canary.6_react-dom@18.0.0+react@18.0.0/node_modules/next/dist/client/dev/amp-dev.js
Module not found: Can't resolve 'D:\Devud-test\node_modules\.pnpm\next@12.1.5-canary.6_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\regenerator-runtime\runtime.js' in 'D:\Dev\ud-test\node_modules\.pnpm\next@12.1.5-canary.6_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\client\dev'
```

### Expected Behavior

Dev server normally runs up.

### To Reproduce

- run `pnpm create next-app` to create a project name that starts with "ud".
- `pnpm run dev` or `yarn run dev`

**Comment by balazsorban44** [comment]
This sounds similar to #34000, but I cannot find any `ud`-like RegExp in our code. :thinking:

I can also not reproduce it on my (Linux) machine.

Could you try `npx create-next-app` and `yarn create next-app` to verify it's not a pnpm specific issue?

From the error: `D:\Devud-test` is there a `\` missing? I wonder what's happening there.

**Comment by EnderWolf50** [comment]
> I can also not reproduce it on my (Linux) machine.

Maybe it's a Windows special case? I can't test it because I don't have Linux on hand as my development environment.

> Could you try `npx create-next-app` and `yarn create next-app` to verify it's not a pnpm specific issue?

I've tested both `npx create-next-app` and `yarn create next-app`, and both of them gave me the same error.
(Not post the error codes here because they are exactly the same.)

> From the error: `D:\Devud-test` is there a `\` missing? I wonder what's happening there.

Not sure what's going on there. 🤔
Whenever I have a folder in my path that starts with `ud` and run a development command, the `\` in front of `ud` is automatically eliminated.

Here are the error codes, even though they are the same as the one at the beginning:
```
> my-app@0.1.0 dev D:\Dev\deep\nested\folder\statswith\ud\my-app
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
error - ./node_modules/.pnpm/next@12.1.4_react-dom@18.0.0+react@18.0.0/node_modules/next/dist/client/dev/amp-dev.js
Module not found: Can't resolve 'D:\Dev\deep\nested\folder\statswithud\my-app\node_modules\.pnpm\next@12.1.4_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\regenerator-runtime\runtime.js' in 'D:\Dev\deep\nested\folder\statswith\ud\my-app\node_modules\.pnpm\next@12.1.4_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\client\dev'
```

**Comment by homfred** [comment]
I've experienced this on Windows as well when I had a folder that started with "ud" in the path.  In my case I utilized this command to create the next app:

```
npx create-next-app
```

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro (10.0.19043 Build 19043)
Binaries:
  Node: 16.14.2
  npm: 8.5.0
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 12.1.5
  react: 18.0.0
  react-dom: 18.0.0
```
Error that occurred:

```
$ npm run dev

> next-js-tutorial@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
error - ./node_modules/next/dist/client/dev/amp-dev.js
Module not found: Can't resolve 'E:\codeudemy\next-js-tutorial\node_modules\next\dist\compiled\regenerator-runtime\runtime.js' in 'E:\code\udemy\next-js-tutorial\node_modules\next\dist\client\dev'
```

When I reverted to next 12.1.0 and react 17.0.2 it worked again.

**Comment by EnderWolf50** [comment]
Oh forgot to mention this, when I rolled back the next.js versions to <12.0.4, they all worked fine.

I think it might be some change in 12.0.4 that is causing the problem?

**Comment by sdbxsdb** [comment]
I can also confirm that with React 18 and Next 12.1.5 that you cannot start a project with 'ud'.

Every other scenario is fine but this combination will not allow a dev server to start.
Renaming the project worked perfectly fine.

**Comment by jonrynn** [comment]
It worked when I didn't use udemy -- seriously, someone wrote next.js so you can't have udemy in the folder name?

**Comment by ryanadhi** [comment]
I am facing same issue since yesterday, it misses `\` on the red mark and I can confirm it only fails when the _next_ folder starts with `ud...`

![Screenshot 2022-06-23 120846](https://user-images.githubusercontent.com/35433920/175221991-6eca5eae-1d8a-467a-a283-db3c8b0f4eca.png)
![Screenshot 2022-06-23 121021](https://user-images.githubusercontent.com/35433920/175221993-6e819320-c140-4f91-bd60-659617440d6b.png)


```
   Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0

**Comment by ryanadhi** [comment]
@balazsorban44 I tried several releases and the oldest I tried https://github.com/vercel/next.js/releases/tag/v12.0.8-canary.10

the issue also occurred

**Comment by dewald-els** [comment]
Same issue occurred for me, Had the folder initially named `udemy-next-auth`, I then changed it to `next-auth-section` and it worked.

**Comment by Martin0619** [comment]
I did experience the same. I created a next project with all 3 options yarn, pnpm & npx, and none of them worked when I had a folder named udemy.com. It only worked for me when I renamed the folder. Btw I'm currently using Windows 11.

Binaries:
    Node: v18.4.0
    pnpm: 7.5.1
    yarn: 1.22.19
    npm: 18.12.2
    
package.json:
    "next": "12.2.2",
    "react": "18.2.0",
    "react-dom": "18.2.0"

**Comment by godoshian** [comment]
**oh. my. gosh.** this is the error!!!!! i was going insane 😂👍 for the record, i am a windows user (please don't shun me).

### thank you 🙏🖤

**Comment by johanroug** [comment]
really weird. My project was in a folder called "udemy".
renaming the folder to something without ud worked

**Comment by atlamors** [comment]
+1

   
**Module not found: Error: Can't resolve './node\_modules/next/dist/client/dev/amp-dev' in '/mnt/data/home/901934.cloudwaysapps.com/zknepprnye/public\_html'**

**Comment by simonknittel** [comment]
I'm having a similar if not the same issue.

After upgrading to 13.4.4 I'm getting the error `Error: Filesystem cache is not enabled, cannot read plugin from phsyical path` when running `npm run build` (btw note the typo in `phsyical`).

When running `npm run dev` the error looks like this: `Error: Cannot find module '/Users/simon.knittel/Documents/hmmh/snivy/app/.next/fallback-build-manifest.json'`

As far as I can see, there is no `ud` in that path or anywhere in my filenames.

However, in contrast to @TimFL, only 13.4.4 is broken for me. Downgrading to 13.4.3 reverts the issue.

**Comment by thekip** [comment]
tracking PR: https://github.com/vercel/next.js/pull/50651

**Comment by AkifumiSato** [comment]
This problem also occurs when running [examples/hello-world](https://github.com/AkifumiSato/next.js/tree/canary/examples/hello-world).
Is there any progress?

**Comment by karlkras** [comment]
Why is this still open? Isn't it fixed in v14^?

**Comment by samcx** [comment]
Hi everyone,

I was not able to replicate this in the latest, and it is unlikely this is still an issue.

I will be closing this issue in the meantime!
