### ISSUE TITLE
Cannot build with URL.canParse function

### ISSUE THREAD

**Issue by Semanual** [vercel/next.js#65412]
### Link to the code that reproduces this issue

https://github.com/Semanual/canparse_github_issue

### To Reproduce

1. Run `npm run build`
2. It throws an error "Property 'canParse' does not exist"

### Current vs. Expected behavior

Current:
An error is thrown, as if function URL.canParse didn't exist.

Expected:
Should build with no problems, as [per mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static) this function is built-in.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
  Available memory (MB): 15852
  Available CPU cores: 16
Binaries:
  Node: 22.1.0
  npm: 10.7.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.3.0-canary.40 // Latest available version is detected (14.3.0-canary.40).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

I tested with `next dev` too, and it works as expected. For some reason, it only gives this error in `next build`.

**Comment by icyJoseph** [comment]
Aha, this requires Node 19... 

Could you share more of the error? I will try to find it in the codebase as well.

**Comment by icyJoseph** [comment]
Do other versions trigger this error as well? Otherwise I think maybe some core team members should chime in.

**Comment by Semanual** [comment]
Just tested out with the latest LTS, v20.12.2, same error

**Comment by icyJoseph** [comment]
Well, it worked on 22.1.0 on MacOS, no problem.

**Comment by icyJoseph** [comment]
Using this Page:

```jsx
export default function Home() {
  console.log("can parse:", URL.canParse("https://example.com/"));
  console.log(process.versions.node);
  return null;
```

The build output contains:

```console
   Generating static pages (0/5)  [    ]
can parse: true
22.1.0

can parse: true
22.1.0
 ✓ Generating static pages (5/5)
```

**Comment by Semanual** [comment]
For me, this is the output:
```sh
$ npm run dev  

> dev
> next dev

  ▲ Next.js 14.3.0-canary.40
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 867ms
 ○ Compiling / ...
 ✓ Compiled / in 1050ms (434 modules)
can parse: true
22.1.0
 GET / 200 in 1156ms
```
Works as intended, but:
```sh
$ npm run build

> build
> next build

  ▲ Next.js 14.3.0-canary.40

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types  .Failed to compile.

./app/page.tsx:3:33
Type error: Property 'canParse' does not exist on type '{ new (url: string | URL, base?: string | URL): URL; prototype: URL; createObjectURL(obj: Blob | MediaSource): string; revokeObjectURL(url: string): void; }'.

  1 | /** Add your relevant code here for the issue to reproduce */
  2 | export default function Home() {
> 3 |   console.log("can parse:", URL.canParse("https://example.com/"));
    |                                 ^
  4 |   console.log(process.versions.node);
  5 |   return null;
  6 | }
```
The build still fails

**Comment by r34son** [comment]
Try to upgrade '@types/node'

**Comment by Semanual** [comment]
Now it works, thank you! But well, the repo successfully reproduced the problem, so I guess it's template should also be updated?

**Comment by icyJoseph** [comment]
Right, so it was a TS issue. Where did the template come from?

**Comment by Semanual** [comment]
From [npx create-next-app -e reproduction-template](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template);

**Comment by Semanual** [comment]
Well, okay then, feel free to close as you see fit then (I'm not sure if this is a won't fix or a fixed, so...)

**Comment by allicanseenow** [comment]
The issue happens with next v14.2.11 even with `next dev`, while still working with 14.2.8

**Comment by zhuchaokn** [comment]
> The issue happens with next v14.2.11 even with `next dev`, while still working with 14.2.10, which makes 14.2.11 an unstable version for me. Tested with node.js LTS 20.17.0 and the latest version 22.8.0

Downgrade the next version from 14.2.11 to 14.2.10.
It works for me. 
Same version test of node.

**Comment by srghma** [comment]
my chrome browser doesnt support URL.canParse, had error thrown in browser, fixed by downgrading to 14.2.10

**Comment by TrungNV31197** [comment]
Try this. I ran this command to update the NextJS version. It helped me resolve this error after one day of debugging.

npm i next@rc react@rc react-dom@rc eslint-config-next@rc --force
