### ISSUE TITLE
Cannot find name 'StaticImageData'.

### ISSUE THREAD

**Issue by sakit0** [vercel/next.js#29788]
### What version of Next.js are you using?

11.1.2 & 11.1.3-canary.57

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next build

### Describe the Bug

The following error occurs during type checking.

```bash
node_modules/next/dist/client/image.d.ts:19:14 - error TS2304: Cannot find name 'StaticImageData'.

19     default: StaticImageData;
                ~~~~~~~~~~~~~~~

node_modules/next/dist/client/image.d.ts:21:45 - error TS2304: Cannot find name 'StaticImageData'.

21 declare type StaticImport = StaticRequire | StaticImageData;
                            
```

I got the following Issue in v11.0.0, upgraded to v11.1.2 and the problem was solved, but now I get this error instead.
https://github.com/vercel/next.js/issues/26892

### Expected Behavior

TS compiler should not give errors.

### To Reproduce

Here's the full code to my component:

```js
import { memo, useState, VFC } from 'react';
import Image, { ImageProps } from 'next/image';
import { isTest } from 'src/lib/environmentDetector';

type PropsType = ImageProps & {
  fallback: string | JSX.Element;
};

export const ImageWithFallback: VFC<PropsType> = memo(
  ({ src, fallback, ...rest }) => {
    const [showFallback, setShowFallback] = useState(false);
    if (isTest()) return null;

    const onError = () => {
      setShowFallback(true);
    };

    if (showFallback && typeof fallback !== 'string') return fallback;
    return <Image {...rest} src={showFallback ? (fallback as string) : src} onError={onError} />;
  },
  (p, n) => p.src === n.src
);
```

**Comment by leerob** [comment]
Related: https://stackoverflow.com/questions/69722076/next-js-type-error-cannot-find-name-staticimagedata

Could anyone create a reproduction of this issue so we can investigate? 🙏

**Comment by artmare** [comment]
So, you can add `StaticImageData` to your `*.d.ts` file like this:

```
type StaticImageData = {
  src: string;
  height: number;
  width: number;
  placeholder?: string;
};

declare module '*.gif' {
  const content: StaticImageData;
  export default content;
};
```

**Comment by nbouvrette** [comment]
@timneutkens @leerob I was able to reproduce when updating Next to v12.0.5 or above

Reproduction steps:

1) clone https://github.com/Avansai/next-multilingual
2) `npm install`
3) Update to Next v12.0.5
4) Run `npm run build` (need to install first of course)

Result:

```sh
node_modules/next/dist/client/image.d.ts:19:14 - error TS2304: Cannot find name 'StaticImageData'.

19     default: StaticImageData;
                ~~~~~~~~~~~~~~~

node_modules/next/dist/client/image.d.ts:21:45 - error TS2304: Cannot find name 'StaticImageData'.

21 declare type StaticImport = StaticRequire | StaticImageData;
                                               ~~~~~~~~~~~~~~~


Found 2 errors.
```

**Comment by PrimeObjects** [comment]
Please fix this issue, I can not make a component rely on next in a different npm package

Thanks
Gary

**Comment by nbouvrette** [comment]
I just upgraded today because of the critical issue and had the same problem in Next v12.0.7. I was able to build my project by adding this:

```ts
export declare type StaticImageData = {
  src: string;
  height: number;
  width: number;
  placeholder?: string;
};
```

Directly in `\node_modules\next\dist\client\image.d.ts`

I will try to investigate a bit more tomorrow if I can pinpoint the exact change that caused this.

**Comment by balazsorban44** [comment]
I believe this change might be related: #28316

Using @nbouvrette's repo, I bisected the releases and found that it was introduced in `12.0.5-canary.11`.

**Comment by nbouvrette** [comment]
@balazsorban44 I was actually bisecting on my end as well :) good find, I confirm that `12.0.5-canary.10` can build but [`12.0.5-canary.11`](https://github.com/vercel/next.js/releases/tag/v12.0.5-canary.11) or above cannot. The only change related to "images" in all the PRs is the [one you found](https://github.com/vercel/next.js/pull/28316) (as far as I could tell).

I am not sure exactly which part of that change is causing this in `next/dist/client/image.d.ts`

<img width="606" alt="image" src="https://user-images.githubusercontent.com/6453322/147303393-c872f6a2-ecdb-4370-9174-d2e35aa6400d.png">

I'm also a bit surprised that this is the only issue on this topic given that `12.0.5` has been released 20 days ago. Is the original issue in this thread the same one or should we open a new one related to `12.0.5-canary.11`?

Also, I found a workaround:

1) Create a `Global.d.ts` type file in my `src` directory
2) Add the following code:
```ts
// Workaround related to: https://github.com/vercel/next.js/issues/29788
declare type StaticImageData = {
  src: string;
  height: number;
  width: number;
  placeholder?: string;
};
```
3) Build

**Comment by EstebanBorai** [comment]
I have the same issue, a reproduction can be found in this repository: https://github.com/TheComputersClub/teampost/commit/0c6b289deada6437b843978fb2421b7fb33f22f7

**Comment by atcastle** [comment]
Is anyone still experiencing this issue? I can't reproduce this, and based on the lack of activity in this issue I'm thinking it's probably fixed. I'll close in a day or two unless I hear otherwise.

**Comment by nbouvrette** [comment]
@atcastle yes - easy to reproduce using `v12.0.10`:

1) Clone `https://github.com/Avansai/next-multilingual.git`
2) `npm install`
3) `npm build`
Now remove the work around:
4) `mv ./src/Global.d.ts ./src/Global.d.ts.old`
5) `npm build`

Voilà:

```sh
$ npm run build

> next-multilingual@0.10.3 build
> rm -Rf ./lib && tsc

node_modules/next/dist/client/image.d.ts:19:14 - error TS2304: Cannot find name 'StaticImageData'.

19     default: StaticImageData;
                ~~~~~~~~~~~~~~~

node_modules/next/dist/client/image.d.ts:21:45 - error TS2304: Cannot find name 'StaticImageData'.

21 declare type StaticImport = StaticRequire | StaticImageData;
                                               ~~~~~~~~~~~~~~~


Found 2 errors.
```

**Comment by atcastle** [comment]
@nbouvrette Thanks, I was able to reproduce with that.

@lfades it looks like this issue was introduced by your change in https://github.com/vercel/next.js/pull/28316. Could you take a look at this?

**Comment by SpencerKaiser** [comment]
I just installed 12.1.0 and I'm still experiencing this issue; was this issue closed because it was fixed in a future release?

**Comment by unknownbreaker** [comment]
> 

Which *.d.ts file did you insert your workaround into?

**Comment by SpencerKaiser** [comment]
@unknownbreaker I used [`patch-package`](https://www.npmjs.com/package/patch-package) and modified `next/dist/client/image.d.ts`. After configuring `patch-package`, making the change suggested by @esafev posted to the file above, and running `yarn patch-package next` this is the output you should get within `YOUR_ROOT/patches/next+12.1.0.patch`: 

```
diff --git a/node_modules/next/dist/client/image.d.ts b/node_modules/next/dist/client/image.d.ts
index a8bf17f..0908c0e 100644
--- a/node_modules/next/dist/client/image.d.ts
+++ b/node_modules/next/dist/client/image.d.ts
@@ -20,6 +20,12 @@ declare type OnLoadingComplete = (result: {
     naturalHeight: number;
 }) => void;
 declare type ImgElementStyle = NonNullable<JSX.IntrinsicElements['img']['style']>;
+export interface StaticImageData {
+   src: string
+   height: number
+   width: number
+   blurDataURL?: string
+ }
 interface StaticRequire {
     default: StaticImageData;
 }
```

Hope that helps 🍻

**Comment by balazsorban44** [comment]
`patch-package` should not be necessary, could you test out `canary` and if it does not work, open a new bug report? Thanks!

**Comment by SpencerKaiser** [comment]
I dug through the source of the PR that closed this issue and everything looks good, I just wasn't ready to switch to `canary` just yet 😬

**Comment by balazsorban44** [comment]
It's fine, I just wanted to point out to the next person reading that there is no need for hacks anymore, as this has been fixed in Next.js already. :+1:

**Comment by SpencerKaiser** [comment]
I get that for sure, but I think a lot of folks may not want to switch to a `canary` branch (or unfamiliar with how to do so) and I think `patch-package` is a whole lot better than using an `index.d.ts` file, so I wanted to share.

**Comment by unknownbreaker** [comment]
@balazsorban44 Unfortunately, I can't use `canary`. I have to stick with the stable version.

**Comment by unknownbreaker** [comment]
@SpencerKaiser Do you have to manually change the `image.d.ts` file AFTER you've cloned down the repo? I need to make sure that my app just works after cloning and installing.

**Comment by SpencerKaiser** [comment]
@unknownbreaker...

1. Follow the instructions to setup that package for your project's repo
2. Make the change to `Next` as I mentioned above
3. Run the command to generate the `.patch` file

The next time someone runs `npm i` or `yarn`, it'll apply that patch and things will work as expected 😄
